// scripts/ingest-vda-isa-extended.ts
// Extended VDA ISA (TISAX) — deeper automotive controls covering connected
// vehicles, ADAS data, supplier chain, software updates (UNECE R155/R156),
// and extended prototype protection.

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'vda-isa-extended.json');

const controls = [
  // Connected Vehicle Security
  { control_number: 'ISA-EXT-CV-01', title_nl: 'Cybersicherheitsmanagement nach UNECE R155', title: 'Cybersecurity management per UNECE R155', description_nl: 'Fahrzeughersteller MUESSEN ein Cybersecurity Management System (CSMS) nach UNECE R155 etablieren. Das CSMS MUSS Risikoanalyse, Bedrohungserkennung und Incident-Response fuer Fahrzeuge abdecken.', description: 'Vehicle manufacturers MUST establish a Cybersecurity Management System (CSMS) per UNECE R155. The CSMS MUST cover risk analysis, threat detection, and incident response for vehicles.', category: 'Connected Vehicle', subcategory: 'CSMS', level: 'MUSS', iso_mapping: 'A.5.1', implementation_guidance: 'CSMS nach ISO/SAE 21434 aufbauen. UNECE R155 Typgenehmigung nachweisen.', verification_guidance: 'CSMS-Zertifizierung und UNECE R155-Konformitaet pruefen.', source_url: null },
  { control_number: 'ISA-EXT-CV-02', title_nl: 'Software-Update-Management nach UNECE R156', title: 'Software update management per UNECE R156', description_nl: 'Fahrzeughersteller MUESSEN ein Software Update Management System (SUMS) nach UNECE R156 betreiben. Over-the-Air-Updates MUESSEN authentifiziert und integritaetsgeschuetzt sein.', description: 'Vehicle manufacturers MUST operate a Software Update Management System (SUMS) per UNECE R156. Over-the-air updates MUST be authenticated and integrity-protected.', category: 'Connected Vehicle', subcategory: 'SUMS', level: 'MUSS', iso_mapping: 'A.8.32', implementation_guidance: 'SUMS nach R156 mit Versionskontrolle. OTA-Signierung. Rollback-Faehigkeit.', verification_guidance: 'SUMS-Prozess und OTA-Signaturverfahren pruefen.', source_url: null },
  { control_number: 'ISA-EXT-CV-03', title_nl: 'V2X-Kommunikationssicherheit', title: 'V2X communication security', description_nl: 'Vehicle-to-Everything (V2X) Kommunikation MUSS durch PKI-basierte Zertifikate abgesichert werden. Pseudonymisierung MUSS den Datenschutz der Fahrzeughalter gewaehrleisten.', description: 'Vehicle-to-Everything (V2X) communication MUST be secured by PKI-based certificates. Pseudonymization MUST ensure privacy of vehicle owners.', category: 'Connected Vehicle', subcategory: 'V2X', level: 'MUSS', iso_mapping: 'A.8.24', implementation_guidance: 'V2X-PKI mit Pseudonym-Zertifikaten. ETSI ITS Security Standards. IEEE 1609.2.', verification_guidance: 'V2X-Zertifikatsinfrastruktur und Pseudonymisierung pruefen.', source_url: null },
  { control_number: 'ISA-EXT-CV-04', title_nl: 'Absicherung fahrzeuginterner Bussysteme', title: 'Securing in-vehicle bus systems', description_nl: 'CAN-Bus, LIN, FlexRay und Ethernet-Kommunikation im Fahrzeug MUESSEN gegen Manipulation geschuetzt werden. Gateway-ECUs MUESSEN nicht autorisierte Nachrichten filtern.', description: 'CAN bus, LIN, FlexRay, and automotive Ethernet communication MUST be protected against manipulation. Gateway ECUs MUST filter unauthorized messages.', category: 'Connected Vehicle', subcategory: 'In-Vehicle Network', level: 'MUSS', iso_mapping: 'A.8.22', implementation_guidance: 'SecOC fuer CAN. AUTOSAR SecOC-Module. Intrusion Detection fuer CAN-Bus.', verification_guidance: 'In-Vehicle-Network-Segmentierung und SecOC-Implementation pruefen.', source_url: null },
  { control_number: 'ISA-EXT-CV-05', title_nl: 'Absicherung von Infotainment-Systemen', title: 'Securing infotainment systems', description_nl: 'Infotainment-Systeme MUESSEN von sicherheitskritischen Fahrzeugsystemen getrennt sein. Externe Schnittstellen (Bluetooth, USB, Wi-Fi) MUESSEN gehaertet und ueberwacht werden.', description: 'Infotainment systems MUST be separated from safety-critical vehicle systems. External interfaces (Bluetooth, USB, Wi-Fi) MUST be hardened and monitored.', category: 'Connected Vehicle', subcategory: 'Infotainment', level: 'MUSS', iso_mapping: 'A.8.22', implementation_guidance: 'Domain-Separation (Hypervisor). Schnittstellen-Haertung. App-Sandboxing.', verification_guidance: 'Trennung Infotainment/Safety und Schnittstellen-Haertung pruefen.', source_url: null },

  // ADAS and Autonomous Driving Data
  { control_number: 'ISA-EXT-ADAS-01', title_nl: 'Schutz von ADAS-Trainingsdaten', title: 'Protection of ADAS training data', description_nl: 'Trainingsdaten fuer ADAS und autonomes Fahren MUESSEN als streng vertraulich klassifiziert werden. Zugriff MUSS auf benannte Entwickler beschraenkt sein.', description: 'Training data for ADAS and autonomous driving MUST be classified as strictly confidential. Access MUST be restricted to named developers.', category: 'ADAS/AD', subcategory: 'Trainingsdaten', level: 'MUSS', iso_mapping: 'A.5.12', implementation_guidance: 'Klassifizierung streng vertraulich. Verschluesselte Speicherung. Named-Access-Only.', verification_guidance: 'Klassifizierung und Zugriffskontrolle der ADAS-Trainingsdaten pruefen.', source_url: null },
  { control_number: 'ISA-EXT-ADAS-02', title_nl: 'Integritaetsschutz von Sensordaten', title: 'Integrity protection of sensor data', description_nl: 'Sensordaten (LiDAR, Radar, Kamera) MUESSEN integritaetsgeschuetzt verarbeitet werden. Spoofing-Angriffe MUESSEN durch Plausibilitaetspruefungen erkannt werden.', description: 'Sensor data (LiDAR, radar, camera) MUST be processed with integrity protection. Spoofing attacks MUST be detected through plausibility checks.', category: 'ADAS/AD', subcategory: 'Sensordaten', level: 'MUSS', iso_mapping: 'A.8.4', implementation_guidance: 'Sensor-Fusion mit Plausibilitaetspruefung. Anti-Spoofing fuer GPS/LiDAR/Radar.', verification_guidance: 'Sensor-Integritaet und Anti-Spoofing-Massnahmen pruefen.', source_url: null },

  // Extended Supply Chain
  { control_number: 'ISA-EXT-SC-01', title_nl: 'TISAX-Anforderungen an Zulieferer', title: 'TISAX requirements for suppliers', description_nl: 'Zulieferer, die Zugang zu vertraulichen oder streng vertraulichen Informationen des OEM haben, MUESSEN TISAX-zertifiziert sein. Das Assessment-Level MUSS dem Schutzbedarf entsprechen.', description: 'Suppliers with access to confidential or strictly confidential OEM information MUST be TISAX-certified. The assessment level MUST match the protection needs.', category: 'Lieferkette', subcategory: 'TISAX-Zertifizierung', level: 'MUSS', iso_mapping: 'A.5.21', implementation_guidance: 'TISAX-Pflicht in Lieferantenvertraege aufnehmen. Assessment-Level AL2 oder AL3 je nach Schutzbedarf.', verification_guidance: 'TISAX-Zertifizierungsstatus aller relevanten Zulieferer pruefen.', source_url: null },
  { control_number: 'ISA-EXT-SC-02', title_nl: 'Software-Lieferkettensicherheit (Automotive SBOM)', title: 'Software supply chain security (Automotive SBOM)', description_nl: 'Zulieferer von Software-Komponenten MUESSEN eine Software-Stueckliste (SBOM) bereitstellen. Bekannte Schwachstellen in Abhaengigkeiten MUESSEN dem OEM gemeldet werden.', description: 'Suppliers of software components MUST provide a software bill of materials (SBOM). Known vulnerabilities in dependencies MUST be reported to the OEM.', category: 'Lieferkette', subcategory: 'Software-SBOM', level: 'MUSS', iso_mapping: 'A.5.21', implementation_guidance: 'SBOM im CycloneDX-Format. Automatische CVE-Ueberwachung der Abhaengigkeiten. VEX-Reports.', verification_guidance: 'SBOM-Bereitstellung und CVE-Monitoring pruefen.', source_url: null },
  { control_number: 'ISA-EXT-SC-03', title_nl: 'Sichere Datenuebertragung in der Lieferkette', title: 'Secure data transfer in supply chain', description_nl: 'Der Austausch vertraulicher Konstruktionsdaten zwischen OEM und Zulieferer MUSS ueber verschluesselte Kanaele erfolgen. Unverschluesselter E-Mail-Versand von CAD-Daten ist VERBOTEN.', description: 'Exchange of confidential design data between OEM and supplier MUST use encrypted channels. Unencrypted email transmission of CAD data is PROHIBITED.', category: 'Lieferkette', subcategory: 'Datenaustausch', level: 'MUSS', iso_mapping: 'A.5.14', implementation_guidance: 'Sichere Austauschplattformen (ENX, OFTP2). Keine unverschluesselte E-Mail fuer CAD/Prototypen.', verification_guidance: 'Datenaustauschkanaele und Verschluesselung pruefen.', source_url: null },

  // Extended Prototype Protection
  { control_number: 'ISA-EXT-PP-01', title_nl: 'Drohnenabwehr fuer Testgelaende', title: 'Drone defense for test sites', description_nl: 'Auf Testgelaenden, auf denen Prototypen erprobt werden, MUESSEN Drohnenerkennungssysteme installiert sein. Es MUESSEN Gegenmassnahmen gegen unautorisierten Drohnenflug definiert sein.', description: 'Drone detection systems MUST be installed at test sites where prototypes are tested. Countermeasures against unauthorized drone flights MUST be defined.', category: 'Prototypenschutz', subcategory: 'Drohnenabwehr', level: 'MUSS', iso_mapping: 'A.7.4', implementation_guidance: 'RF-basierte Drohnenerkennung. Geofencing. Eskalationsprozess bei Drohnen-Detection.', verification_guidance: 'Drohnenerkennungssysteme und Reaktionsprozesse pruefen.', source_url: null },
  { control_number: 'ISA-EXT-PP-02', title_nl: 'Prototypen-Tracking und Inventar', title: 'Prototype tracking and inventory', description_nl: 'Alle physischen Prototypen und Prototypen-Komponenten MUESSEN in einem Tracking-System erfasst sein. Standort und Verbleib MUESSEN jederzeit nachvollziehbar sein.', description: 'All physical prototypes and prototype components MUST be recorded in a tracking system. Location and whereabouts MUST be traceable at all times.', category: 'Prototypenschutz', subcategory: 'Tracking', level: 'MUSS', iso_mapping: 'A.5.9', implementation_guidance: 'RFID/GPS-Tracking fuer Prototypen. Inventarsystem mit Check-in/Check-out. Standort-Audit.', verification_guidance: 'Prototypen-Tracking-System und Inventar-Vollstaendigkeit pruefen.', source_url: null },
  { control_number: 'ISA-EXT-PP-03', title_nl: 'Medienkontrolle bei Prototypen-Events', title: 'Media control at prototype events', description_nl: 'Bei Veranstaltungen mit Prototypen MUESSEN alle Teilnehmer auf Aufnahmegeraete kontrolliert werden. Smartphones MUESSEN bei Betreten des Prototypen-Bereichs abgegeben oder mit Kameraabdeckung versehen werden.', description: 'At events with prototypes, all participants MUST be checked for recording devices. Smartphones MUST be surrendered or fitted with camera covers when entering prototype areas.', category: 'Prototypenschutz', subcategory: 'Medienkontrolle', level: 'MUSS', iso_mapping: 'A.7.2', implementation_guidance: 'Kamera-Sticker/Cases. Smartphone-Sammelstelle. Einlasskontrolle mit Geraetepruefung.', verification_guidance: 'Medienkontroll-Massnahmen und Durchsetzung pruefen.', source_url: null },

  // Extended Access Control
  { control_number: 'ISA-EXT-AC-01', title_nl: 'Multi-Faktor-Authentisierung fuer kritische Systeme', title: 'Multi-factor authentication for critical systems', description_nl: 'Fuer Zugriff auf streng vertrauliche Informationen und kritische Systeme MUSS Multi-Faktor-Authentisierung eingesetzt werden.', description: 'Multi-factor authentication MUST be used for access to strictly confidential information and critical systems.', category: 'Zugriffskontrolle', subcategory: 'MFA', level: 'MUSS', iso_mapping: 'A.8.5', implementation_guidance: 'MFA fuer PLM, SCM, und Prototypen-Systeme. Hardware-Token oder FIDO2 bevorzugt.', verification_guidance: 'MFA-Abdeckung kritischer Systeme pruefen.', source_url: null },
  { control_number: 'ISA-EXT-AC-02', title_nl: 'Zugriffskontrolle fuer Entwicklungsumgebungen', title: 'Access control for development environments', description_nl: 'Entwicklungsumgebungen mit Prototypen-Daten MUESSEN durch Netzwerksegmentierung und Zugriffskontrolle geschuetzt sein. Code-Repositories mit vertraulichem Quellcode MUESSEN RBAC implementieren.', description: 'Development environments with prototype data MUST be protected by network segmentation and access control. Code repositories with confidential source code MUST implement RBAC.', category: 'Zugriffskontrolle', subcategory: 'Entwicklung', level: 'MUSS', iso_mapping: 'A.8.2', implementation_guidance: 'Segmentiertes Entwicklungsnetz. RBAC fuer Git-Repos. Commit-Signierung fuer Steuergeraete-Software.', verification_guidance: 'Netzwerksegmentierung und Repository-Zugriffsrechte pruefen.', source_url: null },

  // Compliance and Audit
  { control_number: 'ISA-EXT-AUD-01', title_nl: 'TISAX-Assessment-Vorbereitung', title: 'TISAX assessment preparation', description_nl: 'Organisationen MUESSEN ein internes Audit-Programm betreiben, das die TISAX-Anforderungen abdeckt. Internes Audit MUSS vor dem externen Assessment durchgefuehrt werden.', description: 'Organizations MUST operate an internal audit program covering TISAX requirements. Internal audit MUST be performed before external assessment.', category: 'Compliance', subcategory: 'TISAX-Audit', level: 'MUSS', iso_mapping: 'A.5.35', implementation_guidance: 'Internes TISAX-Pre-Audit. Gap-Analyse. Massnahmenplan mit Verantwortlichen und Fristen.', verification_guidance: 'Internes Audit-Programm und Pre-Assessment-Ergebnisse pruefen.', source_url: null },
  { control_number: 'ISA-EXT-AUD-02', title_nl: 'Continuous Improvement nach TISAX', title: 'Continuous improvement per TISAX', description_nl: 'Erkannte Schwaechen aus TISAX-Assessments MUESSEN in einem Massnahmenplan adressiert werden. Der Reifegrad MUSS kontinuierlich verbessert werden (Ziel: Maturity Level 3 oder hoeher).', description: 'Weaknesses identified from TISAX assessments MUST be addressed in an action plan. Maturity level MUST be continuously improved (target: Maturity Level 3 or higher).', category: 'Compliance', subcategory: 'Verbesserung', level: 'MUSS', iso_mapping: 'A.5.36', implementation_guidance: 'Massnahmenplan mit KPIs. Tracking der Umsetzung. Quartalsweises Management-Review.', verification_guidance: 'Massnahmenplan-Fortschritt und Reifegrad-Entwicklung pruefen.', source_url: null },

  // Secure Development Lifecycle (Automotive SDLC)
  { control_number: 'ISA-EXT-DEV-01', title_nl: 'Sichere Softwareentwicklung nach ISO/SAE 21434', title: 'Secure software development per ISO/SAE 21434', description_nl: 'Die Entwicklung von Fahrzeugsoftware MUSS einem sicheren Entwicklungsprozess nach ISO/SAE 21434 folgen. Threat Analysis and Risk Assessment (TARA) MUSS fuer alle sicherheitsrelevanten Komponenten durchgefuehrt werden.', description: 'Vehicle software development MUST follow a secure development process per ISO/SAE 21434. Threat Analysis and Risk Assessment (TARA) MUST be performed for all security-relevant components.', category: 'Entwicklung', subcategory: 'Secure SDLC', level: 'MUSS', iso_mapping: 'A.8.25', implementation_guidance: 'ISO/SAE 21434-konformer SDLC. TARA pro ECU/Software-Komponente. Security by Design.', verification_guidance: 'SDLC-Prozess und TARA-Dokumentation pruefen.', source_url: null },
  { control_number: 'ISA-EXT-DEV-02', title_nl: 'Sichere Codierung fuer Steuergeraete', title: 'Secure coding for ECUs', description_nl: 'Quellcode fuer Steuergeraete MUSS nach MISRA C/C++ oder vergleichbaren Coding-Standards entwickelt werden. Statische Code-Analyse MUSS in den CI/CD-Prozess integriert sein.', description: 'Source code for ECUs MUST be developed according to MISRA C/C++ or comparable coding standards. Static code analysis MUST be integrated into the CI/CD process.', category: 'Entwicklung', subcategory: 'Secure Coding', level: 'MUSS', iso_mapping: 'A.8.28', implementation_guidance: 'MISRA C:2012 Compliance. SAST in CI-Pipeline. Peer-Review fuer sicherheitskritischen Code.', verification_guidance: 'MISRA-Compliance-Reports und SAST-Integration pruefen.', source_url: null },
  { control_number: 'ISA-EXT-DEV-03', title_nl: 'Penetrationstests fuer Fahrzeugsysteme', title: 'Penetration testing for vehicle systems', description_nl: 'Fahrzeugsysteme mit externen Schnittstellen (Telematik, OBD, Infotainment) MUESSEN vor dem SOP (Start of Production) Penetrationstests unterzogen werden.', description: 'Vehicle systems with external interfaces (telematics, OBD, infotainment) MUST undergo penetration testing before SOP (Start of Production).', category: 'Entwicklung', subcategory: 'Sicherheitstests', level: 'MUSS', iso_mapping: 'A.8.34', implementation_guidance: 'Automotive-spezifische Pentests (CAN, V2X, Telematik). Pre-SOP-Gate. Retest nach Behebung.', verification_guidance: 'Pentest-Reports und Schwachstellenbehandlung pruefen.', source_url: null },

  // Data Privacy (Automotive)
  { control_number: 'ISA-EXT-DP-01', title_nl: 'Datenschutz bei Fahrzeugdaten', title: 'Data protection for vehicle data', description_nl: 'Fahrzeugdaten, die Rueckschluesse auf das Fahrverhalten oder den Aufenthaltsort des Halters ermoeglichen, MUESSEN als personenbezogene Daten behandelt und DSGVO-konform verarbeitet werden.', description: 'Vehicle data enabling conclusions about driving behavior or location of the owner MUST be treated as personal data and processed GDPR-compliantly.', category: 'Datenschutz', subcategory: 'Fahrzeugdaten', level: 'MUSS', iso_mapping: 'A.5.34', implementation_guidance: 'DSFA fuer Telematikdaten. Anonymisierung/Pseudonymisierung. Einwilligung oder Rechtsgrundlage.', verification_guidance: 'DSFA und DSGVO-Konformitaet fuer Fahrzeugdaten pruefen.', source_url: null },
  { control_number: 'ISA-EXT-DP-02', title_nl: 'Datenminimierung bei Connected Services', title: 'Data minimization for connected services', description_nl: 'Connected Services MUESSEN nach dem Grundsatz der Datenminimierung konzipiert werden. Nur die fuer den jeweiligen Dienst erforderlichen Daten DUERFEN erhoben werden.', description: 'Connected services MUST be designed according to the principle of data minimization. Only data required for the respective service MAY be collected.', category: 'Datenschutz', subcategory: 'Datenminimierung', level: 'MUSS', iso_mapping: 'A.5.34', implementation_guidance: 'Privacy by Design fuer Connected Services. Datenminimierungs-Review bei Service-Design.', verification_guidance: 'Datenminimierung und Erforderlichkeit der erhobenen Daten pruefen.', source_url: null },

  // HSM and Key Management
  { control_number: 'ISA-EXT-KM-01', title_nl: 'Hardware Security Modules in Steuergeraeten', title: 'Hardware security modules in ECUs', description_nl: 'Sicherheitskritische Steuergeraete MUESSEN ueber Hardware Security Modules (HSM) verfuegen. Kryptographische Schluessel MUESSEN im HSM gespeichert und verarbeitet werden.', description: 'Safety-critical ECUs MUST have Hardware Security Modules (HSM). Cryptographic keys MUST be stored and processed in the HSM.', category: 'Kryptographie', subcategory: 'HSM', level: 'MUSS', iso_mapping: 'A.8.24', implementation_guidance: 'SHE+ oder HSM nach EVITA. Schluesselinjizierung in sicherer Produktionsumgebung.', verification_guidance: 'HSM-Ausstattung und Schluesselmanagement pruefen.', source_url: null },
  { control_number: 'ISA-EXT-KM-02', title_nl: 'Schluesselmanagement fuer Fahrzeugflotten', title: 'Key management for vehicle fleets', description_nl: 'Es MUSS ein Schluesselmanagement-System fuer die gesamte Fahrzeugflotte existieren. Schluessel MUESSEN individuell pro Fahrzeug oder ECU sein. Master-Schluessel MUESSEN besonders geschuetzt werden.', description: 'A key management system for the entire vehicle fleet MUST exist. Keys MUST be individual per vehicle or ECU. Master keys MUST be specially protected.', category: 'Kryptographie', subcategory: 'Schluesselmanagement', level: 'MUSS', iso_mapping: 'A.8.24', implementation_guidance: 'KMS fuer Fahrzeugflotte. Individuelle Schluessel pro ECU. HSM-geschuetzte Master-Keys.', verification_guidance: 'KMS-Architektur und Schluessel-Individualitaet pruefen.', source_url: null },

  // Incident Response (Automotive)
  { control_number: 'ISA-EXT-IR-01', title_nl: 'Automotive CERT/PSIRT', title: 'Automotive CERT/PSIRT', description_nl: 'Fahrzeughersteller MUESSEN ein Product Security Incident Response Team (PSIRT) betreiben. Das PSIRT MUSS Schwachstellenmeldungen entgegennehmen und Koordination mit AUTO-ISAC sicherstellen.', description: 'Vehicle manufacturers MUST operate a Product Security Incident Response Team (PSIRT). The PSIRT MUST accept vulnerability reports and ensure coordination with AUTO-ISAC.', category: 'Vorfallsmanagement', subcategory: 'PSIRT', level: 'MUSS', iso_mapping: 'A.5.24', implementation_guidance: 'PSIRT mit 24h-Erreichbarkeit. VDP publizieren. AUTO-ISAC-Mitgliedschaft.', verification_guidance: 'PSIRT-Organisation und AUTO-ISAC-Anbindung pruefen.', source_url: null },
  { control_number: 'ISA-EXT-IR-02', title_nl: 'Sicherheitsvorfall-Eskalation an OEM', title: 'Security incident escalation to OEM', description_nl: 'Zulieferer MUESSEN Sicherheitsvorfaelle, die das Produkt des OEM betreffen, innerhalb von 24 Stunden an den OEM melden. Die Meldung MUSS Schwachstelle, Auswirkung und Gegenmassnahmen enthalten.', description: 'Suppliers MUST report security incidents affecting the OEM product to the OEM within 24 hours. The report MUST contain vulnerability, impact, and countermeasures.', category: 'Vorfallsmanagement', subcategory: 'Eskalation', level: 'MUSS', iso_mapping: 'A.5.26', implementation_guidance: '24h-Meldefrist in Lieferantenvertraegen. Standardisiertes Meldeformular. Eskalationspfad.', verification_guidance: 'Meldeprozess und 24h-Frist in Lieferantenvertraegen pruefen.', source_url: null },

  // Cloud and SaaS in Automotive
  { control_number: 'ISA-EXT-CL-01', title_nl: 'Cloud-Nutzung fuer Fahrzeugdaten', title: 'Cloud use for vehicle data', description_nl: 'Wenn Fahrzeugdaten in Cloud-Diensten verarbeitet werden, MUESSEN die Anforderungen an Datenlokalisierung (EU/EWR) und Mandantentrennung erfuellt werden.', description: 'When vehicle data is processed in cloud services, requirements for data localization (EU/EEA) and tenant separation MUST be met.', category: 'Cloud', subcategory: 'Fahrzeug-Cloud', level: 'MUSS', iso_mapping: 'A.5.23', implementation_guidance: 'EU/EWR-Rechenzentren. Mandantentrennung. Verschluesselung mit eigenen Schluesseln (BYOK).', verification_guidance: 'Datenlokalisierung und Mandantentrennung pruefen.', source_url: null },

  // Physical Security Extension
  { control_number: 'ISA-EXT-PS-01', title_nl: 'Absicherung von Pruefstaenden', title: 'Securing test benches', description_nl: 'Pruefstaende fuer Prototypen-Komponenten MUESSEN in zugangsgesicherten Bereichen betrieben werden. Testergebnisse MUESSEN vertraulich behandelt werden.', description: 'Test benches for prototype components MUST be operated in access-secured areas. Test results MUST be treated confidentially.', category: 'Physische Sicherheit', subcategory: 'Pruefstaende', level: 'MUSS', iso_mapping: 'A.7.1', implementation_guidance: 'Zutrittskontrolle fuer Pruefstand-Bereiche. Vertraulichkeit der Messergebnisse.', verification_guidance: 'Pruefstand-Sicherheit und Datenklassifizierung pruefen.', source_url: null },
  { control_number: 'ISA-EXT-PS-02', title_nl: 'Besuchermanagement in Entwicklungszentren', title: 'Visitor management in development centers', description_nl: 'Besucher in Entwicklungszentren MUESSEN registriert und begleitet werden. Der Zugang zu Prototypen-Bereichen MUSS fuer Besucher grundsaetzlich gesperrt sein, es sei denn, eine Ausnahmegenehmigung liegt vor.', description: 'Visitors to development centers MUST be registered and escorted. Access to prototype areas MUST be blocked for visitors by default unless an exception permit exists.', category: 'Physische Sicherheit', subcategory: 'Besuchermanagement', level: 'MUSS', iso_mapping: 'A.7.2', implementation_guidance: 'Elektronisches Besuchermanagementsystem. Begleitung fuer alle Besucher. Ausnahme nur mit ISB-Genehmigung.', verification_guidance: 'Besuchermanagement und Prototypen-Zugangsrestriktionen pruefen.', source_url: null },

  // Backup and Recovery (Automotive)
  { control_number: 'ISA-EXT-BR-01', title_nl: 'Sicherung von Konstruktionsdaten', title: 'Backup of design data', description_nl: 'CAD-Daten, Simulationsergebnisse und Konstruktionsdaten MUESSEN mindestens taeglich gesichert werden. Backups MUESSEN verschluesselt und an einem separaten Standort aufbewahrt werden.', description: 'CAD data, simulation results, and design data MUST be backed up at least daily. Backups MUST be encrypted and stored at a separate location.', category: 'Business Continuity', subcategory: 'Datensicherung', level: 'MUSS', iso_mapping: 'A.8.13', implementation_guidance: 'Taegliche inkrementelle, woechentliche Voll-Backups. Verschluesselung. Offsite-Replikation.', verification_guidance: 'Backup-Frequenz, Verschluesselung und Offsite-Aufbewahrung pruefen.', source_url: null },
];

const output = {
  framework: {
    id: 'vda-isa-extended',
    name: 'VDA ISA Extended (TISAX, UNECE R155/R156, ISO/SAE 21434)',
    name_nl: 'VDA ISA Erweitert (TISAX, UNECE R155/R156, ISO/SAE 21434)',
    issuing_body: 'Verband der Automobilindustrie (VDA)',
    version: '6.0 Extended (2024)',
    effective_date: '2024-01-01',
    scope: 'Extended automotive security: connected vehicle cybersecurity (UNECE R155/R156), ADAS data protection, supplier chain TISAX, prototype protection, HSM key management, automotive PSIRT, and secure ECU development (ISO/SAE 21434)',
    scope_sectors: ['automotive', 'manufacturing'],
    structure_description: 'Covers connected vehicle (CSMS, SUMS, V2X, in-vehicle networks, infotainment), ADAS data, supply chain (TISAX certification, SBOM), prototype protection (drones, tracking, media control), access control, development (ISO/SAE 21434, MISRA, pentesting), data privacy, HSM/key management, PSIRT, cloud, physical security, and backup.',
    source_url: 'https://www.vda.de/de/themen/digitalisierung/daten/informationssicherheit',
    license: 'VDA copyright — control domains publicly available',
    language: 'de+en',
  },
  controls,
  metadata: { ingested_at: new Date().toISOString(), total_controls: controls.length },
};

mkdirSync(DATA_DIR, { recursive: true });
writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
console.log(`VDA ISA Extended: ${controls.length} controls written to ${OUTPUT_FILE}`);
