// scripts/ingest-bsi-tr-extended-2.ts
// Further BSI Technical Guidelines: TR-03153 (Internet of Things),
// TR-03160 (Smart Metering), TR-03146 (eID-Server), TR-03124 (eID-Client),
// TR-03105 (Conformity Testing), TR-03171 (FIDO2), TR-03185 (Cyber-Physical Systems).

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'bsi-tr-extended-2.json');

const controls = [
  // TR-03153 — IT Security for Smart Meters
  { control_number: 'TR-03153-01', title_nl: 'Smart Meter Gateway Sicherheitsanforderungen', title: 'Smart Meter Gateway security requirements', description_nl: 'Smart Meter Gateways MUESSEN die Sicherheitsanforderungen der BSI TR-03109 erfuellen. Das Gateway MUSS als Common Criteria-zertifiziertes Geraet ausgeliefert werden.', description: 'Smart Meter Gateways MUST meet security requirements of BSI TR-03109. The gateway MUST be delivered as a Common Criteria-certified device.', category: 'Smart Metering', subcategory: 'TR-03153 Smart Meter', level: 'Verpflichtend', iso_mapping: 'A.8.9', implementation_guidance: 'CC-zertifiziertes Gateway einsetzen. BSI TR-03109 als Sicherheitsstandard. PP-0073 als Protection Profile.', verification_guidance: 'CC-Zertifizierung und TR-03109-Konformitaet pruefen.', source_url: 'https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/Technische-Richtlinien/TR-nach-Thema/tr03109/tr-03109_node.html' },
  { control_number: 'TR-03153-02', title_nl: 'Smart Meter Gateway PKI', title: 'Smart Meter Gateway PKI', description_nl: 'Die Kommunikation des Smart Meter Gateways MUSS ueber eine dedizierte PKI (SM-PKI) abgesichert werden. Zertifikate MUESSEN ueber die BSI-betriebene Root-CA ausgestellt werden.', description: 'Smart Meter Gateway communication MUST be secured via a dedicated PKI (SM-PKI). Certificates MUST be issued via the BSI-operated Root CA.', category: 'Smart Metering', subcategory: 'TR-03153 PKI', level: 'Verpflichtend', iso_mapping: 'A.8.24', implementation_guidance: 'SM-PKI Integration. Zertifikate ueber BSI Root-CA. Zertifikats-Lifecycle-Management.', verification_guidance: 'SM-PKI-Anbindung und Zertifikatskette pruefen.', source_url: null },
  { control_number: 'TR-03153-03', title_nl: 'Verschluesselung von Messdaten', title: 'Encryption of metering data', description_nl: 'Messdaten MUESSEN bei der Uebertragung vom Smart Meter Gateway zum Gateway-Administrator verschluesselt und integritaetsgeschuetzt werden.', description: 'Metering data MUST be encrypted and integrity-protected during transmission from the Smart Meter Gateway to the Gateway Administrator.', category: 'Smart Metering', subcategory: 'TR-03153 Datenverschluesselung', level: 'Verpflichtend', iso_mapping: 'A.8.24', implementation_guidance: 'TLS-basierte Kommunikation. Signierten Content-Datensaetze (CMS). AES-GCM.', verification_guidance: 'Messdaten-Verschluesselung und Integritaetsschutz pruefen.', source_url: null },
  { control_number: 'TR-03153-04', title_nl: 'Firmware-Updates fuer Smart Meter Gateways', title: 'Firmware updates for Smart Meter Gateways', description_nl: 'Firmware-Updates MUESSEN signiert sein und nur ueber den Gateway-Administrator eingespielt werden. Der Update-Prozess MUSS die Integritaet des Gateways gewaehrleisten.', description: 'Firmware updates MUST be signed and may only be installed via the Gateway Administrator. The update process MUST ensure the integrity of the gateway.', category: 'Smart Metering', subcategory: 'TR-03153 Firmware', level: 'Verpflichtend', iso_mapping: 'A.8.32', implementation_guidance: 'Code-Signierung fuer Firmware. Nur Gateway-Admin darf Updates einspielen. Integritaetspruefung.', verification_guidance: 'Firmware-Signierung und Update-Prozess pruefen.', source_url: null },

  // TR-03146 — eID-Server
  { control_number: 'TR-03146-01', title_nl: 'eID-Server Sicherheitsanforderungen', title: 'eID server security requirements', description_nl: 'Der eID-Server MUSS in einem gehaerteten Betriebsumfeld betrieben werden. Der Server MUSS durch Firewall, IDS und Zugriffskontrolle geschuetzt sein.', description: 'The eID server MUST be operated in a hardened environment. The server MUST be protected by firewall, IDS, and access control.', category: 'eID', subcategory: 'TR-03146 eID-Server', level: 'Verpflichtend', iso_mapping: 'A.8.9', implementation_guidance: 'eID-Server in DMZ mit Firewall. IDS/IPS. Zugriff nur fuer Administratoren.', verification_guidance: 'eID-Server Betriebsumgebung und Haertung pruefen.', source_url: null },
  { control_number: 'TR-03146-02', title_nl: 'PACE-Protokoll-Implementation', title: 'PACE protocol implementation', description_nl: 'Der eID-Server MUSS das PACE (Password Authenticated Connection Establishment) Protokoll korrekt implementieren, um den Datenschutz der Ausweisdaten zu gewaehrleisten.', description: 'The eID server MUST correctly implement the PACE (Password Authenticated Connection Establishment) protocol to ensure privacy of ID card data.', category: 'eID', subcategory: 'TR-03146 PACE', level: 'Verpflichtend', iso_mapping: 'A.8.24', implementation_guidance: 'PACE mit DH oder ECDH. Parameter gemaess BSI TR-03110. Konformitaetstest nach TR-03105.', verification_guidance: 'PACE-Implementation und Konformitaet pruefen.', source_url: null },

  // TR-03124 — eID-Client
  { control_number: 'TR-03124-01', title_nl: 'eID-Client Sicherheitsanforderungen', title: 'eID client security requirements', description_nl: 'Der eID-Client (AusweisApp oder alternative Implementierung) MUSS die Authentizitaet des eID-Servers pruefen. Der Client MUSS gegen Man-in-the-Middle-Angriffe geschuetzt sein.', description: 'The eID client (AusweisApp or alternative implementation) MUST verify the authenticity of the eID server. The client MUST be protected against man-in-the-middle attacks.', category: 'eID', subcategory: 'TR-03124 eID-Client', level: 'Verpflichtend', iso_mapping: 'A.8.5', implementation_guidance: 'Server-Authentisierung ueber TLS-Zertifikate. Terminalzertifikats-Pruefung. Certificate Pinning.', verification_guidance: 'eID-Client gegen TR-03124 testen lassen.', source_url: null },
  { control_number: 'TR-03124-02', title_nl: 'Sicherer Kanal zwischen eID-Client und Kartenleser', title: 'Secure channel between eID client and card reader', description_nl: 'Die Kommunikation zwischen eID-Client und Kartenleser MUSS ueber einen sicheren Kanal erfolgen, insbesondere bei kontaktlosen Lesegeraeten.', description: 'Communication between eID client and card reader MUST use a secure channel, especially for contactless readers.', category: 'eID', subcategory: 'TR-03124 Kartenleser', level: 'Verpflichtend', iso_mapping: 'A.8.24', implementation_guidance: 'PACE fuer kontaktlose NFC-Kommunikation. Sichere PIN-Eingabe (Klasse 2/3 Leser).', verification_guidance: 'Kommunikationskanal und PIN-Eingabe-Sicherheit pruefen.', source_url: null },

  // TR-03171 — FIDO2/WebAuthn
  { control_number: 'TR-03171-01', title_nl: 'FIDO2-Implementierungsanforderungen', title: 'FIDO2 implementation requirements', description_nl: 'Bei der Implementierung von FIDO2/WebAuthn MUESSEN die Anforderungen dieser TR eingehalten werden. FIDO2-Authenticatoren MUESSEN auf FIDO-Zertifizierung geprueft werden.', description: 'When implementing FIDO2/WebAuthn, the requirements of this TR MUST be met. FIDO2 authenticators MUST be checked for FIDO certification.', category: 'Authentisierung', subcategory: 'TR-03171 FIDO2', level: 'Empfehlung', iso_mapping: 'A.8.5', implementation_guidance: 'FIDO2-zertifizierte Authenticatoren. Attestation-Pruefung. Backup-Authenticator-Policy.', verification_guidance: 'FIDO2-Implementierung und Authenticator-Zertifizierung pruefen.', source_url: null },
  { control_number: 'TR-03171-02', title_nl: 'Registrierungs- und Authentisierungszeremonien', title: 'Registration and authentication ceremonies', description_nl: 'Die FIDO2-Registrierung MUSS mit einem initialen Identifizierungsnachweis verknuepft sein. Die Attestation des Authenticators SOLLTE geprueft werden, um nur zugelassene Geraetetypen zu akzeptieren.', description: 'FIDO2 registration MUST be linked to an initial identity verification. Authenticator attestation SHOULD be verified to accept only approved device types.', category: 'Authentisierung', subcategory: 'TR-03171 Zeremonie', level: 'Empfehlung', iso_mapping: 'A.8.5', implementation_guidance: 'Identitaetspruefung bei Erstregistrierung. Attestation-Validierung. Allowlist fuer Authenticator-Modelle.', verification_guidance: 'Registrierungsprozess und Attestation-Pruefung pruefen.', source_url: null },

  // TR-03185 — Cyber-Physical Systems
  { control_number: 'TR-03185-01', title_nl: 'Sicherheitsanforderungen an Cyber-Physical Systems', title: 'Security requirements for cyber-physical systems', description_nl: 'Cyber-Physical Systems (CPS) MUESSEN eine Bedrohungsanalyse durchlaufen, die sowohl IT-Sicherheit als auch physische Sicherheitsaspekte (Safety) beruecksichtigt.', description: 'Cyber-Physical Systems (CPS) MUST undergo a threat analysis considering both IT security and physical safety aspects.', category: 'Cyber-Physical Systems', subcategory: 'TR-03185 CPS', level: 'Empfehlung', iso_mapping: 'A.5.7', implementation_guidance: 'Kombinierte Safety/Security-Analyse (z.B. SAHARA, STPA-Sec). Risikomatrix mit Safety-Impact.', verification_guidance: 'Safety/Security-Bedrohungsanalyse und Risikobewertung pruefen.', source_url: null },
  { control_number: 'TR-03185-02', title_nl: 'Sichere Kommunikation zwischen CPS-Komponenten', title: 'Secure communication between CPS components', description_nl: 'Die Kommunikation zwischen CPS-Komponenten MUSS authentifiziert und integritaetsgeschuetzt sein. Echtzeitanforderungen MUESSEN bei der Wahl der Sicherheitsmechanismen beruecksichtigt werden.', description: 'Communication between CPS components MUST be authenticated and integrity-protected. Real-time requirements MUST be considered when choosing security mechanisms.', category: 'Cyber-Physical Systems', subcategory: 'TR-03185 Kommunikation', level: 'Empfehlung', iso_mapping: 'A.8.20', implementation_guidance: 'Leichtgewichtige Kryptographie fuer Echtzeitkommunikation. DTLS oder MACsec. Latenzmessung.', verification_guidance: 'CPS-Kommunikationssicherheit und Latenz-Auswirkung pruefen.', source_url: null },

  // TR-02102 — Post-Quantum Cryptography
  { control_number: 'TR-02102-PQ-01', title_nl: 'Vorbereitung auf Post-Quanten-Kryptographie', title: 'Preparation for post-quantum cryptography', description_nl: 'Organisationen SOLLTEN ihre kryptographischen Systeme auf Quanten-Sicherheit analysieren. Systeme mit langfristigem Schutzbedarf (>10 Jahre) SOLLTEN bereits hybride Verfahren einsetzen.', description: 'Organizations SHOULD analyze their cryptographic systems for quantum safety. Systems with long-term protection needs (>10 years) SHOULD already use hybrid methods.', category: 'Kryptographie', subcategory: 'Post-Quanten', level: 'Empfehlung', iso_mapping: 'A.8.24', implementation_guidance: 'Krypto-Inventar erstellen. PQC-Migrationsplan. Hybride Verfahren (klassisch + PQC) fuer langfristigen Schutz.', verification_guidance: 'PQC-Readiness-Assessment und Migrationsplan pruefen.', source_url: null },
  { control_number: 'TR-02102-PQ-02', title_nl: 'Empfohlene Post-Quanten-Algorithmen', title: 'Recommended post-quantum algorithms', description_nl: 'Als Post-Quanten-Algorithmen WERDEN ML-KEM (Kyber) fuer Schluesselaustausch und ML-DSA (Dilithium) fuer Signaturen empfohlen. XMSS kann fuer langfristige Signaturen eingesetzt werden.', description: 'As post-quantum algorithms, ML-KEM (Kyber) for key exchange and ML-DSA (Dilithium) for signatures ARE recommended. XMSS can be used for long-term signatures.', category: 'Kryptographie', subcategory: 'Post-Quanten', level: 'Empfehlung', iso_mapping: 'A.8.24', implementation_guidance: 'ML-KEM-768/1024 fuer Schluesselaustausch. ML-DSA-65/87 fuer Signaturen. Hybrid mit ECDH/ECDSA.', verification_guidance: 'PQC-Algorithmen-Auswahl und hybride Implementation pruefen.', source_url: null },

  // TR-03105 — Conformance Testing
  { control_number: 'TR-03105-01', title_nl: 'Konformitaetstests fuer eID-Systeme', title: 'Conformance testing for eID systems', description_nl: 'eID-Systeme (Clients und Server) MUESSEN die Konformitaetstests nach BSI TR-03105 bestehen. Die Tests decken PACE, Terminal Authentication und Chip Authentication ab.', description: 'eID systems (clients and servers) MUST pass conformance tests per BSI TR-03105. Tests cover PACE, Terminal Authentication, and Chip Authentication.', category: 'eID', subcategory: 'TR-03105 Konformitaet', level: 'Verpflichtend', iso_mapping: 'A.8.34', implementation_guidance: 'BSI TR-03105-Testumgebung aufsetzen. Alle Testfaelle bestehen vor Produktivstellung.', verification_guidance: 'TR-03105-Konformitaetstestergebnisse pruefen.', source_url: null },

  // TR-03108 — Sicherer E-Mail-Transport
  { control_number: 'TR-03108-01', title_nl: 'DANE und MTA-STS fuer E-Mail-Transport', title: 'DANE and MTA-STS for email transport', description_nl: 'E-Mail-Server SOLLTEN DANE (TLSA-Records) oder MTA-STS implementieren, um die TLS-Verschluesselung zwischen Mailservern zu erzwingen und Downgrade-Angriffe zu verhindern.', description: 'Email servers SHOULD implement DANE (TLSA records) or MTA-STS to enforce TLS encryption between mail servers and prevent downgrade attacks.', category: 'E-Mail-Sicherheit', subcategory: 'TR-03108 Sicherer Transport', level: 'Empfehlung', iso_mapping: 'A.8.24', implementation_guidance: 'DANE mit TLSA-Records in DNS. MTA-STS als Alternative. SMTP-TLS-Reporting (RFC 8460).', verification_guidance: 'DANE/MTA-STS-Konfiguration und TLS-Reporting pruefen.', source_url: null },
  { control_number: 'TR-03108-02', title_nl: 'DMARC-Implementation fuer Bundesbehoerden', title: 'DMARC implementation for federal agencies', description_nl: 'Bundesbehoerden MUESSEN DMARC mit einer Policy von mindestens "quarantine" implementieren. SPF und DKIM MUESSEN als Voraussetzung konfiguriert sein.', description: 'Federal agencies MUST implement DMARC with a policy of at least "quarantine". SPF and DKIM MUST be configured as prerequisites.', category: 'E-Mail-Sicherheit', subcategory: 'TR-03108 DMARC', level: 'Verpflichtend', iso_mapping: 'A.8.24', implementation_guidance: 'SPF: strenge Policy (-all). DKIM: 2048-Bit RSA. DMARC: p=quarantine (Ziel: p=reject).', verification_guidance: 'SPF/DKIM/DMARC-Records und Policy pruefen.', source_url: null },

  // TR-03166 — Biometrie
  { control_number: 'TR-03166-01', title_nl: 'Biometrische Verifikation in hoheitlichen Dokumenten', title: 'Biometric verification in sovereign documents', description_nl: 'Biometrische Daten in hoheitlichen Dokumenten (Reisepass, Personalausweis) MUESSEN nach dieser TR verarbeitet werden. Die Daten MUESSEN auf dem Chip verschluesselt gespeichert sein.', description: 'Biometric data in sovereign documents (passport, ID card) MUST be processed per this TR. Data MUST be stored encrypted on the chip.', category: 'Biometrie', subcategory: 'TR-03166 Biometrie', level: 'Verpflichtend', iso_mapping: 'A.5.34', implementation_guidance: 'Verschluesselte biometrische Speicherung. Extended Access Control (EAC) fuer Fingerabdruecke.', verification_guidance: 'Biometrie-Verarbeitung und EAC-Implementation pruefen.', source_url: null },

  // Additional TR-02102 — S/MIME
  { control_number: 'TR-02102-SMIME-01', title_nl: 'S/MIME-Verschluesselung und -Signatur', title: 'S/MIME encryption and signature', description_nl: 'Bei der Verwendung von S/MIME MUESSEN die kryptographischen Vorgaben des BSI eingehalten werden. RSA-3072+ oder ECDSA P-256+ fuer Signaturen, AES-256 fuer Inhaltsverschluesselung.', description: 'When using S/MIME, BSI cryptographic requirements MUST be met. RSA-3072+ or ECDSA P-256+ for signatures, AES-256 for content encryption.', category: 'Kryptographie', subcategory: 'TR-02102 S/MIME', level: 'Empfehlung', iso_mapping: 'A.8.24', implementation_guidance: 'S/MIME-Zertifikate mit RSA-3072 oder ECDSA P-256. AES-256-CBC fuer Verschluesselung. SHA-256+ fuer Signaturen.', verification_guidance: 'S/MIME-Konfiguration und Zertifikatsparameter pruefen.', source_url: null },

  // TR-03109 — Smart Meter Gateway Administration
  { control_number: 'TR-03109-ADMIN-01', title_nl: 'Smart Meter Gateway Administrator Sicherheit', title: 'Smart Meter Gateway Administrator security', description_nl: 'Der Gateway-Administrator MUSS ein ISMS nach ISO 27001 betreiben. Die Verbindung zum Smart Meter Gateway MUSS ueber die SM-PKI authentifiziert und verschluesselt sein.', description: 'The Gateway Administrator MUST operate an ISMS per ISO 27001. The connection to the Smart Meter Gateway MUST be authenticated and encrypted via SM-PKI.', category: 'Smart Metering', subcategory: 'TR-03109 GW-Admin', level: 'Verpflichtend', iso_mapping: 'A.5.1', implementation_guidance: 'ISO 27001-zertifiziertes ISMS fuer GW-Admin. SM-PKI-basierte Kommunikation. Audit-Trail.', verification_guidance: 'ISMS-Zertifizierung und SM-PKI-Anbindung des GW-Admin pruefen.', source_url: null },
  { control_number: 'TR-03109-ADMIN-02', title_nl: 'Tarifprofil- und Konfigurationsmanagement', title: 'Tariff profile and configuration management', description_nl: 'Aenderungen an Tarifprofilen und Gateway-Konfigurationen MUESSEN signiert und authentifiziert uebertragen werden. Der Gateway MUSS nur Befehle von autorisierten Akteuren akzeptieren.', description: 'Changes to tariff profiles and gateway configurations MUST be transmitted signed and authenticated. The gateway MUST accept commands only from authorized actors.', category: 'Smart Metering', subcategory: 'TR-03109 Konfiguration', level: 'Verpflichtend', iso_mapping: 'A.8.32', implementation_guidance: 'Signierte Konfigurationsaenderungen. Whitelist autorisierter Akteure. Audit-Log aller Aenderungen.', verification_guidance: 'Konfigurations-Signierung und Autorisierungspruefung pruefen.', source_url: null },

  // TR-03160 — Smart Home
  { control_number: 'TR-03160-01', title_nl: 'Sicherheitsanforderungen an Smart-Home-Geraete', title: 'Security requirements for smart home devices', description_nl: 'Smart-Home-Geraete MUESSEN sichere Standardkonfigurationen haben. Jedes Geraet MUSS ein individuelles Standardpasswort besitzen. Keine hartcodierten Zugangsdaten.', description: 'Smart home devices MUST have secure default configurations. Each device MUST have an individual default password. No hardcoded credentials.', category: 'IoT', subcategory: 'TR-03160 Smart Home', level: 'Empfehlung', iso_mapping: 'A.8.9', implementation_guidance: 'Individuelle Standardpasswoerter. Keine hardcodierten Credentials. Firmware-Update-Faehigkeit.', verification_guidance: 'Standardkonfiguration und Passwort-Individualitaet pruefen.', source_url: null },
  { control_number: 'TR-03160-02', title_nl: 'Verschluesselung und Datenschutz bei Smart-Home-Geraeten', title: 'Encryption and data protection for smart home devices', description_nl: 'Smart-Home-Geraete MUESSEN die Kommunikation verschluesseln (TLS 1.2+). Personenbezogene Daten (z.B. Nutzungsprofile) MUESSEN DSGVO-konform verarbeitet werden.', description: 'Smart home devices MUST encrypt communication (TLS 1.2+). Personal data (e.g., usage profiles) MUST be processed GDPR-compliantly.', category: 'IoT', subcategory: 'TR-03160 Verschluesselung', level: 'Empfehlung', iso_mapping: 'A.8.24', implementation_guidance: 'TLS 1.2+ fuer Cloud-Kommunikation. Lokale Verschluesselung. Datenschutz-Transparenz.', verification_guidance: 'Kommunikationsverschluesselung und DSGVO-Konformitaet pruefen.', source_url: null },
];

const output = {
  framework: {
    id: 'bsi-tr-extended-2',
    name: 'BSI Technical Guidelines (Extended 2: IoT, Smart Metering, eID, PQC)',
    name_nl: 'BSI Technische Richtlinien (Erweitert 2: IoT, Smart Metering, eID, PQC)',
    issuing_body: 'Bundesamt fuer Sicherheit in der Informationstechnik (BSI)',
    version: '2024',
    effective_date: '2024-01-01',
    scope: 'Further BSI Technical Guidelines covering Smart Metering (TR-03109/03153), eID server and client (TR-03146/03124), FIDO2 (TR-03171), cyber-physical systems (TR-03185), post-quantum cryptography, email security (TR-03108), biometrics (TR-03166), smart home (TR-03160), and conformance testing (TR-03105)',
    scope_sectors: ['energy', 'government', 'all'],
    structure_description: 'Covers smart metering gateway (PKI, encryption, firmware, administration), eID infrastructure (server, client, PACE), FIDO2 authentication, cyber-physical systems, post-quantum cryptography preparation, email security (DANE, DMARC), biometrics, smart home, and conformance testing.',
    source_url: 'https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/Technische-Richtlinien/technische-richtlinien_node.html',
    license: 'Public document',
    language: 'de+en',
  },
  controls,
  metadata: { ingested_at: new Date().toISOString(), total_controls: controls.length },
};

mkdirSync(DATA_DIR, { recursive: true });
writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
console.log(`BSI TR Extended 2: ${controls.length} controls written to ${OUTPUT_FILE}`);
