// scripts/ingest-c5-extended.ts
// Extended BSI C5 controls — deeper controls from all 17 domains plus
// additional controls from C5:2020 that were not in the base ingest.

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'bsi-c5-extended.json');

const controls = [
  // OIS — Extended Organisation der Informationssicherheit
  { control_number: 'OIS-05', title_nl: 'Informationsklassifizierung im Cloud-Dienst', title: 'Information classification in the cloud service', description_nl: 'Der Cloud-Anbieter MUSS ein Klassifizierungsschema fuer Informationen implementieren, das die Vertraulichkeit, Integritaet und Verfuegbarkeit der Cloud-Kundendaten beruecksichtigt.', description: 'The cloud provider MUST implement an information classification scheme considering the confidentiality, integrity, and availability of cloud customer data.', category: 'OIS', subcategory: 'Informationsklassifizierung', level: 'Basis', iso_mapping: 'A.5.12', implementation_guidance: 'Klassifizierungsschema fuer Cloud-Daten. Kundenspezifische Anforderungen beruecksichtigen.', verification_guidance: 'Informationsklassifizierung und Umsetzung pruefen.', source_url: null },
  { control_number: 'OIS-06', title_nl: 'Risikomanagement fuer Cloud-Dienste', title: 'Risk management for cloud services', description_nl: 'Der Cloud-Anbieter MUSS ein Risikomanagement betreiben, das Cloud-spezifische Risiken (Multi-Tenancy, Datenlokalisierung, Vendor Lock-in) systematisch identifiziert und bewertet.', description: 'The cloud provider MUST operate risk management that systematically identifies and assesses cloud-specific risks (multi-tenancy, data localization, vendor lock-in).', category: 'OIS', subcategory: 'Risikomanagement', level: 'Basis', iso_mapping: 'A.5.7', implementation_guidance: 'Cloud-spezifische Risikoanalyse. Multi-Tenancy-Risiken. Datenlokalisierung.', verification_guidance: 'Cloud-Risikomanagement und -bewertungen pruefen.', source_url: null },

  // AM — Extended Asset Management
  { control_number: 'AM-04', title_nl: 'Cloud-Asset-Inventar', title: 'Cloud asset inventory', description_nl: 'Der Cloud-Anbieter MUSS ein vollstaendiges Inventar aller Cloud-Assets fuehren, einschliesslich virtueller Ressourcen, Speicher, Netzwerkkomponenten und Container.', description: 'The cloud provider MUST maintain a complete inventory of all cloud assets including virtual resources, storage, network components, and containers.', category: 'AM', subcategory: 'Asset-Inventar', level: 'Basis', iso_mapping: 'A.5.9', implementation_guidance: 'Automatisiertes Cloud-Asset-Discovery. CMDB fuer Cloud-Ressourcen.', verification_guidance: 'Cloud-Asset-Inventar auf Vollstaendigkeit pruefen.', source_url: null },
  { control_number: 'AM-05', title_nl: 'Klassifizierung von Cloud-Assets', title: 'Classification of cloud assets', description_nl: 'Alle Cloud-Assets MUESSEN nach ihrem Schutzbedarf klassifiziert werden. Die Klassifizierung MUSS bei Aenderungen aktualisiert werden.', description: 'All cloud assets MUST be classified according to their protection needs. Classification MUST be updated when changes occur.', category: 'AM', subcategory: 'Asset-Klassifizierung', level: 'Basis', iso_mapping: 'A.5.12', implementation_guidance: 'Schutzbedarfsfeststellung pro Cloud-Asset. Automatische Tagging.', verification_guidance: 'Asset-Klassifizierung und Aktualitaet pruefen.', source_url: null },

  // PS — Extended Physical Security
  { control_number: 'PS-08', title_nl: 'Schutz der Cloud-Rechenzentren', title: 'Protection of cloud data centers', description_nl: 'Cloud-Rechenzentren MUESSEN gegen physische Bedrohungen (Einbruch, Brand, Wasser, Stromausfall) geschuetzt sein. Redundante Standorte SOLLTEN vorhanden sein.', description: 'Cloud data centers MUST be protected against physical threats (intrusion, fire, water, power outage). Redundant locations SHOULD exist.', category: 'PS', subcategory: 'Rechenzentrumssicherheit', level: 'Basis', iso_mapping: 'A.7.3', implementation_guidance: 'Physische Sicherheit der Cloud-RZ. Redundanz. Zertifizierung (z.B. EN 50600).', verification_guidance: 'Physische Sicherheit und Redundanz der Cloud-RZ pruefen.', source_url: null },

  // OPS — Extended Operations Security
  { control_number: 'OPS-06', title_nl: 'Automatisiertes Konfigurationsmanagement', title: 'Automated configuration management', description_nl: 'Cloud-Infrastruktur MUSS durch automatisiertes Konfigurationsmanagement (Infrastructure as Code) verwaltet werden. Konfigurationsabweichungen MUESSEN erkannt und korrigiert werden.', description: 'Cloud infrastructure MUST be managed through automated configuration management (Infrastructure as Code). Configuration drift MUST be detected and corrected.', category: 'OPS', subcategory: 'Konfigurationsmanagement', level: 'Basis', iso_mapping: 'A.8.9', implementation_guidance: 'IaC (Terraform, Ansible). Drift-Detection. Automatische Korrektur.', verification_guidance: 'IaC-Einsatz und Drift-Detection pruefen.', source_url: null },
  { control_number: 'OPS-07', title_nl: 'Monitoring der Cloud-Dienste', title: 'Monitoring of cloud services', description_nl: 'Alle Cloud-Dienste MUESSEN kontinuierlich ueberwacht werden. Performance, Verfuegbarkeit und Sicherheitsereignisse MUESSEN in Echtzeit erfasst werden.', description: 'All cloud services MUST be continuously monitored. Performance, availability, and security events MUST be captured in real time.', category: 'OPS', subcategory: 'Monitoring', level: 'Basis', iso_mapping: 'A.8.16', implementation_guidance: 'Cloud-Monitoring-Stack (Prometheus, Grafana). Alerting. SLA-Tracking.', verification_guidance: 'Cloud-Monitoring-Abdeckung und Alerting pruefen.', source_url: null },
  { control_number: 'OPS-08', title_nl: 'Kapazitaetsmanagement fuer Cloud-Dienste', title: 'Capacity management for cloud services', description_nl: 'Der Cloud-Anbieter MUSS sicherstellen, dass ausreichende Kapazitaeten fuer die vereinbarten SLAs vorhanden sind. Kapazitaetsengpaesse MUESSEN fruehzeitig erkannt werden.', description: 'The cloud provider MUST ensure sufficient capacity for agreed SLAs. Capacity bottlenecks MUST be detected early.', category: 'OPS', subcategory: 'Kapazitaetsmanagement', level: 'Basis', iso_mapping: 'A.8.6', implementation_guidance: 'Kapazitaets-Monitoring. Auto-Scaling. Vorausschauende Planung.', verification_guidance: 'Kapazitaetsmanagement und SLA-Einhaltung pruefen.', source_url: null },

  // IDM — Extended Identity and Access Management
  { control_number: 'IDM-05', title_nl: 'Multi-Faktor-Authentisierung fuer Cloud-Administration', title: 'Multi-factor authentication for cloud administration', description_nl: 'Fuer alle administrativen Zugaenge zur Cloud-Infrastruktur MUSS Multi-Faktor-Authentisierung eingesetzt werden. Dies gilt auch fuer API-Zugaenge mit erhoehten Rechten.', description: 'Multi-factor authentication MUST be used for all administrative access to cloud infrastructure. This also applies to API access with elevated privileges.', category: 'IDM', subcategory: 'Authentisierung', level: 'Basis', iso_mapping: 'A.8.5', implementation_guidance: 'MFA fuer alle Admin-Zugaenge. FIDO2/WebAuthn. MFA fuer privilegierte API-Calls.', verification_guidance: 'MFA-Konfiguration fuer Cloud-Administration pruefen.', source_url: null },
  { control_number: 'IDM-06', title_nl: 'Cloud-Mandantentrennung bei Zugriffskontrolle', title: 'Cloud tenant separation in access control', description_nl: 'Der Cloud-Anbieter MUSS sicherstellen, dass die Zugriffskontrolle eine strikte Mandantentrennung gewaehrleistet. Kein Mandant DARF auf Daten oder Ressourcen eines anderen Mandanten zugreifen koennen.', description: 'The cloud provider MUST ensure that access control guarantees strict tenant separation. No tenant MAY be able to access data or resources of another tenant.', category: 'IDM', subcategory: 'Mandantentrennung', level: 'Basis', iso_mapping: 'A.8.3', implementation_guidance: 'Strikte Tenant-Isolation. RBAC pro Mandant. Keine mandantenuebergreifenden Zugriffsmoeglichkeiten.', verification_guidance: 'Mandantentrennung und Isolationstests pruefen.', source_url: null },

  // CRY — Extended Cryptography
  { control_number: 'CRY-04', title_nl: 'Schluesselmanagement im Cloud-Dienst', title: 'Key management in the cloud service', description_nl: 'Der Cloud-Anbieter MUSS ein sicheres Schluesselmanagement implementieren. Kunden SOLLTEN die Moeglichkeit haben, eigene Schluessel (BYOK) oder kundenverwaltete Schluessel (CMEK) einzusetzen.', description: 'The cloud provider MUST implement secure key management. Customers SHOULD have the option to use their own keys (BYOK) or customer-managed keys (CMEK).', category: 'CRY', subcategory: 'Schluesselmanagement', level: 'Basis', iso_mapping: 'A.8.24', implementation_guidance: 'Cloud-KMS. BYOK/CMEK-Optionen. HSM-backed Keys fuer Kunden.', verification_guidance: 'Schluesselmanagement und BYOK/CMEK-Verfuegbarkeit pruefen.', source_url: null },
  { control_number: 'CRY-05', title_nl: 'Verschluesselung der Daten at Rest im Cloud-Speicher', title: 'Encryption of data at rest in cloud storage', description_nl: 'Alle Kundendaten im Cloud-Speicher MUESSEN verschluesselt gespeichert werden. Die Verschluesselung MUSS mindestens AES-256 einsetzen.', description: 'All customer data in cloud storage MUST be stored encrypted. Encryption MUST use at least AES-256.', category: 'CRY', subcategory: 'Datenverschluesselung', level: 'Basis', iso_mapping: 'A.8.24', implementation_guidance: 'AES-256 at Rest. Server-seitige Verschluesselung. Client-seitige Verschluesselung fuer sensitive Daten.', verification_guidance: 'Verschluesselungskonfiguration und Algorithmen pruefen.', source_url: null },

  // COS — Extended Cloud Service Operations
  { control_number: 'COS-06', title_nl: 'Multi-Region-Verfuegbarkeit', title: 'Multi-region availability', description_nl: 'Fuer hochverfuegbare Cloud-Dienste SOLLTE der Cloud-Anbieter Multi-Region-Deployment anbieten. Kunden MUESSEN ueber die Standorte der Datenverarbeitung informiert werden.', description: 'For highly available cloud services, the cloud provider SHOULD offer multi-region deployment. Customers MUST be informed about data processing locations.', category: 'COS', subcategory: 'Verfuegbarkeit', level: 'Standard', iso_mapping: 'A.8.14', implementation_guidance: 'Multi-Region-Architektur. Geo-Redundanz. Transparenz ueber Standorte.', verification_guidance: 'Multi-Region-Faehigkeit und Standort-Transparenz pruefen.', source_url: null },
  { control_number: 'COS-07', title_nl: 'Datenlokalisierung und Datensouveraenitaet', title: 'Data localization and data sovereignty', description_nl: 'Der Cloud-Anbieter MUSS dem Kunden ermoglichen, die Speicherorte der Daten festzulegen. Fuer EU/EWR-Daten MUSS eine Verarbeitung innerhalb des EU/EWR gewaehrleistet werden koennen.', description: 'The cloud provider MUST enable the customer to specify data storage locations. For EU/EEA data, processing within the EU/EEA MUST be ensurable.', category: 'COS', subcategory: 'Datensouveraenitaet', level: 'Basis', iso_mapping: 'A.5.34', implementation_guidance: 'Data-Residency-Optionen. EU-only-Verarbeitung. Transparenz ueber Subprozessoren.', verification_guidance: 'Datenlokalisierung und Subprozessor-Transparenz pruefen.', source_url: null },

  // DEV — Extended Secure Development
  { control_number: 'DEV-04', title_nl: 'Sicherer Entwicklungsprozess fuer Cloud-Dienste', title: 'Secure development process for cloud services', description_nl: 'Der Cloud-Anbieter MUSS einen sicheren Entwicklungsprozess (Secure SDLC) implementieren. Security-Reviews MUESSEN in jeder Phase des Entwicklungszyklus stattfinden.', description: 'The cloud provider MUST implement a secure development process (Secure SDLC). Security reviews MUST occur in every phase of the development cycle.', category: 'DEV', subcategory: 'Sichere Entwicklung', level: 'Basis', iso_mapping: 'A.8.25', implementation_guidance: 'Secure SDLC. Threat Modeling. Code-Reviews. Security-Testing in CI/CD.', verification_guidance: 'SDLC-Prozess und Security-Integration pruefen.', source_url: null },
  { control_number: 'DEV-05', title_nl: 'Schwachstellenmanagement fuer Cloud-Dienste', title: 'Vulnerability management for cloud services', description_nl: 'Der Cloud-Anbieter MUSS ein Schwachstellenmanagement betreiben, das regelmaessige Scans, Penetrationstests und zeitnahe Behebung von Schwachstellen umfasst.', description: 'The cloud provider MUST operate vulnerability management comprising regular scans, penetration tests, and timely remediation of vulnerabilities.', category: 'DEV', subcategory: 'Schwachstellenmanagement', level: 'Basis', iso_mapping: 'A.8.8', implementation_guidance: 'Regelmaessige Vulnerability-Scans. Jaehrliche Pentests. Patch-SLAs nach Kritikalitaet.', verification_guidance: 'Schwachstellenmanagement-Prozess und Patch-Zeiten pruefen.', source_url: null },

  // SIM — Extended Security Incident Management
  { control_number: 'SIM-04', title_nl: 'Benachrichtigung der Kunden bei Sicherheitsvorfaellen', title: 'Customer notification of security incidents', description_nl: 'Der Cloud-Anbieter MUSS betroffene Kunden unverzueglich ueber Sicherheitsvorfaelle informieren, die deren Daten oder Dienste betreffen koennen.', description: 'The cloud provider MUST promptly inform affected customers about security incidents that may affect their data or services.', category: 'SIM', subcategory: 'Kundenbenachrichtigung', level: 'Basis', iso_mapping: 'A.5.26', implementation_guidance: 'Kundenbenachrichtigungs-Prozess. Kommunikationsvorlagen. SLA fuer Benachrichtigung.', verification_guidance: 'Kundenbenachrichtigungs-Prozess und SLA pruefen.', source_url: null },

  // BCM — Extended Business Continuity
  { control_number: 'BCM-05', title_nl: 'Disaster Recovery fuer Cloud-Dienste', title: 'Disaster recovery for cloud services', description_nl: 'Der Cloud-Anbieter MUSS Disaster-Recovery-Faehigkeiten fuer seine Cloud-Dienste vorhalten. DR-Tests MUESSEN regelmaessig durchgefuehrt und dokumentiert werden.', description: 'The cloud provider MUST maintain disaster recovery capabilities for its cloud services. DR tests MUST be regularly performed and documented.', category: 'BCM', subcategory: 'Disaster Recovery', level: 'Basis', iso_mapping: 'A.5.30', implementation_guidance: 'DR-Plan fuer Cloud-Dienste. Regelmaessige DR-Tests. RTO/RPO pro Dienst.', verification_guidance: 'DR-Plan und Testergebnisse pruefen.', source_url: null },

  // COM — Extended Compliance
  { control_number: 'COM-04', title_nl: 'Transparenzberichte', title: 'Transparency reports', description_nl: 'Der Cloud-Anbieter SOLLTE regelmaessig Transparenzberichte veroeffentlichen, die Informationen ueber behoerdliche Datenanfragen, Sicherheitsvorfaelle und Service-Verfuegbarkeit enthalten.', description: 'The cloud provider SHOULD regularly publish transparency reports containing information about government data requests, security incidents, and service availability.', category: 'COM', subcategory: 'Transparenz', level: 'Standard', iso_mapping: 'A.5.31', implementation_guidance: 'Halbjaehrliche Transparenzberichte. Behoerdenanfragen-Statistik. Verfuegbarkeits-SLA.', verification_guidance: 'Transparenzberichte und deren Vollstaendigkeit pruefen.', source_url: null },

  // INQ — Extended Inquiry/Audit
  { control_number: 'INQ-04', title_nl: 'Recht auf Audit durch Cloud-Kunden', title: 'Right to audit by cloud customers', description_nl: 'Der Cloud-Anbieter MUSS Cloud-Kunden das Recht einraeumen, die Einhaltung der C5-Anforderungen durch Audits oder Einsicht in Auditberichte zu ueberpruefen.', description: 'The cloud provider MUST grant cloud customers the right to verify compliance with C5 requirements through audits or access to audit reports.', category: 'INQ', subcategory: 'Audit-Rechte', level: 'Basis', iso_mapping: 'A.5.35', implementation_guidance: 'Audit-Klausel in Vertraegen. SOC-2-Berichte oder C5-Testate bereitstellen.', verification_guidance: 'Audit-Rechte und Verfuegbarkeit von Audit-Berichten pruefen.', source_url: null },

  // PSS — Extended Portability and Service Specification
  { control_number: 'PSS-04', title_nl: 'Datenportabilitaet und Export-Moeglichkeiten', title: 'Data portability and export options', description_nl: 'Der Cloud-Anbieter MUSS seinen Kunden die Moeglichkeit bieten, ihre Daten in einem gaengigen Format zu exportieren. Lock-in-Effekte MUESSEN minimiert werden.', description: 'The cloud provider MUST offer its customers the ability to export their data in a common format. Lock-in effects MUST be minimized.', category: 'PSS', subcategory: 'Datenportabilitaet', level: 'Basis', iso_mapping: 'A.5.23', implementation_guidance: 'Datenexport in Standard-Formaten (JSON, CSV, SQL). API fuer Bulk-Export. Exit-Strategie.', verification_guidance: 'Datenexport-Moeglichkeiten und Format-Standards pruefen.', source_url: null },

  // SP — Extended Security Policy
  { control_number: 'SP-05', title_nl: 'Cloud-Sicherheitsrichtlinie fuer Kunden', title: 'Cloud security policy for customers', description_nl: 'Der Cloud-Anbieter MUSS eine Cloud-Sicherheitsrichtlinie bereitstellen, die Kunden ueber das Shared-Responsibility-Modell, ihre Pflichten und die Sicherheitskonfigurationsoptionen informiert.', description: 'The cloud provider MUST provide a cloud security policy informing customers about the shared responsibility model, their obligations, and security configuration options.', category: 'SP', subcategory: 'Sicherheitsrichtlinie', level: 'Basis', iso_mapping: 'A.5.1', implementation_guidance: 'Shared-Responsibility-Dokumentation. Sicherheitskonfigurationsanleitungen. Best-Practice-Guides.', verification_guidance: 'Shared-Responsibility-Dokumentation und Kunden-Guidance pruefen.', source_url: null },

  // HR — Extended Human Resources
  { control_number: 'HR-05', title_nl: 'Sicherheitsueberpruefung von Cloud-Personal', title: 'Security screening of cloud personnel', description_nl: 'Personal des Cloud-Anbieters mit Zugang zu Kundendaten oder kritischer Infrastruktur MUSS einer angemessenen Sicherheitsueberpruefung unterzogen werden.', description: 'Cloud provider personnel with access to customer data or critical infrastructure MUST undergo appropriate security screening.', category: 'HR', subcategory: 'Personalueberpruefung', level: 'Basis', iso_mapping: 'A.6.1', implementation_guidance: 'Background-Checks fuer privilegiertes Personal. Regelmaessige Wiederholung.', verification_guidance: 'Sicherheitsueberpruefungen des Cloud-Personals pruefen.', source_url: null },
];

const output = {
  framework: {
    id: 'bsi-c5-extended',
    name: 'C5 Cloud Computing Compliance Criteria Catalogue (Extended)',
    name_nl: 'Cloud Computing Compliance Criteria Katalog (C5) (Erweitert)',
    issuing_body: 'Bundesamt fuer Sicherheit in der Informationstechnik (BSI)',
    version: 'C5:2020 (Extended)',
    effective_date: '2020-01-01',
    scope: 'Extended C5 controls covering cloud-specific security requirements: multi-tenancy, data sovereignty, key management, IaC, customer notification, DR, transparency, portability, and shared responsibility',
    scope_sectors: ['cloud', 'digital_infrastructure', 'all'],
    structure_description: 'Extends the base C5 catalogue with deeper controls across all 17 domains including cloud-specific asset management, key management, data sovereignty, IaC operations, customer notification, DR testing, transparency reporting, and data portability.',
    source_url: 'https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Informationen-und-Empfehlungen/Empfehlungen-nach-Angriffszielen/Cloud-Computing/Kriterienkatalog-C5/kriterienkatalog-c5_node.html',
    license: 'Public document',
    language: 'de+en',
  },
  controls,
  metadata: { ingested_at: new Date().toISOString(), total_controls: controls.length },
};

mkdirSync(DATA_DIR, { recursive: true });
writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
console.log(`BSI C5 Extended: ${controls.length} controls written to ${OUTPUT_FILE}`);
