// scripts/ingest-bsi-tr-extended.ts
// Extends BSI Technische Richtlinien with additional TRs not in base ingest-bsi-tr.ts.
// Base covers: TR-02102-1 (partial), TR-02102-2 (partial), TR-03116-3 (partial), TR-03107-1, TR-03138, TR-03148.
// This adds: TR-02102-3/4, TR-03116-1/2/4, TR-03161, TR-03183, TR-03184, TR-03125 (Beweiswerterhaltung).

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'bsi-tr-extended.json');

const controls = [
  // TR-02102-3 — IPsec und IKE
  { control_number: 'TR-02102-3.1', title_nl: 'IPsec-Protokollversionen', title: 'IPsec protocol versions', description_nl: 'Es MUSS IKEv2 eingesetzt werden. IKEv1 SOLLTE nur noch in begruendeten Ausnahmefaellen verwendet werden. ESP MUSS fuer die Verschluesselung eingesetzt werden; AH allein ist nicht ausreichend.', description: 'IKEv2 MUST be used. IKEv1 SHOULD only be used in justified exceptional cases. ESP MUST be used for encryption; AH alone is not sufficient.', category: 'Kryptographie', subcategory: 'TR-02102 IPsec/IKE', level: 'Empfehlung', iso_mapping: 'A.8.24', implementation_guidance: 'IKEv2 mit ESP. AES-256-GCM oder AES-256-CBC mit SHA-256+ als Integritaetsschutz.', verification_guidance: 'IPsec/IKE-Konfiguration gegen BSI TR-02102-3 pruefen.', source_url: 'https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR02102/BSI-TR-02102-3.html' },
  { control_number: 'TR-02102-3.2', title_nl: 'Empfohlene IPsec-Algorithmen', title: 'Recommended IPsec algorithms', description_nl: 'Fuer ESP SOLLTEN AES-GCM (128/256) oder AES-CBC mit HMAC-SHA-256/384/512 eingesetzt werden. 3DES und DES DUERFEN NICHT verwendet werden.', description: 'For ESP, AES-GCM (128/256) or AES-CBC with HMAC-SHA-256/384/512 SHOULD be used. 3DES and DES MUST NOT be used.', category: 'Kryptographie', subcategory: 'TR-02102 IPsec/IKE', level: 'Empfehlung', iso_mapping: 'A.8.24', implementation_guidance: 'AES-256-GCM bevorzugt. DES/3DES aus allen IPsec-Policies entfernen.', verification_guidance: 'ESP-Algorithmen in VPN-Konfigurationen pruefen.', source_url: null },

  // TR-02102-4 — SSH
  { control_number: 'TR-02102-4.1', title_nl: 'SSH-Versionen und Konfiguration', title: 'SSH versions and configuration', description_nl: 'Es MUSS ausschliesslich SSH-2 eingesetzt werden. SSH-1 DARF NICHT verwendet werden. Passwort-Authentisierung SOLLTE deaktiviert und durch schluesselbasierte Authentisierung ersetzt werden.', description: 'Only SSH-2 MUST be used. SSH-1 MUST NOT be used. Password authentication SHOULD be disabled and replaced by key-based authentication.', category: 'Kryptographie', subcategory: 'TR-02102 SSH', level: 'Empfehlung', iso_mapping: 'A.8.24', implementation_guidance: 'SSH-2 only. Public-Key-Authentisierung. Ed25519 oder RSA-3072+ Schluessel.', verification_guidance: 'SSH-Konfiguration aller Server gegen BSI TR-02102-4 pruefen.', source_url: 'https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR02102/BSI-TR-02102-4.html' },
  { control_number: 'TR-02102-4.2', title_nl: 'SSH-Schluesselmanagement', title: 'SSH key management', description_nl: 'SSH-Schluessel MUESSEN regelmaessig rotiert werden. Nicht mehr benoetigte Schluessel MUESSEN aus den authorized_keys-Dateien entfernt werden.', description: 'SSH keys MUST be regularly rotated. Keys no longer needed MUST be removed from authorized_keys files.', category: 'Kryptographie', subcategory: 'TR-02102 SSH', level: 'Empfehlung', iso_mapping: 'A.8.24', implementation_guidance: 'SSH-Key-Inventar fuehren. Jaehrliche Rotation. Automatisierte Bereinigung verwaister Schluessel.', verification_guidance: 'SSH-Key-Inventar und Rotationsnachweis pruefen.', source_url: null },

  // TR-03116-1 — eCard-Projekte der Bundesregierung
  { control_number: 'TR-03116-1.1', title_nl: 'Kryptographische Vorgaben fuer eCard-Projekte', title: 'Cryptographic requirements for eCard projects', description_nl: 'Fuer eCard-Projekte der Bundesregierung MUESSEN die kryptographischen Vorgaben dieser TR eingehalten werden. Dies betrifft Schluessellaengen, Algorithmen und Zertifikatsprofile.', description: 'Cryptographic requirements of this TR MUST be followed for eCard projects of the federal government. This applies to key lengths, algorithms, and certificate profiles.', category: 'Kryptographie', subcategory: 'TR-03116 eCard', level: 'Verpflichtend', iso_mapping: 'A.8.24', implementation_guidance: 'BSI-zugelassene Algorithmen und Schluessellaengen fuer eCard-Projekte verwenden.', verification_guidance: 'eCard-Implementierung gegen TR-03116-1 zertifizieren lassen.', source_url: null },

  // TR-03116-4 — Kommunikationsverfahren in Anwendungen
  { control_number: 'TR-03116-4.1', title_nl: 'Kryptographische Vorgaben fuer Kommunikationsverfahren', title: 'Cryptographic requirements for communication procedures', description_nl: 'Fuer Kommunikationsverfahren in Bundesanwendungen MUESSEN die kryptographischen Mindestanforderungen dieser TR eingehalten werden. Dies umfasst TLS, S/MIME und XML-Verschluesselung.', description: 'For communication procedures in federal applications, the minimum cryptographic requirements of this TR MUST be met. This covers TLS, S/MIME, and XML encryption.', category: 'Kryptographie', subcategory: 'TR-03116 Kommunikation', level: 'Verpflichtend', iso_mapping: 'A.8.24', implementation_guidance: 'TLS nach TR-02102-2. S/MIME-Zertifikate gemaess TR-03116. XML-Signatur/Verschluesselung gemaess TR.', verification_guidance: 'Kommunikationsverfahren gegen TR-03116-4 pruefen.', source_url: null },

  // TR-03161 — Anforderungen an Anwendungen im Gesundheitswesen (Mobile Application Security)
  { control_number: 'TR-03161-1.1', title_nl: 'Sicherheitsanforderungen an mobile Anwendungen', title: 'Security requirements for mobile applications', description_nl: 'Mobile Anwendungen MUESSEN die Sicherheitsanforderungen dieser TR erfuellen. Dies umfasst sichere Datenspeicherung, sichere Kommunikation und Schutz vor Reverse Engineering.', description: 'Mobile applications MUST meet the security requirements of this TR. This includes secure data storage, secure communication, and protection against reverse engineering.', category: 'Anwendungssicherheit', subcategory: 'TR-03161 Mobile App Security', level: 'Empfehlung', iso_mapping: 'A.8.26', implementation_guidance: 'OWASP MASVS Level 2 als Basis. Sichere lokale Speicherung. Certificate Pinning. Root/Jailbreak-Erkennung.', verification_guidance: 'Mobile App gegen TR-03161 und OWASP MASVS pruefen.', source_url: 'https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/Technische-Richtlinien/TR-nach-Thema/tr03161/tr-03161_node.html' },
  { control_number: 'TR-03161-1.2', title_nl: 'Sichere Datenspeicherung auf mobilen Geraeten', title: 'Secure data storage on mobile devices', description_nl: 'Sensible Daten MUESSEN verschluesselt auf dem mobilen Geraet gespeichert werden. Schluessel MUESSEN in der sicheren Enklave (Keystore/Keychain) des Geraets gespeichert werden.', description: 'Sensitive data MUST be stored encrypted on the mobile device. Keys MUST be stored in the device secure enclave (Keystore/Keychain).', category: 'Anwendungssicherheit', subcategory: 'TR-03161 Mobile App Security', level: 'Empfehlung', iso_mapping: 'A.8.24', implementation_guidance: 'Android Keystore / iOS Keychain fuer Schluessel. SQLCipher oder aehnliches fuer lokale Datenbanken.', verification_guidance: 'Datenspeicherung und Schluesselverwahrung der App pruefen.', source_url: null },

  // TR-03183 — Cyber-Resilienz-Anforderungen
  { control_number: 'TR-03183-1.1', title_nl: 'Software Bill of Materials (SBOM)', title: 'Software bill of materials (SBOM)', description_nl: 'Hersteller MUESSEN eine Software-Stueckliste (SBOM) fuer ihre Produkte bereitstellen. Die SBOM MUSS alle eingesetzten Softwarekomponenten und deren Versionen auflisten.', description: 'Manufacturers MUST provide a software bill of materials (SBOM) for their products. The SBOM MUST list all software components used and their versions.', category: 'Cyber-Resilienz', subcategory: 'TR-03183 Cyber-Resilienz', level: 'Empfehlung', iso_mapping: 'A.8.28', implementation_guidance: 'SBOM im CycloneDX- oder SPDX-Format generieren. Automatisierte SBOM-Erstellung in CI/CD.', verification_guidance: 'SBOM-Verfuegbarkeit und Vollstaendigkeit pruefen.', source_url: 'https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/Technische-Richtlinien/TR-nach-Thema/tr03183/tr-03183_node.html' },
  { control_number: 'TR-03183-1.2', title_nl: 'Schwachstellenmanagement fuer Softwareprodukte', title: 'Vulnerability management for software products', description_nl: 'Hersteller MUESSEN einen Prozess fuer den Umgang mit Schwachstellen in ihren Produkten etablieren. Sicherheitsupdates MUESSEN zeitnah bereitgestellt werden.', description: 'Manufacturers MUST establish a process for handling vulnerabilities in their products. Security updates MUST be provided promptly.', category: 'Cyber-Resilienz', subcategory: 'TR-03183 Cyber-Resilienz', level: 'Empfehlung', iso_mapping: 'A.8.8', implementation_guidance: 'Coordinated Vulnerability Disclosure (CVD) Prozess. Security Advisories bei Schwachstellen.', verification_guidance: 'VDP/CVD-Prozess und Update-Bereitstellung pruefen.', source_url: null },
  { control_number: 'TR-03183-1.3', title_nl: 'Sichere Standardkonfiguration', title: 'Secure default configuration', description_nl: 'Produkte MUESSEN in einer sicheren Standardkonfiguration ausgeliefert werden. Nicht benoetigte Dienste und Funktionen MUESSEN standardmaessig deaktiviert sein.', description: 'Products MUST be delivered in a secure default configuration. Unnecessary services and functions MUST be disabled by default.', category: 'Cyber-Resilienz', subcategory: 'TR-03183 Cyber-Resilienz', level: 'Empfehlung', iso_mapping: 'A.8.9', implementation_guidance: 'Secure-by-Default-Konfiguration. Keine Standardpasswoerter. Haertungsdokumentation bereitstellen.', verification_guidance: 'Standardkonfiguration gegen Secure-by-Default-Prinzipien pruefen.', source_url: null },

  // TR-03125 — Beweiswerterhaltung (Preservation of Evidence)
  { control_number: 'TR-03125-1.1', title_nl: 'Beweiswerterhaltung kryptographisch signierter Dokumente', title: 'Preservation of evidence for cryptographically signed documents', description_nl: 'Kryptographisch signierte Dokumente MUESSEN so aufbewahrt werden, dass ihr Beweiswert erhalten bleibt. Dies erfordert regelmaessige Uebersignierung mit aktuellen Algorithmen.', description: 'Cryptographically signed documents MUST be stored so that their evidentiary value is preserved. This requires regular re-signing with current algorithms.', category: 'Dokumentensicherheit', subcategory: 'TR-03125 Beweiswerterhaltung', level: 'Verpflichtend', iso_mapping: null, implementation_guidance: 'Beweiswerterhaltungssystem gemaess TR-ESOR einrichten. Regelmaessige Uebersignierung planen.', verification_guidance: 'Beweiswerterhaltungsprozess und Uebersignierungsnachweise pruefen.', source_url: null },

  // TR-03184 — Online-Wahlsysteme
  { control_number: 'TR-03184-1.1', title_nl: 'Sicherheitsanforderungen an Online-Wahlsysteme', title: 'Security requirements for online voting systems', description_nl: 'Online-Wahlsysteme MUESSEN das Wahlgeheimnis technisch sicherstellen. Ende-zu-Ende-Verifizierbarkeit MUSS implementiert werden.', description: 'Online voting systems MUST technically ensure voting secrecy. End-to-end verifiability MUST be implemented.', category: 'Wahlsysteme', subcategory: 'TR-03184 Online-Wahlen', level: 'Verpflichtend', iso_mapping: null, implementation_guidance: 'Homomorphe Verschluesselung oder Mix-Nets fuer Wahlgeheimnis. Individual- und Universal-Verifizierbarkeit.', verification_guidance: 'Wahlsystem gegen TR-03184 auditieren lassen.', source_url: null },
];

const output = {
  framework: {
    id: 'bsi-tr-extended',
    name: 'BSI Technical Guidelines (Extended)',
    name_nl: 'BSI Technische Richtlinien (Erweitert)',
    issuing_body: 'Bundesamt fuer Sicherheit in der Informationstechnik (BSI)',
    version: '2024',
    effective_date: '2024-01-01',
    scope: 'Extended technical guidelines: TR-02102-3/4 (IPsec, SSH), TR-03116-1/4, TR-03161 (Mobile Security), TR-03183 (Cyber-Resilience/SBOM), TR-03184 (Online Voting), TR-03125 (Evidence Preservation)',
    scope_sectors: ['government', 'all'],
    structure_description: 'Additional BSI Technical Guidelines covering IPsec, SSH, mobile application security, cyber resilience requirements (CRA preparation), online voting, and evidence preservation.',
    source_url: 'https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/Technische-Richtlinien/technische-richtlinien_node.html',
    license: 'Public document',
    language: 'de+en',
  },
  controls,
  metadata: { ingested_at: new Date().toISOString(), total_controls: controls.length },
};

mkdirSync(DATA_DIR, { recursive: true });
writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
console.log(`BSI TR Extended: ${controls.length} controls written to ${OUTPUT_FILE}`);
