// scripts/ingest-mindeststandards-extended.ts
// Extended BSI Mindeststandards — additional domains: DNS security,
// cloud computing, video conferencing, network segmentation,
// endpoint detection, secure software development, and identity management.

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'bsi-mindeststandards-extended.json');

const controls = [
  // MS-DNS — Domain Name System
  { control_number: 'MS-DNS-01', title_nl: 'DNSSEC-Implementation', title: 'DNSSEC implementation', description_nl: 'Bundesbehoerden MUESSEN DNSSEC fuer ihre autoritativen DNS-Zonen implementieren. Resolving-Nameserver MUESSEN DNSSEC-Validierung durchfuehren.', description: 'Federal agencies MUST implement DNSSEC for their authoritative DNS zones. Resolving nameservers MUST perform DNSSEC validation.', category: 'DNS-Sicherheit', subcategory: 'DNSSEC', level: 'Verpflichtend', iso_mapping: 'A.8.20', implementation_guidance: 'DNSSEC-Signierung autoritativer Zonen. Validierende Resolver. Key-Rollover-Planung.', verification_guidance: 'DNSSEC-Signierung und Validierung pruefen (z.B. dnsviz.net).', source_url: null },
  { control_number: 'MS-DNS-02', title_nl: 'DNS-over-TLS/HTTPS', title: 'DNS over TLS/HTTPS', description_nl: 'Fuer die DNS-Kommunikation SOLLTE DNS-over-TLS (DoT) oder DNS-over-HTTPS (DoH) eingesetzt werden, um die Vertraulichkeit von DNS-Anfragen zu schuetzen.', description: 'For DNS communication, DNS-over-TLS (DoT) or DNS-over-HTTPS (DoH) SHOULD be used to protect the confidentiality of DNS queries.', category: 'DNS-Sicherheit', subcategory: 'Verschluesselte DNS', level: 'Empfehlung', iso_mapping: 'A.8.20', implementation_guidance: 'DoT (Port 853) oder DoH auf Resolvern. Interne DNS-Infrastruktur verschluesselt.', verification_guidance: 'Verschluesselte DNS-Konfiguration und Traffic-Analyse pruefen.', source_url: null },
  { control_number: 'MS-DNS-03', title_nl: 'DNS-Infrastruktur-Haertung', title: 'DNS infrastructure hardening', description_nl: 'DNS-Server MUESSEN gehaertet betrieben werden. Rekursion DARF NICHT auf autoritativen Servern aktiviert sein. Zone-Transfers MUESSEN auf autorisierte Sekundaerserver beschraenkt sein.', description: 'DNS servers MUST be operated in a hardened manner. Recursion MUST NOT be enabled on authoritative servers. Zone transfers MUST be restricted to authorized secondary servers.', category: 'DNS-Sicherheit', subcategory: 'DNS-Haertung', level: 'Verpflichtend', iso_mapping: 'A.8.9', implementation_guidance: 'Keine offene Rekursion. TSIG fuer Zone-Transfers. Minimale Antworten. Rate-Limiting.', verification_guidance: 'DNS-Server-Konfiguration und Haertung pruefen.', source_url: null },

  // MS-Cloud — Cloud Computing
  { control_number: 'MS-CLOUD-01', title_nl: 'Cloud-Sicherheitsbewertung', title: 'Cloud security assessment', description_nl: 'Vor der Nutzung von Cloud-Diensten MUESSEN Bundesbehoerden eine Sicherheitsbewertung des Cloud-Anbieters durchfuehren. C5-Testierung SOLLTE als Grundlage dienen.', description: 'Before using cloud services, federal agencies MUST perform a security assessment of the cloud provider. C5 attestation SHOULD serve as the basis.', category: 'Cloud Computing', subcategory: 'Cloud-Bewertung', level: 'Verpflichtend', iso_mapping: 'A.5.23', implementation_guidance: 'C5-Testierung als Mindestanforderung. Risikoanalyse pro Cloud-Dienst. Vertragliche Sicherheitsanforderungen.', verification_guidance: 'C5-Testierung und Sicherheitsbewertung des Cloud-Anbieters pruefen.', source_url: null },
  { control_number: 'MS-CLOUD-02', title_nl: 'Datenlokalisierung bei Cloud-Nutzung', title: 'Data localization for cloud use', description_nl: 'Daten mit Schutzbedarf MUESSEN in Rechenzentren innerhalb der EU/des EWR verarbeitet werden. Fuer VS-NfD-Daten MUESSEN Rechenzentren in Deutschland genutzt werden.', description: 'Data requiring protection MUST be processed in data centers within the EU/EEA. For VS-NfD data, data centers in Germany MUST be used.', category: 'Cloud Computing', subcategory: 'Datenlokalisierung', level: 'Verpflichtend', iso_mapping: 'A.5.23', implementation_guidance: 'EU/EWR-Rechenzentren fuer schutzbeduerftige Daten. Deutsche RZ fuer VS-NfD. Vertragliche Zusicherung.', verification_guidance: 'Datenlokalisierung und vertragliche Zusicherungen pruefen.', source_url: null },
  { control_number: 'MS-CLOUD-03', title_nl: 'Verschluesselung in der Cloud', title: 'Encryption in the cloud', description_nl: 'In der Cloud gespeicherte Daten MUESSEN verschluesselt sein. Fuer hochsensible Daten MUSS die Schluesselhoheit bei der Behoerde liegen (Bring Your Own Key).', description: 'Data stored in the cloud MUST be encrypted. For highly sensitive data, key sovereignty MUST remain with the agency (Bring Your Own Key).', category: 'Cloud Computing', subcategory: 'Cloud-Verschluesselung', level: 'Verpflichtend', iso_mapping: 'A.8.24', implementation_guidance: 'Encryption at Rest und in Transit. BYOK oder HYOK fuer sensible Daten. HSM-gestuetzte Schluessel.', verification_guidance: 'Cloud-Verschluesselung und Schluesselhoheit pruefen.', source_url: null },
  { control_number: 'MS-CLOUD-04', title_nl: 'Cloud-Exit-Strategie', title: 'Cloud exit strategy', description_nl: 'Bundesbehoerden MUESSEN vor Cloud-Nutzung eine Exit-Strategie definieren. Datenportabilitaet und Loeschnachweis nach Vertragsende MUESSEN vertraglich vereinbart werden.', description: 'Federal agencies MUST define an exit strategy before cloud use. Data portability and deletion confirmation after contract end MUST be contractually agreed.', category: 'Cloud Computing', subcategory: 'Exit-Strategie', level: 'Verpflichtend', iso_mapping: 'A.5.23', implementation_guidance: 'Cloud-Exit-Plan mit Datenexport und Loeschfrist. Portabilitaets-Test. Loeschnachweis-Klausel.', verification_guidance: 'Exit-Strategie und vertragliche Vereinbarungen pruefen.', source_url: null },

  // MS-Videokonferenz — Video Conferencing
  { control_number: 'MS-VK-01', title_nl: 'Sichere Videokonferenzsysteme', title: 'Secure video conferencing systems', description_nl: 'Videokonferenzsysteme MUESSEN Ende-zu-Ende oder mindestens Transport-verschluesselt sein. Fuer VS-NfD-Besprechungen MUESSEN BSI-zugelassene Systeme eingesetzt werden.', description: 'Video conferencing systems MUST use end-to-end or at minimum transport encryption. For VS-NfD meetings, BSI-approved systems MUST be used.', category: 'Videokonferenz', subcategory: 'Verschluesselung', level: 'Verpflichtend', iso_mapping: 'A.8.24', implementation_guidance: 'E2E-verschluesselte VK-Loesung. BSI-zugelassene Systeme fuer VS-NfD. Signalisierungsverschluesselung.', verification_guidance: 'VK-Verschluesselung und BSI-Zulassung pruefen.', source_url: null },
  { control_number: 'MS-VK-02', title_nl: 'Zugangskontrolle fuer Videokonferenzen', title: 'Access control for video conferences', description_nl: 'Videokonferenzen MUESSEN durch Zugangscodes oder Warteraeume geschuetzt werden. Nicht eingeladene Teilnehmer DUERFEN NICHT automatisch beitreten koennen.', description: 'Video conferences MUST be protected by access codes or waiting rooms. Uninvited participants MUST NOT be able to join automatically.', category: 'Videokonferenz', subcategory: 'Zugangskontrolle', level: 'Verpflichtend', iso_mapping: 'A.8.5', implementation_guidance: 'Warteraum-Funktion. Meeting-Passwort. Teilnehmer-Verifizierung. Lobby-Management.', verification_guidance: 'Zugangsschutz-Konfiguration der VK-Systeme pruefen.', source_url: null },
  { control_number: 'MS-VK-03', title_nl: 'Datenlokalisierung bei Video-Plattformen', title: 'Data localization for video platforms', description_nl: 'Videokonferenz-Plattformen MUESSEN die Verarbeitung der Mediendaten innerhalb der EU/des EWR sicherstellen. Aufzeichnungen MUESSEN in der Behoerde und nicht beim Anbieter gespeichert werden.', description: 'Video conferencing platforms MUST ensure processing of media data within the EU/EEA. Recordings MUST be stored at the agency, not at the provider.', category: 'Videokonferenz', subcategory: 'Datenlokalisierung', level: 'Verpflichtend', iso_mapping: 'A.5.23', implementation_guidance: 'EU/EWR-Medienrouting. Aufzeichnungen nur auf behoerdeneignen Systemen. Keine Cloud-Transkription.', verification_guidance: 'Medien-Routing und Aufzeichnungs-Speicherort pruefen.', source_url: null },

  // MS-Netzwerk — Network Security
  { control_number: 'MS-NETZ-01', title_nl: 'Netzwerksegmentierung in Bundesbehoerden', title: 'Network segmentation in federal agencies', description_nl: 'Behoerdennetze MUESSEN segmentiert werden. Mindestens die Trennung in Servernetz, Clientnetz, DMZ und Managementnetz MUSS umgesetzt werden.', description: 'Agency networks MUST be segmented. At minimum, separation into server network, client network, DMZ, and management network MUST be implemented.', category: 'Netzwerksicherheit', subcategory: 'Segmentierung', level: 'Verpflichtend', iso_mapping: 'A.8.22', implementation_guidance: 'Mindestens 4 Zonen: Server, Client, DMZ, Management. Next-Gen-Firewall zwischen Zonen.', verification_guidance: 'Netzwerksegmentierung und Firewall-Regelwerk pruefen.', source_url: null },
  { control_number: 'MS-NETZ-02', title_nl: 'Schutz des Regierungsnetzverbunds (NdB)', title: 'Protection of government network interconnect (NdB)', description_nl: 'Die Anbindung an den Netzverbund der Bundesverwaltung (NdB) MUSS durch BSI-konforme Sicherheitsgateways geschuetzt werden. Nur autorisierte Kommunikation DARF passieren.', description: 'The connection to the federal administration network interconnect (NdB) MUST be protected by BSI-compliant security gateways. Only authorized communication MAY pass.', category: 'Netzwerksicherheit', subcategory: 'NdB-Anbindung', level: 'Verpflichtend', iso_mapping: 'A.8.22', implementation_guidance: 'BSI-zugelassene Sicherheitsgateways. Default-Deny-Policy. Protokoll- und Inhaltsfilterung.', verification_guidance: 'NdB-Gateway-Konfiguration und BSI-Zulassung pruefen.', source_url: null },

  // MS-EDR — Endpoint Detection & Response
  { control_number: 'MS-EDR-01', title_nl: 'Einsatz von Endpoint Detection and Response', title: 'Use of Endpoint Detection and Response', description_nl: 'Bundesbehoerden MUESSEN EDR-Loesungen auf allen verwalteten Endpunkten einsetzen. Die EDR-Loesung MUSS verdaechtiges Verhalten erkennen und automatisiert reagieren koennen.', description: 'Federal agencies MUST deploy EDR solutions on all managed endpoints. The EDR solution MUST be able to detect suspicious behavior and respond automatically.', category: 'Endpunktsicherheit', subcategory: 'EDR', level: 'Verpflichtend', iso_mapping: 'A.8.7', implementation_guidance: 'EDR auf allen Endpoints. Verhaltensbasierte Erkennung. Automatische Isolation bei Verdacht.', verification_guidance: 'EDR-Abdeckung und Erkennungsfaehigkeit pruefen.', source_url: null },
  { control_number: 'MS-EDR-02', title_nl: 'Zentrale EDR-Konsole und Incident-Anbindung', title: 'Central EDR console and incident integration', description_nl: 'EDR-Events MUESSEN in einer zentralen Konsole zusammengefuehrt werden. Die EDR-Loesung MUSS in den SIEM-/SOC-Prozess integriert sein.', description: 'EDR events MUST be aggregated in a central console. The EDR solution MUST be integrated into the SIEM/SOC process.', category: 'Endpunktsicherheit', subcategory: 'EDR-Integration', level: 'Verpflichtend', iso_mapping: 'A.8.16', implementation_guidance: 'EDR-SIEM-Integration. Automatische Ticket-Erstellung bei kritischen Alerts. SOC-Anbindung.', verification_guidance: 'EDR-SIEM-Integration und SOC-Prozess pruefen.', source_url: null },

  // MS-Softwareentwicklung — Secure Development
  { control_number: 'MS-DEV-01', title_nl: 'Sichere Softwareentwicklung in der Verwaltung', title: 'Secure software development in administration', description_nl: 'Software, die von oder fuer Bundesbehoerden entwickelt wird, MUSS einem sicheren Entwicklungsprozess folgen. SAST und DAST MUESSEN in den Entwicklungsprozess integriert sein.', description: 'Software developed by or for federal agencies MUST follow a secure development process. SAST and DAST MUST be integrated into the development process.', category: 'Softwareentwicklung', subcategory: 'Secure SDLC', level: 'Verpflichtend', iso_mapping: 'A.8.25', implementation_guidance: 'Secure SDLC mit Bedrohungsmodellierung, SAST/DAST/SCA in CI/CD. Security Gates.', verification_guidance: 'SDLC-Prozess und Security-Tool-Integration pruefen.', source_url: null },
  { control_number: 'MS-DEV-02', title_nl: 'Abhaengigkeitsmanagement und SCA', title: 'Dependency management and SCA', description_nl: 'Softwareprojekte MUESSEN ein Abhaengigkeitsmanagement implementieren. Bekannte Schwachstellen in Drittanbieter-Bibliotheken MUESSEN automatisiert erkannt und behoben werden.', description: 'Software projects MUST implement dependency management. Known vulnerabilities in third-party libraries MUST be automatically detected and remediated.', category: 'Softwareentwicklung', subcategory: 'SCA', level: 'Verpflichtend', iso_mapping: 'A.8.28', implementation_guidance: 'SCA-Tool in CI/CD (Dependabot, Snyk, Trivy). Automatische PR fuer Schwachstellen. SBOM-Erstellung.', verification_guidance: 'SCA-Integration und Schwachstellen-Behandlungsfristen pruefen.', source_url: null },

  // MS-IAM — Identity and Access Management
  { control_number: 'MS-IAM-01', title_nl: 'Zentrales Identitaetsmanagement', title: 'Central identity management', description_nl: 'Bundesbehoerden MUESSEN ein zentrales Identitaetsmanagement betreiben. Alle Benutzeridentitaeten MUESSEN in einem zentralen Verzeichnisdienst verwaltet werden.', description: 'Federal agencies MUST operate central identity management. All user identities MUST be managed in a central directory service.', category: 'Identitaetsmanagement', subcategory: 'IAM', level: 'Verpflichtend', iso_mapping: 'A.5.16', implementation_guidance: 'Zentrales IAM-System. Active Directory oder LDAP-basiert. SSO fuer alle Fachanwendungen.', verification_guidance: 'IAM-System und Verzeichnisdienst-Abdeckung pruefen.', source_url: null },
  { control_number: 'MS-IAM-02', title_nl: 'Multi-Faktor-Authentisierung fuer Verwaltungsnetze', title: 'Multi-factor authentication for administration networks', description_nl: 'Der Zugriff auf Verwaltungsnetze und -anwendungen MUSS durch Multi-Faktor-Authentisierung geschuetzt werden. Fuer privilegierte Zugriffe MUSS Hardware-basierte MFA eingesetzt werden.', description: 'Access to administration networks and applications MUST be protected by multi-factor authentication. Hardware-based MFA MUST be used for privileged access.', category: 'Identitaetsmanagement', subcategory: 'MFA', level: 'Verpflichtend', iso_mapping: 'A.8.5', implementation_guidance: 'MFA fuer alle Nutzer. FIDO2/PIV fuer privilegierte Zugriffe. Conditional Access Policies.', verification_guidance: 'MFA-Abdeckung und Hardware-Token-Einsatz pruefen.', source_url: null },
  { control_number: 'MS-IAM-03', title_nl: 'Privileged Access Management', title: 'Privileged Access Management', description_nl: 'Privilegierte Zugriffe MUESSEN ueber ein PAM-System verwaltet werden. Administratorkonten MUESSEN separate, personalisierte Accounts sein. Shared Accounts sind VERBOTEN.', description: 'Privileged access MUST be managed via a PAM system. Administrator accounts MUST be separate, personalized accounts. Shared accounts are PROHIBITED.', category: 'Identitaetsmanagement', subcategory: 'PAM', level: 'Verpflichtend', iso_mapping: 'A.8.2', implementation_guidance: 'PAM-Loesung mit Session-Recording. Personalisierte Admin-Accounts. Just-in-Time-Zugriffsmodell.', verification_guidance: 'PAM-Einsatz und Admin-Konto-Verwaltung pruefen.', source_url: null },

  // MS-Patch — Patch Management
  { control_number: 'MS-PATCH-01', title_nl: 'Patch-Management-Prozess', title: 'Patch management process', description_nl: 'Bundesbehoerden MUESSEN einen formalisierten Patch-Management-Prozess betreiben. Sicherheitspatches MUESSEN innerhalb definierter Fristen eingespielt werden: kritisch 72h, hoch 7 Tage, mittel 30 Tage.', description: 'Federal agencies MUST operate a formalized patch management process. Security patches MUST be applied within defined timeframes: critical 72h, high 7 days, medium 30 days.', category: 'Patch-Management', subcategory: 'Patch-Prozess', level: 'Verpflichtend', iso_mapping: 'A.8.8', implementation_guidance: 'Formalisierter Patch-Prozess. SLA: kritisch 72h, hoch 7d, mittel 30d. Patch-Compliance-Monitoring.', verification_guidance: 'Patch-Prozess und Einhaltung der Fristen pruefen.', source_url: null },
  { control_number: 'MS-PATCH-02', title_nl: 'Notfall-Patching (Out-of-Band)', title: 'Emergency patching (out-of-band)', description_nl: 'Fuer Zero-Day-Schwachstellen und aktiv ausgenutzte Schwachstellen MUSS ein beschleunigtes Patching-Verfahren existieren, das Patches innerhalb von 24 Stunden einspielen kann.', description: 'For zero-day and actively exploited vulnerabilities, an accelerated patching procedure MUST exist that can apply patches within 24 hours.', category: 'Patch-Management', subcategory: 'Notfall-Patching', level: 'Verpflichtend', iso_mapping: 'A.8.8', implementation_guidance: 'Out-of-Band-Patching-Prozess. 24h-Frist fuer Zero-Day. Vorab-getestete Deployment-Pipelines.', verification_guidance: 'Notfall-Patching-Prozess und 24h-Faehigkeit pruefen.', source_url: null },

  // MS-Datensicherung — Backup
  { control_number: 'MS-BACKUP-01', title_nl: 'Backup-Strategie fuer Bundesbehoerden', title: 'Backup strategy for federal agencies', description_nl: 'Bundesbehoerden MUESSEN eine dokumentierte Backup-Strategie betreiben. Die 3-2-1-Regel (3 Kopien, 2 Medien, 1 Offsite) MUSS als Mindeststandard eingehalten werden.', description: 'Federal agencies MUST operate a documented backup strategy. The 3-2-1 rule (3 copies, 2 media, 1 offsite) MUST be adhered to as minimum standard.', category: 'Datensicherung', subcategory: 'Backup-Strategie', level: 'Verpflichtend', iso_mapping: 'A.8.13', implementation_guidance: '3-2-1-Backup-Regel. Mindestens ein Air-Gapped-Backup. RPO/RTO pro System definieren.', verification_guidance: 'Backup-Strategie und 3-2-1-Einhaltung pruefen.', source_url: null },
  { control_number: 'MS-BACKUP-02', title_nl: 'Ransomware-resistente Backups', title: 'Ransomware-resistant backups', description_nl: 'Mindestens ein Backup-Ziel MUSS gegen Ransomware-Verschluesselung geschuetzt sein (Immutable Storage oder Air Gap). Regelmaessige Restore-Tests MUESSEN durchgefuehrt werden.', description: 'At least one backup target MUST be protected against ransomware encryption (immutable storage or air gap). Regular restore tests MUST be performed.', category: 'Datensicherung', subcategory: 'Ransomware-Schutz', level: 'Verpflichtend', iso_mapping: 'A.8.13', implementation_guidance: 'Immutable Backup (WORM oder Object Lock). Offline-Backup. Quartalsweiser Restore-Test.', verification_guidance: 'Ransomware-Resistenz und Restore-Test-Ergebnisse pruefen.', source_url: null },

  // MS-Awareness — Security Awareness
  { control_number: 'MS-AWARE-01', title_nl: 'Security-Awareness-Programm', title: 'Security awareness program', description_nl: 'Bundesbehoerden MUESSEN ein kontinuierliches Security-Awareness-Programm betreiben. Alle Mitarbeiter MUESSEN mindestens jaehrlich geschult werden. Phishing-Simulationen SOLLTEN regelmaessig durchgefuehrt werden.', description: 'Federal agencies MUST operate a continuous security awareness program. All employees MUST be trained at least annually. Phishing simulations SHOULD be performed regularly.', category: 'Awareness', subcategory: 'Schulungsprogramm', level: 'Verpflichtend', iso_mapping: 'A.6.3', implementation_guidance: 'Jaehrliche Pflichtschulung. Quartalsweise Phishing-Simulation. Meldekanal fuer verdaechtige E-Mails.', verification_guidance: 'Schulungsquoten und Phishing-Simulationsergebnisse pruefen.', source_url: null },
  { control_number: 'MS-AWARE-02', title_nl: 'Rollenspezifische Sicherheitsschulungen', title: 'Role-specific security training', description_nl: 'IT-Administratoren, Entwickler und Fuehrungskraefte MUESSEN rollenspezifische Sicherheitsschulungen erhalten. Die Schulungsinhalte MUESSEN an die spezifischen Bedrohungen der jeweiligen Rolle angepasst sein.', description: 'IT administrators, developers, and management MUST receive role-specific security training. Training content MUST be adapted to the specific threats of each role.', category: 'Awareness', subcategory: 'Rollenspezifisch', level: 'Verpflichtend', iso_mapping: 'A.6.3', implementation_guidance: 'Rollenprofile mit spezifischen Schulungsinhalten. Admin: Haertung, Incident. Dev: Secure Coding. Management: Risiko.', verification_guidance: 'Rollenspezifische Schulungsinhalte und Teilnahme pruefen.', source_url: null },
];

const output = {
  framework: {
    id: 'bsi-mindeststandards-extended',
    name: 'BSI Minimum Standards Extended (DNS, Cloud, EDR, IAM, VK)',
    name_nl: 'BSI Mindeststandards Erweitert (DNS, Cloud, EDR, IAM, VK)',
    issuing_body: 'Bundesamt fuer Sicherheit in der Informationstechnik (BSI)',
    version: '2024',
    effective_date: '2024-01-01',
    scope: 'Extended minimum standards for federal agencies: DNS security (DNSSEC, DoT/DoH), cloud computing (C5, data localization, BYOK), video conferencing, network segmentation, EDR, secure development, identity management (IAM, MFA, PAM), patch management, backup, and security awareness',
    scope_sectors: ['government'],
    structure_description: 'Eleven additional domains: DNS Security, Cloud Computing, Video Conferencing, Network Security, Endpoint Detection, Secure Development, Identity Management, Patch Management, Backup, and Security Awareness. Mandatory for all German federal agencies.',
    source_url: 'https://www.bsi.bund.de/DE/Themen/Oeffentliche-Verwaltung/Mindeststandards/mindeststandards_node.html',
    license: 'Public document',
    language: 'de+en',
  },
  controls,
  metadata: { ingested_at: new Date().toISOString(), total_controls: controls.length },
};

mkdirSync(DATA_DIR, { recursive: true });
writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
console.log(`BSI Mindeststandards Extended: ${controls.length} controls written to ${OUTPUT_FILE}`);
