// scripts/ingest-datenschutz-extended.ts
// Extended German data protection controls — deeper BfDI TOM measures,
// expanded DSK SDM reference measures, BDSG-specific requirements,
// and sector-specific data protection (Beschaeftigtendatenschutz, Forschung).

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'datenschutz-extended.json');

const controls = [
  // Extended TOM — Art. 32 DSGVO / §64 BDSG
  { control_number: 'TOM-EXT-01', title_nl: 'Zugangskontrolle zu Verarbeitungsanlagen', title: 'Access control to processing facilities', description_nl: 'Unbefugten MUSS der Zugang zu Verarbeitungsanlagen verwehrt werden. Zutrittskontrollsysteme (Schluesselkarten, Biometrie) MUESSEN implementiert werden. Besucherregelungen MUESSEN existieren.', description: 'Unauthorized persons MUST be denied access to processing facilities. Access control systems (key cards, biometrics) MUST be implemented. Visitor regulations MUST exist.', category: 'Technische und Organisatorische Massnahmen', subcategory: 'Zugangskontrolle', level: 'Pflicht', iso_mapping: 'A.7.1', implementation_guidance: 'Zutrittskontrolle zu Serverraeumen. Besucherregelungen. Protokollierung.', verification_guidance: 'Physische Zugangskontrolle und Besuchermanagement pruefen.', source_url: null },
  { control_number: 'TOM-EXT-02', title_nl: 'Datentraegerkontrolle', title: 'Data carrier control', description_nl: 'Es MUSS verhindert werden, dass Datentraeger unbefugt gelesen, kopiert, veraendert oder entfernt werden koennen. Verschluesselung mobiler Datentraeger MUSS durchgesetzt werden.', description: 'It MUST be prevented that data carriers can be read, copied, modified, or removed without authorization. Encryption of mobile data carriers MUST be enforced.', category: 'Technische und Organisatorische Massnahmen', subcategory: 'Datentraegerkontrolle', level: 'Pflicht', iso_mapping: 'A.7.10', implementation_guidance: 'Verschluesselung mobiler Datentraeger. USB-Port-Kontrolle. Sichere Entsorgung.', verification_guidance: 'Datentraeger-Verschluesselung und Entsorgungsprozess pruefen.', source_url: null },
  { control_number: 'TOM-EXT-03', title_nl: 'Speicherkontrolle', title: 'Storage control', description_nl: 'Es MUSS verhindert werden, dass gespeicherte personenbezogene Daten unbefugt zur Kenntnis genommen, veraendert oder geloescht werden koennen. Zugriffskontrolle und Verschluesselung MUESSEN umgesetzt sein.', description: 'It MUST be prevented that stored personal data can be read, modified, or deleted without authorization. Access control and encryption MUST be implemented.', category: 'Technische und Organisatorische Massnahmen', subcategory: 'Speicherkontrolle', level: 'Pflicht', iso_mapping: 'A.8.3', implementation_guidance: 'Datenbank-Zugriffskontrolle. Verschluesselung at Rest. Backup-Verschluesselung.', verification_guidance: 'Speicherkontrolle und Verschluesselung pruefen.', source_url: null },
  { control_number: 'TOM-EXT-04', title_nl: 'Benutzerkontrolle', title: 'User control', description_nl: 'Es MUSS verhindert werden, dass Datenverarbeitungssysteme von Unbefugten genutzt werden koennen. Individuelle Benutzerauthentisierung MUSS durchgesetzt werden.', description: 'It MUST be prevented that data processing systems can be used by unauthorized persons. Individual user authentication MUST be enforced.', category: 'Technische und Organisatorische Massnahmen', subcategory: 'Benutzerkontrolle', level: 'Pflicht', iso_mapping: 'A.8.5', implementation_guidance: 'Individuelle Accounts. Starke Authentisierung. Automatische Abmeldung.', verification_guidance: 'Benutzerauthentisierung und Sessionmanagement pruefen.', source_url: null },
  { control_number: 'TOM-EXT-05', title_nl: 'Zugriffskontrolle (Need-to-Know)', title: 'Access control (need-to-know)', description_nl: 'Berechtigte DUERFEN nur auf die personenbezogenen Daten zugreifen, die sie fuer ihre Aufgaben benoetigen. Rollenbasierte Zugriffskontrolle MUSS implementiert sein.', description: 'Authorized persons MAY only access personal data they need for their tasks. Role-based access control MUST be implemented.', category: 'Technische und Organisatorische Massnahmen', subcategory: 'Zugriffskontrolle', level: 'Pflicht', iso_mapping: 'A.8.3', implementation_guidance: 'RBAC mit Need-to-Know. Zugriffs-Audit. Regelmaessige Rezertifizierung.', verification_guidance: 'Zugriffskontrolle nach Need-to-Know-Prinzip pruefen.', source_url: null },
  { control_number: 'TOM-EXT-06', title_nl: 'Uebertragungskontrolle', title: 'Transmission control', description_nl: 'Es MUSS nachvollziehbar sein, an welche Stellen personenbezogene Daten uebermittelt werden. Die Uebertragung MUSS verschluesselt erfolgen. Empfaenger MUESSEN dokumentiert werden.', description: 'It MUST be traceable to which recipients personal data is transmitted. Transmission MUST be encrypted. Recipients MUST be documented.', category: 'Technische und Organisatorische Massnahmen', subcategory: 'Uebertragungskontrolle', level: 'Pflicht', iso_mapping: 'A.8.24', implementation_guidance: 'Verschluesselte Uebertragung. Empfaenger-Dokumentation. DLP-Massnahmen.', verification_guidance: 'Uebertragungsverschluesselung und Empfaenger-Dokumentation pruefen.', source_url: null },
  { control_number: 'TOM-EXT-07', title_nl: 'Eingabekontrolle', title: 'Input control', description_nl: 'Es MUSS nachtraeglich festgestellt werden koennen, ob und von wem personenbezogene Daten eingegeben, veraendert oder geloescht worden sind. Audit-Trails MUESSEN implementiert sein.', description: 'It MUST be possible to determine retrospectively whether and by whom personal data has been entered, modified, or deleted. Audit trails MUST be implemented.', category: 'Technische und Organisatorische Massnahmen', subcategory: 'Eingabekontrolle', level: 'Pflicht', iso_mapping: 'A.8.15', implementation_guidance: 'Audit-Trail fuer alle Datenmanipulationen. Wer/Was/Wann-Protokollierung.', verification_guidance: 'Eingabekontrolle und Audit-Trail-Vollstaendigkeit pruefen.', source_url: null },
  { control_number: 'TOM-EXT-08', title_nl: 'Transportkontrolle', title: 'Transport control', description_nl: 'Bei physischem Transport personenbezogener Daten (Datentraeger, Akten) MUSS die Vertraulichkeit und Integritaet sichergestellt werden. Verschlossene Transportbehaeltnisse MUESSEN verwendet werden.', description: 'During physical transport of personal data (data carriers, files), confidentiality and integrity MUST be ensured. Locked transport containers MUST be used.', category: 'Technische und Organisatorische Massnahmen', subcategory: 'Transportkontrolle', level: 'Pflicht', iso_mapping: 'A.7.10', implementation_guidance: 'Verschlossene Transportbehaeltnisse. Begleitdokumentation. Verschluesselung.', verification_guidance: 'Transportmassnahmen und Verschluesselung pruefen.', source_url: null },
  { control_number: 'TOM-EXT-09', title_nl: 'Wiederherstellbarkeit', title: 'Recoverability', description_nl: 'Personenbezogene Daten MUESSEN nach technischen Stoerungen oder Vorfaellen wiederhergestellt werden koennen. Backup-Systeme MUESSEN implementiert und regelmaessig getestet werden.', description: 'Personal data MUST be recoverable after technical disruptions or incidents. Backup systems MUST be implemented and regularly tested.', category: 'Technische und Organisatorische Massnahmen', subcategory: 'Wiederherstellbarkeit', level: 'Pflicht', iso_mapping: 'A.8.13', implementation_guidance: 'Regelmaessige Backups. Verschluesselung. Restore-Tests. Offsite-Kopien.', verification_guidance: 'Backup-Prozess und Restore-Testergebnisse pruefen.', source_url: null },
  { control_number: 'TOM-EXT-10', title_nl: 'Zuverlaessigkeit der Verarbeitung', title: 'Reliability of processing', description_nl: 'Systeme zur Verarbeitung personenbezogener Daten MUESSEN zuverlaessig funktionieren. Stoerungen MUESSEN erkannt und behoben werden. Redundanz SOLLTE implementiert werden.', description: 'Systems for processing personal data MUST function reliably. Disruptions MUST be detected and resolved. Redundancy SHOULD be implemented.', category: 'Technische und Organisatorische Massnahmen', subcategory: 'Zuverlaessigkeit', level: 'Pflicht', iso_mapping: 'A.8.14', implementation_guidance: 'Monitoring. Redundante Systeme. Stoerungserkennung. SLAs.', verification_guidance: 'Systemzuverlaessigkeit und Monitoring pruefen.', source_url: null },

  // BDSG-spezifische Anforderungen
  { control_number: 'BDSG-01', title_nl: 'Datenschutzbeauftragter (§38 BDSG)', title: 'Data protection officer', description_nl: 'Unternehmen mit mindestens 20 staendig mit der automatisierten Verarbeitung beschaeftigten Personen MUESSEN einen Datenschutzbeauftragten (DSB) benennen. Der DSB MUSS die erforderliche Fachkunde besitzen.', description: 'Companies with at least 20 persons permanently engaged in automated processing MUST appoint a data protection officer (DPO). The DPO MUST possess the required expertise.', category: 'BDSG', subcategory: 'Datenschutzbeauftragter', level: 'Pflicht', iso_mapping: 'A.5.2', implementation_guidance: 'DSB benennen. Fachkunde sicherstellen. DSB-Kontaktdaten veroeffentlichen.', verification_guidance: 'DSB-Benennung und Qualifikation pruefen.', source_url: null },
  { control_number: 'BDSG-02', title_nl: 'Beschaeftigtendatenschutz (§26 BDSG)', title: 'Employee data protection', description_nl: 'Personenbezogene Daten von Beschaeftigten DUERFEN nur verarbeitet werden, soweit dies fuer das Beschaeftigungsverhaeltnis erforderlich ist. Bei besonderen Kategorien (Gesundheitsdaten) gelten verstaerkte Anforderungen.', description: 'Personal data of employees MAY only be processed insofar as necessary for the employment relationship. Enhanced requirements apply to special categories (health data).', category: 'BDSG', subcategory: 'Beschaeftigtendatenschutz', level: 'Pflicht', iso_mapping: 'A.5.34', implementation_guidance: 'Beschaeftigtendatenschutz-Konzept. Erforderlichkeitspruefung. Betriebsvereinbarungen.', verification_guidance: 'Beschaeftigtendaten-Verarbeitung auf Erforderlichkeit pruefen.', source_url: null },
  { control_number: 'BDSG-03', title_nl: 'Videoueberwachung oeffentlich zugaenglicher Raeume (§4 BDSG)', title: 'Video surveillance of publicly accessible areas', description_nl: 'Videoueberwachung oeffentlich zugaenglicher Raeume DARF nur erfolgen, wenn sie zur Wahrnehmung berechtigter Interessen erforderlich ist. Die Speicherdauer MUSS begrenzt und Hinweisschilder MUESSEN angebracht werden.', description: 'Video surveillance of publicly accessible areas MAY only occur if necessary for the exercise of legitimate interests. Storage duration MUST be limited and notice signs MUST be displayed.', category: 'BDSG', subcategory: 'Videoueberwachung', level: 'Pflicht', iso_mapping: 'A.7.4', implementation_guidance: 'Verhaeltnismaessigkeitspruefung. Hinweisschilder. Speicherfrist (max. 72h). DSFA.', verification_guidance: 'Videoueberwachung auf Rechtmaessigkeit und Speicherfrist pruefen.', source_url: null },
  { control_number: 'BDSG-04', title_nl: 'Verarbeitung besonderer Kategorien (§22 BDSG)', title: 'Processing of special categories', description_nl: 'Die Verarbeitung besonderer Kategorien personenbezogener Daten (Gesundheit, Religion, ethnische Herkunft) ERFORDERT zusaetzliche Schutzmassnahmen. §22 BDSG praezisiert die Bedingungen.', description: 'Processing of special categories of personal data (health, religion, ethnic origin) REQUIRES additional protective measures. Section 22 BDSG specifies the conditions.', category: 'BDSG', subcategory: 'Besondere Kategorien', level: 'Pflicht', iso_mapping: 'A.5.34', implementation_guidance: 'Zusaetzliche TOM fuer besondere Kategorien. Verschluesselung. Zugriffsbeschraenkung.', verification_guidance: 'Zusaetzliche Schutzmassnahmen fuer besondere Kategorien pruefen.', source_url: null },
  { control_number: 'BDSG-05', title_nl: 'Datengeheimnis und Verpflichtung (§53 BDSG)', title: 'Data secrecy and obligation', description_nl: 'Personen, die Zugang zu personenbezogenen Daten haben, MUESSEN auf das Datengeheimnis verpflichtet werden. Die Verpflichtung MUSS dokumentiert werden und auch nach Ende der Taetigkeit fortbestehen.', description: 'Persons with access to personal data MUST be obligated to data secrecy. The obligation MUST be documented and continue to apply after the end of the activity.', category: 'BDSG', subcategory: 'Datengeheimnis', level: 'Pflicht', iso_mapping: 'A.6.6', implementation_guidance: 'Verpflichtung auf Datengeheimnis bei Einstellung. Dokumentation. Fortbestehen nach Austritt.', verification_guidance: 'Verpflichtungserklärungen auf Vollstaendigkeit pruefen.', source_url: null },

  // DSK Orientierungshilfe
  { control_number: 'DSK-OH-01', title_nl: 'Datenschutzfreundliche Voreinstellungen (Privacy by Default)', title: 'Data protection friendly defaults', description_nl: 'IT-Systeme MUESSEN so konfiguriert werden, dass standardmaessig nur die fuer den jeweiligen Zweck erforderlichen personenbezogenen Daten verarbeitet werden (Art. 25 Abs. 2 DSGVO).', description: 'IT systems MUST be configured so that by default only personal data necessary for the respective purpose is processed (Art. 25 para. 2 GDPR).', category: 'DSK Orientierungshilfe', subcategory: 'Privacy by Default', level: 'Pflicht', iso_mapping: 'A.5.34', implementation_guidance: 'Standard-Einstellungen auf Datenminimierung. Opt-in statt Opt-out. Minimale Vorauswahl.', verification_guidance: 'Standard-Konfiguration auf Datenminimierung pruefen.', source_url: null },
  { control_number: 'DSK-OH-02', title_nl: 'Datenschutz durch Technikgestaltung (Privacy by Design)', title: 'Data protection through technology design', description_nl: 'Der Datenschutz MUSS von Anfang an in die Technikgestaltung integriert werden (Art. 25 Abs. 1 DSGVO). Datenschutz-Folgenabschaetzungen MUESSEN fruehzeitig durchgefuehrt werden.', description: 'Data protection MUST be integrated into technology design from the start (Art. 25 para. 1 GDPR). Data protection impact assessments MUST be performed early.', category: 'DSK Orientierungshilfe', subcategory: 'Privacy by Design', level: 'Pflicht', iso_mapping: 'A.5.34', implementation_guidance: 'Datenschutz in Anforderungsanalyse. DSFA bei neuen Verarbeitungen. PETs evaluieren.', verification_guidance: 'Privacy-by-Design-Integration in Entwicklungsprozess pruefen.', source_url: null },
  { control_number: 'DSK-OH-03', title_nl: 'Auftragsverarbeitung (Art. 28 DSGVO)', title: 'Order processing (Art. 28 GDPR)', description_nl: 'Bei Auftragsverarbeitung MUSS ein Auftragsverarbeitungsvertrag (AVV) nach Art. 28 DSGVO geschlossen werden. Der Auftragsverarbeiter MUSS hinreichende Garantien bieten.', description: 'For order processing, a data processing agreement (DPA) according to Art. 28 GDPR MUST be concluded. The processor MUST provide sufficient guarantees.', category: 'DSK Orientierungshilfe', subcategory: 'Auftragsverarbeitung', level: 'Pflicht', iso_mapping: 'A.5.20', implementation_guidance: 'AVV nach Art. 28. Technische und organisatorische Massnahmen dokumentiert. Audit-Recht.', verification_guidance: 'AVV-Abschluss und TOM des Auftragsverarbeiters pruefen.', source_url: null },
  { control_number: 'DSK-OH-04', title_nl: 'Drittlaendertransfer (Art. 44-49 DSGVO)', title: 'Third country transfer (Art. 44-49 GDPR)', description_nl: 'Die Uebermittlung personenbezogener Daten in Drittlaender DARF nur erfolgen, wenn ein Angemessenheitsbeschluss, geeignete Garantien (SCC, BCR) oder eine Ausnahme nach Art. 49 vorliegt.', description: 'Transfer of personal data to third countries MAY only occur if an adequacy decision, appropriate safeguards (SCC, BCR), or an exception under Art. 49 exists.', category: 'DSK Orientierungshilfe', subcategory: 'Drittlaendertransfer', level: 'Pflicht', iso_mapping: 'A.5.34', implementation_guidance: 'Drittlaendertransfer-Pruefung. SCC oder BCR. Transfer Impact Assessment (TIA).', verification_guidance: 'Drittlaendertransfer und Rechtsgrundlage pruefen.', source_url: null },
  { control_number: 'DSK-OH-05', title_nl: 'Loeschkonzept nach DIN 66398', title: 'Deletion concept according to DIN 66398', description_nl: 'Ein strukturiertes Loeschkonzept MUSS erstellt werden, das Loeschregeln, Loeschfristen und Loeschklassen fuer alle personenbezogenen Daten definiert. Die DIN 66398 SOLLTE als Grundlage dienen.', description: 'A structured deletion concept MUST be created defining deletion rules, deletion periods, and deletion classes for all personal data. DIN 66398 SHOULD serve as the basis.', category: 'DSK Orientierungshilfe', subcategory: 'Loeschkonzept', level: 'Pflicht', iso_mapping: 'A.5.33', implementation_guidance: 'Loeschkonzept nach DIN 66398. Loeschklassen definieren. Automatisierte Loeschung.', verification_guidance: 'Loeschkonzept und Umsetzung der Loeschfristen pruefen.', source_url: null },

  // Erweiterte DSK SDM Referenzmassnahmen
  { control_number: 'SDM-REF-04', title_nl: 'Belastbarkeit der Verarbeitungssysteme', title: 'Resilience of processing systems', description_nl: 'Die Belastbarkeit der Verarbeitungssysteme MUSS sichergestellt sein. Systeme MUESSEN gegen DDoS-Angriffe, Lastspitzen und Hardware-Ausfaelle geschuetzt sein.', description: 'The resilience of processing systems MUST be ensured. Systems MUST be protected against DDoS attacks, peak loads, and hardware failures.', category: 'DSK SDM Erweitert', subcategory: 'Belastbarkeit', level: 'Pflicht', iso_mapping: 'A.8.14', implementation_guidance: 'DDoS-Schutz. Lastverteilung. Redundante Hardware. Autoscaling.', verification_guidance: 'Belastbarkeit und DDoS-Schutzmassnahmen pruefen.', source_url: null },
  { control_number: 'SDM-REF-05', title_nl: 'Datenschutz-Management-System (DSMS)', title: 'Data protection management system', description_nl: 'Ein Datenschutz-Management-System SOLLTE implementiert werden, das die systematische Steuerung aller datenschutzrelevanten Prozesse ermoeglicht. Das DSMS SOLLTE mit dem ISMS integriert werden.', description: 'A data protection management system SHOULD be implemented enabling systematic management of all data protection relevant processes. The DPMS SHOULD be integrated with the ISMS.', category: 'DSK SDM Erweitert', subcategory: 'DSMS', level: 'Empfohlen', iso_mapping: 'A.5.1', implementation_guidance: 'DSMS implementieren. Integration mit ISMS. Verarbeitungsverzeichnis als Kern.', verification_guidance: 'DSMS-Implementation und ISMS-Integration pruefen.', source_url: null },

  // VDA ISA Extended
  { control_number: 'ISA-EXT-01', title_nl: 'Prototypenschutz — Physische Sicherheit', title: 'Prototype protection — physical security', description_nl: 'Prototypen und vertrauliche Fahrzeugdaten MUESSEN durch physische Sicherheitsmassnahmen geschuetzt werden. Zutritt zu Prototypenbereichen MUSS strikt kontrolliert werden.', description: 'Prototypes and confidential vehicle data MUST be protected by physical security measures. Access to prototype areas MUST be strictly controlled.', category: 'VDA ISA Erweitert', subcategory: 'Prototypenschutz', level: 'Verpflichtend', iso_mapping: 'A.7.1', implementation_guidance: 'Zutrittskontrolle fuer Prototypenbereiche. Fotoverbot. Besucherbegleitung.', verification_guidance: 'Physische Sicherheit in Prototypenbereichen pruefen.', source_url: null },
  { control_number: 'ISA-EXT-02', title_nl: 'Prototypenschutz — Digitaler Schutz', title: 'Prototype protection — digital protection', description_nl: 'Digitale Prototypendaten (CAD, Simulationen) MUESSEN durch Zugriffskontrolle, Verschluesselung und DLP-Massnahmen geschuetzt werden. Die Weitergabe MUSS kontrolliert werden.', description: 'Digital prototype data (CAD, simulations) MUST be protected by access control, encryption, and DLP measures. Distribution MUST be controlled.', category: 'VDA ISA Erweitert', subcategory: 'Prototypenschutz', level: 'Verpflichtend', iso_mapping: 'A.8.12', implementation_guidance: 'DLP fuer Prototypendaten. Verschluesselung. Zugriffskontrolle. Watermarking.', verification_guidance: 'Digitalen Prototypenschutz und DLP-Massnahmen pruefen.', source_url: null },
  { control_number: 'ISA-EXT-03', title_nl: 'TISAX-Assessment-Vorbereitung', title: 'TISAX assessment preparation', description_nl: 'Unternehmen, die ein TISAX-Assessment anstreben, MUESSEN alle anwendbaren Controls des VDA ISA umsetzen und dokumentieren. Self-Assessment MUSS vor dem externen Assessment durchgefuehrt werden.', description: 'Companies pursuing TISAX assessment MUST implement and document all applicable VDA ISA controls. Self-assessment MUST be performed before external assessment.', category: 'VDA ISA Erweitert', subcategory: 'TISAX-Assessment', level: 'Verpflichtend', iso_mapping: 'A.5.35', implementation_guidance: 'VDA ISA Self-Assessment. Gap-Analyse. Massnahmenplanung. Assessment-Provider waehlen.', verification_guidance: 'Self-Assessment und Massnahmenumsetzung pruefen.', source_url: null },
];

const output = {
  framework: {
    id: 'datenschutz-extended',
    name: 'German Data Protection Extended (BDSG, TOM, DSK, VDA ISA)',
    name_nl: 'Datenschutz Erweitert (BDSG, TOM, DSK, VDA ISA)',
    issuing_body: 'BfDI / DSK / BaFin / VDA',
    version: '2024',
    effective_date: '2024-01-01',
    scope: 'Extended German data protection controls: detailed TOM measures (Art. 32 GDPR), BDSG-specific requirements (DPO, employee data, video surveillance, special categories), DSK guidance (Privacy by Design/Default, DPA, third country transfer, deletion concept), and VDA ISA prototype protection',
    scope_sectors: ['all', 'automotive', 'manufacturing'],
    structure_description: 'Covers TOM detail measures (access, carrier, storage, user, transmission, input, transport, recovery, reliability controls), BDSG specifics (DPO, employee data, surveillance, special categories, data secrecy), DSK guidance (PbD, PbDefault, DPA, transfer, deletion), extended SDM measures, and VDA ISA prototype protection.',
    source_url: 'https://www.bfdi.bund.de/DE/Datenschutz/datenschutz_node.html',
    license: 'Public sector publication',
    language: 'de+en',
  },
  controls,
  metadata: { ingested_at: new Date().toISOString(), total_controls: controls.length },
};

mkdirSync(DATA_DIR, { recursive: true });
writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
console.log(`Datenschutz Extended: ${controls.length} controls written to ${OUTPUT_FILE}`);
