// scripts/ingest-c5.ts
// Ingests BSI Cloud Computing Compliance Criteria Catalogue (C5:2020) controls.
// Source: BSI — 17 control domains, ~121 controls.

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'bsi-c5.json');

interface C5Control {
  control_number: string;
  title: string | null;
  title_nl: string;
  description: string | null;
  description_nl: string;
  category: string;
  subcategory: string;
  level: string;
  iso_mapping: string | null;
  implementation_guidance: string | null;
  verification_guidance: string | null;
  source_url: string | null;
}

const controls: C5Control[] = [
  // OIS — Organisation der Informationssicherheit
  { control_number: 'OIS-01', title_nl: 'Informationssicherheitsmanagementsystem', title: 'Information security management system', description_nl: 'Der Cloud-Anbieter betreibt ein Informationssicherheitsmanagementsystem (ISMS), das die fuer den Cloud-Dienst relevanten gesetzlichen, regulatorischen und vertraglichen Anforderungen beruecksichtigt.', description: 'The cloud provider operates an ISMS that considers all relevant legal, regulatory, and contractual requirements for the cloud service.', category: 'OIS', subcategory: 'Organisation der Informationssicherheit', level: 'Basis', iso_mapping: 'A.5.1', implementation_guidance: 'ISMS nach ISO 27001 oder BSI IT-Grundschutz aufbauen und zertifizieren lassen.', verification_guidance: 'ISMS-Zertifikat oder Auditbericht pruefen.', source_url: 'https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Informationen-und-Empfehlungen/Empfehlungen-nach-Angriffszielen/Cloud-Computing/Kriterienkatalog-C5/kriterienkatalog-c5_node.html' },
  { control_number: 'OIS-02', title_nl: 'Informationssicherheitsleitlinie', title: 'Information security policy', description_nl: 'Der Cloud-Anbieter hat eine Informationssicherheitsleitlinie definiert und veroeffentlicht, die von der Geschaeftsleitung genehmigt ist.', description: 'The cloud provider has defined and published an information security policy approved by management.', category: 'OIS', subcategory: 'Organisation der Informationssicherheit', level: 'Basis', iso_mapping: 'A.5.1', implementation_guidance: 'IS-Leitlinie erstellen, von Geschaeftsfuehrung genehmigen lassen und allen Mitarbeitern zugaenglich machen.', verification_guidance: 'IS-Leitlinie auf Genehmigung und Aktualitaet pruefen.', source_url: null },
  { control_number: 'OIS-03', title_nl: 'Verantwortung der Geschaeftsleitung', title: 'Management responsibility', description_nl: 'Die Geschaeftsleitung des Cloud-Anbieters traegt die Gesamtverantwortung fuer die Informationssicherheit und stellt angemessene Ressourcen bereit.', description: 'The management of the cloud provider bears overall responsibility for information security and provides adequate resources.', category: 'OIS', subcategory: 'Organisation der Informationssicherheit', level: 'Basis', iso_mapping: 'A.5.4', implementation_guidance: 'Verantwortlichkeit der Geschaeftsfuehrung dokumentieren. IS-Budget planen und freigeben.', verification_guidance: 'Budgetfreigaben und Verantwortlichkeitsdokumentation pruefen.', source_url: null },
  { control_number: 'OIS-04', title_nl: 'Rollen und Verantwortlichkeiten', title: 'Roles and responsibilities', description_nl: 'Der Cloud-Anbieter hat Rollen und Verantwortlichkeiten fuer die Informationssicherheit definiert und zugewiesen.', description: 'The cloud provider has defined and assigned roles and responsibilities for information security.', category: 'OIS', subcategory: 'Organisation der Informationssicherheit', level: 'Basis', iso_mapping: 'A.5.2', implementation_guidance: 'RACI-Matrix fuer IS-Aufgaben erstellen und kommunizieren.', verification_guidance: 'Rollenbeschreibungen und Zuweisungsnachweise pruefen.', source_url: null },
  { control_number: 'OIS-05', title_nl: 'Risikomanagement', title: 'Risk management', description_nl: 'Der Cloud-Anbieter hat einen Risikomanagementprozess etabliert, der die cloud-spezifischen Risiken bewertet und behandelt.', description: 'The cloud provider has established a risk management process that assesses and treats cloud-specific risks.', category: 'OIS', subcategory: 'Organisation der Informationssicherheit', level: 'Basis', iso_mapping: 'A.5.7', implementation_guidance: 'Risikoanalyse fuer Cloud-Dienste durchfuehren. Risikobehandlungsplan erstellen.', verification_guidance: 'Risikoregister und Behandlungsplan pruefen.', source_url: null },

  // SP — Sicherheitsrichtlinien
  { control_number: 'SP-01', title_nl: 'Richtlinien und Arbeitsanweisungen', title: 'Policies and work instructions', description_nl: 'Der Cloud-Anbieter hat themenspezifische Richtlinien und Arbeitsanweisungen definiert, die sich an der Informationssicherheitsleitlinie orientieren.', description: 'The cloud provider has defined topic-specific policies and work instructions aligned with the IS policy.', category: 'SP', subcategory: 'Sicherheitsrichtlinien', level: 'Basis', iso_mapping: 'A.5.1', implementation_guidance: 'Themenspezifische Richtlinien (z.B. Passwort, Verschluesselung, Zugang) erstellen.', verification_guidance: 'Richtlinienverzeichnis auf Vollstaendigkeit pruefen.', source_url: null },
  { control_number: 'SP-02', title_nl: 'Ueberpruefung der Richtlinien', title: 'Review of policies', description_nl: 'Die Informationssicherheitsrichtlinien werden regelmaessig und bei wesentlichen Aenderungen ueberprueft und aktualisiert.', description: 'Information security policies are regularly reviewed and updated, as well as upon significant changes.', category: 'SP', subcategory: 'Sicherheitsrichtlinien', level: 'Basis', iso_mapping: 'A.5.1', implementation_guidance: 'Jaehrliche Richtlinien-Reviews planen. Aenderungsprozess definieren.', verification_guidance: 'Review-Nachweise und Aenderungsprotokolle pruefen.', source_url: null },

  // HR — Personal
  { control_number: 'HR-01', title_nl: 'Sicherheitsueberpruefung von Mitarbeitern', title: 'Security screening of employees', description_nl: 'Vor Einstellung von Mitarbeitern fuehrt der Cloud-Anbieter angemessene Hintergrundueberpruefungen durch.', description: 'Before hiring employees, the cloud provider conducts appropriate background checks.', category: 'HR', subcategory: 'Personal', level: 'Basis', iso_mapping: 'A.6.1', implementation_guidance: 'Background-Checks gemaess lokalen Gesetzen durchfuehren. Ergebnisse dokumentieren.', verification_guidance: 'Screening-Prozess und Nachweise pruefen.', source_url: null },
  { control_number: 'HR-02', title_nl: 'Arbeitsvertragliche Regelungen', title: 'Employment contract provisions', description_nl: 'Die Arbeitsvertraege enthalten Regelungen zur Informationssicherheit, einschliesslich Vertraulichkeitsvereinbarungen.', description: 'Employment contracts include provisions on information security, including confidentiality agreements.', category: 'HR', subcategory: 'Personal', level: 'Basis', iso_mapping: 'A.6.2', implementation_guidance: 'IS-Klauseln und NDAs in Arbeitsvertraege aufnehmen.', verification_guidance: 'Mustervertraege auf IS-Regelungen pruefen.', source_url: null },
  { control_number: 'HR-03', title_nl: 'Sicherheitssensibilisierung und Schulung', title: 'Security awareness and training', description_nl: 'Der Cloud-Anbieter fuehrt regelmaessige Schulungen und Sensibilisierungsmassnahmen zur Informationssicherheit durch.', description: 'The cloud provider conducts regular training and awareness measures for information security.', category: 'HR', subcategory: 'Personal', level: 'Basis', iso_mapping: 'A.6.3', implementation_guidance: 'Jaehrliche Pflichtschulungen und laufende Awareness-Kampagnen durchfuehren.', verification_guidance: 'Schulungsnachweise und Teilnahmeraten pruefen.', source_url: null },

  // AM — Asset Management
  { control_number: 'AM-01', title_nl: 'Inventarisierung der Assets', title: 'Asset inventory', description_nl: 'Der Cloud-Anbieter fuehrt ein vollstaendiges Inventar aller fuer den Cloud-Dienst relevanten Assets.', description: 'The cloud provider maintains a complete inventory of all assets relevant to the cloud service.', category: 'AM', subcategory: 'Asset Management', level: 'Basis', iso_mapping: 'A.5.9', implementation_guidance: 'CMDB oder Asset-Register aufbauen und aktuell halten.', verification_guidance: 'Asset-Inventar auf Vollstaendigkeit pruefen.', source_url: null },
  { control_number: 'AM-02', title_nl: 'Klassifizierung von Informationen', title: 'Classification of information', description_nl: 'Informationen werden gemaess ihrem Schutzbedarf klassifiziert und entsprechend behandelt.', description: 'Information is classified according to its protection needs and treated accordingly.', category: 'AM', subcategory: 'Asset Management', level: 'Basis', iso_mapping: 'A.5.12', implementation_guidance: 'Klassifizierungsschema definieren. Labeling-Richtlinie erstellen.', verification_guidance: 'Klassifizierungsschema und Anwendung pruefen.', source_url: null },
  { control_number: 'AM-03', title_nl: 'Rueckgabe von Assets', title: 'Return of assets', description_nl: 'Bei Beendigung des Beschaeftigungsverhaeltnisses oder Vertragsendes werden alle Assets zurueckgegeben.', description: 'All assets are returned upon termination of employment or contract.', category: 'AM', subcategory: 'Asset Management', level: 'Basis', iso_mapping: 'A.5.11', implementation_guidance: 'Rueckgabeprozess in Offboarding-Checkliste integrieren.', verification_guidance: 'Rueckgabenachweise stichprobenartig pruefen.', source_url: null },

  // PS — Physische Sicherheit
  { control_number: 'PS-01', title_nl: 'Physische Sicherheitsperimeter', title: 'Physical security perimeters', description_nl: 'Der Cloud-Anbieter hat physische Sicherheitsperimeter definiert und umgesetzt, um den Zugang zu Bereichen mit informationsverarbeitenden Anlagen zu schuetzen.', description: 'The cloud provider has defined and implemented physical security perimeters to protect areas with information processing facilities.', category: 'PS', subcategory: 'Physische Sicherheit', level: 'Basis', iso_mapping: 'A.7.1', implementation_guidance: 'Sicherheitszonen definieren. Zutrittskontrollsysteme installieren.', verification_guidance: 'Physische Sicherheitsmassnahmen vor Ort pruefen.', source_url: null },
  { control_number: 'PS-02', title_nl: 'Zugangskontrollen', title: 'Access controls', description_nl: 'Der Zugang zu sicherheitsrelevanten Bereichen ist durch angemessene Zugangskontrollen geschuetzt.', description: 'Access to security-relevant areas is protected by appropriate access controls.', category: 'PS', subcategory: 'Physische Sicherheit', level: 'Basis', iso_mapping: 'A.7.2', implementation_guidance: 'Mehrstufige Zutrittskontrolle (Karte, PIN, Biometrie) fuer Rechenzentren.', verification_guidance: 'Zutrittsprotokolle und Zugangskontrollen pruefen.', source_url: null },
  { control_number: 'PS-03', title_nl: 'Schutz vor Umweltbedrohungen', title: 'Protection against environmental threats', description_nl: 'Massnahmen zum Schutz vor Brand, Wasser, Stromausfall und anderen Umweltbedrohungen sind umgesetzt.', description: 'Measures for protection against fire, water, power failure, and other environmental threats are implemented.', category: 'PS', subcategory: 'Physische Sicherheit', level: 'Basis', iso_mapping: 'A.7.5', implementation_guidance: 'Brandschutz, Wassermelder, USV und Klimatisierung installieren.', verification_guidance: 'Technische Schutzmassnahmen und Wartungsnachweise pruefen.', source_url: null },

  // OPS — Regelbetrieb
  { control_number: 'OPS-01', title_nl: 'Dokumentierte Betriebsverfahren', title: 'Documented operating procedures', description_nl: 'Betriebsverfahren fuer den Cloud-Dienst sind dokumentiert und den relevanten Mitarbeitern zugaenglich.', description: 'Operating procedures for the cloud service are documented and available to relevant staff.', category: 'OPS', subcategory: 'Regelbetrieb', level: 'Basis', iso_mapping: 'A.5.37', implementation_guidance: 'Betriebshandbuecher erstellen und zentral verfuegbar machen.', verification_guidance: 'Betriebshandbuecher auf Aktualitaet und Zugaenglichkeit pruefen.', source_url: null },
  { control_number: 'OPS-02', title_nl: 'Aenderungsmanagement', title: 'Change management', description_nl: 'Aenderungen an IT-Systemen und Anwendungen des Cloud-Dienstes werden durch einen dokumentierten Aenderungsmanagementprozess gesteuert.', description: 'Changes to IT systems and applications of the cloud service are managed through a documented change management process.', category: 'OPS', subcategory: 'Regelbetrieb', level: 'Basis', iso_mapping: 'A.8.32', implementation_guidance: 'Change-Management-Prozess mit CAB, Risikoanalyse und Rollback-Planung einrichten.', verification_guidance: 'Change-Tickets und Genehmigungen stichprobenartig pruefen.', source_url: null },
  { control_number: 'OPS-03', title_nl: 'Kapazitaetsmanagement', title: 'Capacity management', description_nl: 'Der Cloud-Anbieter ueberwacht die Ressourcenauslastung und stellt ausreichende Kapazitaeten fuer den Cloud-Dienst sicher.', description: 'The cloud provider monitors resource utilization and ensures sufficient capacity for the cloud service.', category: 'OPS', subcategory: 'Regelbetrieb', level: 'Basis', iso_mapping: 'A.8.6', implementation_guidance: 'Monitoring-System mit Schwellenwerten und Alerting einrichten. Kapazitaetsplanung durchfuehren.', verification_guidance: 'Monitoring-Dashboards und Kapazitaetsberichte pruefen.', source_url: null },
  { control_number: 'OPS-04', title_nl: 'Schutz vor Schadsoftware', title: 'Protection against malware', description_nl: 'Massnahmen zum Schutz vor Schadsoftware sind implementiert und werden regelmaessig aktualisiert.', description: 'Measures for protection against malware are implemented and regularly updated.', category: 'OPS', subcategory: 'Regelbetrieb', level: 'Basis', iso_mapping: 'A.8.7', implementation_guidance: 'Anti-Malware auf allen Endpunkten und Servern. Regelmaessige Signatur-Updates.', verification_guidance: 'Anti-Malware-Abdeckung und Aktualitaet der Signaturen pruefen.', source_url: null },
  { control_number: 'OPS-05', title_nl: 'Datensicherung', title: 'Data backup', description_nl: 'Regelmaessige Datensicherungen des Cloud-Dienstes werden durchgefuehrt und auf Wiederherstellbarkeit getestet.', description: 'Regular data backups of the cloud service are performed and tested for restorability.', category: 'OPS', subcategory: 'Regelbetrieb', level: 'Basis', iso_mapping: 'A.8.13', implementation_guidance: 'Backup-Strategie mit RTO/RPO definieren. Regelmaessige Restore-Tests durchfuehren.', verification_guidance: 'Backup-Logs und Restore-Test-Protokolle pruefen.', source_url: null },
  { control_number: 'OPS-06', title_nl: 'Protokollierung und Ueberwachung', title: 'Logging and monitoring', description_nl: 'Sicherheitsrelevante Ereignisse werden protokolliert und ueberwacht. Protokolldaten werden vor unautorisiertem Zugriff geschuetzt.', description: 'Security-relevant events are logged and monitored. Log data is protected against unauthorized access.', category: 'OPS', subcategory: 'Regelbetrieb', level: 'Basis', iso_mapping: 'A.8.15', implementation_guidance: 'Zentrale Log-Aggregation (SIEM) einrichten. Aufbewahrungsfristen definieren.', verification_guidance: 'Log-Abdeckung, SIEM-Regeln und Aufbewahrungszeiten pruefen.', source_url: null },
  { control_number: 'OPS-07', title_nl: 'Schwachstellenmanagement', title: 'Vulnerability management', description_nl: 'Der Cloud-Anbieter identifiziert, bewertet und behandelt Schwachstellen in seinen IT-Systemen zeitnah.', description: 'The cloud provider identifies, assesses, and remediates vulnerabilities in its IT systems in a timely manner.', category: 'OPS', subcategory: 'Regelbetrieb', level: 'Basis', iso_mapping: 'A.8.8', implementation_guidance: 'Regelmaessige Vulnerability-Scans. Patch-Management-Prozess mit definierten SLAs.', verification_guidance: 'Scan-Berichte und Patch-Compliance-Raten pruefen.', source_url: null },

  // IDM — Identitaets- und Berechtigungsmanagement
  { control_number: 'IDM-01', title_nl: 'Identitaetsmanagement', title: 'Identity management', description_nl: 'Der Cloud-Anbieter hat einen Prozess fuer das Identitaetsmanagement etabliert, der den gesamten Lebenszyklus von Benutzeridentitaeten abdeckt.', description: 'The cloud provider has established an identity management process covering the full lifecycle of user identities.', category: 'IDM', subcategory: 'Identitaets- und Berechtigungsmanagement', level: 'Basis', iso_mapping: 'A.5.16', implementation_guidance: 'IAM-System mit automatisiertem Provisionierung/Deprovisionierung einrichten.', verification_guidance: 'IAM-Prozesse und Lifecycle-Management pruefen.', source_url: null },
  { control_number: 'IDM-02', title_nl: 'Berechtigungsmanagement', title: 'Authorization management', description_nl: 'Zugriffsberechtigungen werden nach dem Prinzip der geringsten Berechtigung vergeben und regelmaessig ueberprueft.', description: 'Access authorizations are granted according to the principle of least privilege and regularly reviewed.', category: 'IDM', subcategory: 'Identitaets- und Berechtigungsmanagement', level: 'Basis', iso_mapping: 'A.5.18', implementation_guidance: 'RBAC implementieren. Quartalsweise Rezertifizierungen durchfuehren.', verification_guidance: 'Berechtigungskonzept und Rezertifizierungsnachweise pruefen.', source_url: null },
  { control_number: 'IDM-03', title_nl: 'Administratorkonten', title: 'Administrator accounts', description_nl: 'Privilegierte Konten werden besonders geschuetzt. Fuer administrative Zugaenge wird eine starke Authentisierung eingesetzt.', description: 'Privileged accounts are specially protected. Strong authentication is used for administrative access.', category: 'IDM', subcategory: 'Identitaets- und Berechtigungsmanagement', level: 'Basis', iso_mapping: 'A.8.2', implementation_guidance: 'MFA fuer alle Admin-Konten. PAM-Loesung einsetzen. Admin-Zugaenge protokollieren.', verification_guidance: 'MFA-Konfiguration und PAM-Nutzung fuer Admin-Konten pruefen.', source_url: null },

  // CRY — Kryptographie
  { control_number: 'CRY-01', title_nl: 'Verschluesselungsrichtlinie', title: 'Encryption policy', description_nl: 'Der Cloud-Anbieter hat eine Richtlinie fuer den Einsatz kryptographischer Massnahmen definiert.', description: 'The cloud provider has defined a policy for the use of cryptographic measures.', category: 'CRY', subcategory: 'Kryptographie', level: 'Basis', iso_mapping: 'A.8.24', implementation_guidance: 'Kryptographierichtlinie mit zugelassenen Algorithmen und Schluessellaengen erstellen.', verification_guidance: 'Kryptographierichtlinie auf Uebereinstimmung mit BSI TR-02102 pruefen.', source_url: null },
  { control_number: 'CRY-02', title_nl: 'Verschluesselung bei Uebertragung', title: 'Encryption in transit', description_nl: 'Daten werden bei der Uebertragung durch geeignete kryptographische Verfahren geschuetzt.', description: 'Data is protected during transmission using appropriate cryptographic methods.', category: 'CRY', subcategory: 'Kryptographie', level: 'Basis', iso_mapping: 'A.8.24', implementation_guidance: 'TLS 1.2+ fuer alle Uebertragungen. Sichere Cipher-Suites konfigurieren.', verification_guidance: 'TLS-Konfiguration mit SSL-Scannern pruefen.', source_url: null },
  { control_number: 'CRY-03', title_nl: 'Verschluesselung bei Speicherung', title: 'Encryption at rest', description_nl: 'Gespeicherte Daten werden gemaess Klassifizierung durch angemessene Verschluesselung geschuetzt.', description: 'Stored data is protected with appropriate encryption according to classification.', category: 'CRY', subcategory: 'Kryptographie', level: 'Basis', iso_mapping: 'A.8.24', implementation_guidance: 'Festplattenverschluesselung (AES-256) und Datenbankverschluesselung einsetzen.', verification_guidance: 'Verschluesselungskonfiguration fuer Storage und Datenbanken pruefen.', source_url: null },
  { control_number: 'CRY-04', title_nl: 'Schluesselmanagement', title: 'Key management', description_nl: 'Der Cloud-Anbieter hat einen Prozess fuer das Management kryptographischer Schluessel implementiert.', description: 'The cloud provider has implemented a process for managing cryptographic keys.', category: 'CRY', subcategory: 'Kryptographie', level: 'Basis', iso_mapping: 'A.8.24', implementation_guidance: 'KMS einsetzen. Schluesselrotation, -archivierung und -vernichtung regeln.', verification_guidance: 'KMS-Konfiguration und Schluessel-Lifecycle-Nachweise pruefen.', source_url: null },

  // COS — Kommunikationssicherheit
  { control_number: 'COS-01', title_nl: 'Netzwerksicherheit', title: 'Network security', description_nl: 'Der Cloud-Anbieter schuetzt seine Netzwerke durch Segmentierung, Firewalls und Ueberwachung.', description: 'The cloud provider protects its networks through segmentation, firewalls, and monitoring.', category: 'COS', subcategory: 'Kommunikationssicherheit', level: 'Basis', iso_mapping: 'A.8.20', implementation_guidance: 'Netzsegmentierung, IDS/IPS und Firewall-Regeln implementieren.', verification_guidance: 'Netzwerk-Topologie und Firewall-Regeln pruefen.', source_url: null },
  { control_number: 'COS-02', title_nl: 'Sichere Netzwerkdienste', title: 'Secure network services', description_nl: 'Netzwerkdienste werden sicher konfiguriert und ueberwacht.', description: 'Network services are securely configured and monitored.', category: 'COS', subcategory: 'Kommunikationssicherheit', level: 'Basis', iso_mapping: 'A.8.21', implementation_guidance: 'Haertung aller Netzwerkdienste. Nicht benoetigte Dienste deaktivieren.', verification_guidance: 'Netzwerkdienste-Inventar und Haertungskonfiguration pruefen.', source_url: null },

  // PI — Portabilitaet und Interoperabilitaet
  { control_number: 'PI-01', title_nl: 'Datenportabilitaet', title: 'Data portability', description_nl: 'Der Cloud-Anbieter stellt sicher, dass Kundendaten in einem gaengigen Format exportierbar sind und ein geordneter Anbieterwechsel moeglich ist.', description: 'The cloud provider ensures that customer data can be exported in a common format and that an orderly provider change is possible.', category: 'PI', subcategory: 'Portabilitaet und Interoperabilitaet', level: 'Basis', iso_mapping: null, implementation_guidance: 'Datenexport-API und standardisierte Formate bereitstellen. Migrationsplan dokumentieren.', verification_guidance: 'Datenexport-Faehigkeit und Migrationsplan testen und pruefen.', source_url: null },

  // DEV — Beschaffung, Entwicklung und Aenderung
  { control_number: 'DEV-01', title_nl: 'Sichere Entwicklung', title: 'Secure development', description_nl: 'Der Cloud-Anbieter hat einen sicheren Softwareentwicklungsprozess implementiert (Secure SDLC).', description: 'The cloud provider has implemented a secure software development process (Secure SDLC).', category: 'DEV', subcategory: 'Beschaffung, Entwicklung und Aenderung', level: 'Basis', iso_mapping: 'A.8.25', implementation_guidance: 'Secure SDLC mit Code-Reviews, SAST, DAST und Penetrationstests einrichten.', verification_guidance: 'SDLC-Prozess und Security-Testing-Nachweise pruefen.', source_url: null },
  { control_number: 'DEV-02', title_nl: 'Trennung von Entwicklungs-, Test- und Produktionsumgebungen', title: 'Separation of development, test, and production environments', description_nl: 'Entwicklungs-, Test- und Produktionsumgebungen sind voneinander getrennt.', description: 'Development, test, and production environments are separated from each other.', category: 'DEV', subcategory: 'Beschaffung, Entwicklung und Aenderung', level: 'Basis', iso_mapping: 'A.8.31', implementation_guidance: 'Strikte Trennung der Umgebungen. Keine Produktionsdaten in Test/Entwicklung.', verification_guidance: 'Umgebungstrennung und Datenmaskierung pruefen.', source_url: null },

  // SSO — Steuerung von Dienstleistern
  { control_number: 'SSO-01', title_nl: 'Lieferantenmanagement', title: 'Supplier management', description_nl: 'Der Cloud-Anbieter hat einen Prozess zur Bewertung und Steuerung seiner Dienstleister und Unterauftragnehmer.', description: 'The cloud provider has a process for evaluating and managing its service providers and subcontractors.', category: 'SSO', subcategory: 'Steuerung von Dienstleistern', level: 'Basis', iso_mapping: 'A.5.19', implementation_guidance: 'Lieferantenbewertung mit IS-Kriterien durchfuehren. Vertraege mit IS-Klauseln.', verification_guidance: 'Lieferantenregister und Vertragspruefung durchfuehren.', source_url: null },
  { control_number: 'SSO-02', title_nl: 'Ueberwachung der Dienstleister', title: 'Monitoring of service providers', description_nl: 'Die Einhaltung der vertraglichen Sicherheitsanforderungen durch Dienstleister wird regelmaessig ueberprueft.', description: 'Compliance of service providers with contractual security requirements is regularly monitored.', category: 'SSO', subcategory: 'Steuerung von Dienstleistern', level: 'Basis', iso_mapping: 'A.5.22', implementation_guidance: 'Regelmaessige Audits und Leistungsueberpruefungen der Dienstleister.', verification_guidance: 'Audit-Berichte und Leistungskennzahlen pruefen.', source_url: null },

  // SIM — Umgang mit Sicherheitsvorfaellen
  { control_number: 'SIM-01', title_nl: 'Incident-Management-Prozess', title: 'Incident management process', description_nl: 'Der Cloud-Anbieter hat einen dokumentierten Prozess fuer das Management von Sicherheitsvorfaellen.', description: 'The cloud provider has a documented process for managing security incidents.', category: 'SIM', subcategory: 'Umgang mit Sicherheitsvorfaellen', level: 'Basis', iso_mapping: 'A.5.24', implementation_guidance: 'Incident-Response-Plan mit Eskalationsstufen und Benachrichtigungspflichten erstellen.', verification_guidance: 'Incident-Response-Plan und Uebungsszenarien pruefen.', source_url: null },
  { control_number: 'SIM-02', title_nl: 'Meldung von Sicherheitsvorfaellen', title: 'Reporting of security incidents', description_nl: 'Sicherheitsvorfaelle werden zeitnah an betroffene Kunden und zustaendige Behoerden gemeldet.', description: 'Security incidents are promptly reported to affected customers and relevant authorities.', category: 'SIM', subcategory: 'Umgang mit Sicherheitsvorfaellen', level: 'Basis', iso_mapping: 'A.5.26', implementation_guidance: 'Benachrichtigungsprozess mit definierten Zeitfenstern und Kommunikationsvorlagen.', verification_guidance: 'Meldeprozess und Einhaltung der Meldefristen pruefen.', source_url: null },

  // BCM — Betriebskontinuitaet
  { control_number: 'BCM-01', title_nl: 'Business-Continuity-Management', title: 'Business continuity management', description_nl: 'Der Cloud-Anbieter hat ein Business-Continuity-Management implementiert, das die Verfuegbarkeit des Cloud-Dienstes sicherstellt.', description: 'The cloud provider has implemented business continuity management that ensures the availability of the cloud service.', category: 'BCM', subcategory: 'Betriebskontinuitaet', level: 'Basis', iso_mapping: 'A.5.30', implementation_guidance: 'BCP und DRP erstellen. RTO/RPO definieren. Regelmaessige Tests durchfuehren.', verification_guidance: 'BCP/DRP-Dokumente und Test-Protokolle pruefen.', source_url: null },
  { control_number: 'BCM-02', title_nl: 'Redundanz und Wiederherstellung', title: 'Redundancy and recovery', description_nl: 'Kritische Komponenten des Cloud-Dienstes sind redundant ausgelegt. Wiederherstellungsverfahren sind dokumentiert und getestet.', description: 'Critical components of the cloud service are designed redundantly. Recovery procedures are documented and tested.', category: 'BCM', subcategory: 'Betriebskontinuitaet', level: 'Basis', iso_mapping: 'A.8.14', implementation_guidance: 'Geo-redundante Infrastruktur. Automatisiertes Failover. Regelmaessige DR-Tests.', verification_guidance: 'Redundanzkonfiguration und DR-Test-Ergebnisse pruefen.', source_url: null },

  // COM — Compliance
  { control_number: 'COM-01', title_nl: 'Identifikation rechtlicher Anforderungen', title: 'Identification of legal requirements', description_nl: 'Der Cloud-Anbieter identifiziert und dokumentiert alle fuer den Cloud-Dienst relevanten gesetzlichen und regulatorischen Anforderungen.', description: 'The cloud provider identifies and documents all legal and regulatory requirements relevant to the cloud service.', category: 'COM', subcategory: 'Compliance', level: 'Basis', iso_mapping: 'A.5.31', implementation_guidance: 'Rechtskataster fuer Cloud-relevante Vorschriften erstellen und pflegen.', verification_guidance: 'Rechtskataster auf Vollstaendigkeit und Aktualitaet pruefen.', source_url: null },
  { control_number: 'COM-02', title_nl: 'Datenschutzanforderungen', title: 'Data protection requirements', description_nl: 'Der Cloud-Anbieter stellt die Einhaltung datenschutzrechtlicher Anforderungen sicher, insbesondere der DSGVO.', description: 'The cloud provider ensures compliance with data protection requirements, particularly the GDPR.', category: 'COM', subcategory: 'Compliance', level: 'Basis', iso_mapping: 'A.5.34', implementation_guidance: 'DSFA durchfuehren. Auftragsverarbeitungsvertrag (AVV) bereitstellen. TOM dokumentieren.', verification_guidance: 'AVV, DSFA und TOM-Dokumentation pruefen.', source_url: null },

  // INQ — Umgang mit Ermittlungsanfragen
  { control_number: 'INQ-01', title_nl: 'Umgang mit Ermittlungsanfragen', title: 'Handling of investigation requests', description_nl: 'Der Cloud-Anbieter hat einen Prozess fuer den Umgang mit behoerdlichen Ermittlungsanfragen und Herausgabeverlangen.', description: 'The cloud provider has a process for handling government investigation requests and data disclosure demands.', category: 'INQ', subcategory: 'Umgang mit Ermittlungsanfragen', level: 'Basis', iso_mapping: 'A.5.31', implementation_guidance: 'Prozess mit juristischer Pruefung und Kundenbenachrichtigung definieren.', verification_guidance: 'Prozessdokumentation und Schulungsnachweise pruefen.', source_url: null },

  // PSS — Produktsicherheit
  { control_number: 'PSS-01', title_nl: 'Sicherheitseigenschaften des Cloud-Dienstes', title: 'Security properties of the cloud service', description_nl: 'Die Sicherheitseigenschaften und -funktionen des Cloud-Dienstes sind dokumentiert und den Kunden zugaenglich.', description: 'The security properties and functions of the cloud service are documented and accessible to customers.', category: 'PSS', subcategory: 'Produktsicherheit', level: 'Basis', iso_mapping: null, implementation_guidance: 'Security-Whitepaper und Datenschutzhinweise fuer Kunden bereitstellen.', verification_guidance: 'Sicherheitsdokumentation auf Vollstaendigkeit und Zugaenglichkeit pruefen.', source_url: null },
  { control_number: 'PSS-02', title_nl: 'Mandantentrennung', title: 'Tenant separation', description_nl: 'Der Cloud-Anbieter stellt die logische und physische Trennung der Kundendaten sicher.', description: 'The cloud provider ensures logical and physical separation of customer data.', category: 'PSS', subcategory: 'Produktsicherheit', level: 'Basis', iso_mapping: 'A.8.22', implementation_guidance: 'Mandantenisolierung durch Netzwerk-Segmentierung, separate DB-Schemata oder verschluesselte Trennung.', verification_guidance: 'Mandantentrennungsmechanismen und Penetrationstests pruefen.', source_url: null },
];

const output = {
  framework: {
    id: 'bsi-c5',
    name: 'Cloud Computing Compliance Criteria Catalogue',
    name_nl: 'Cloud Computing Compliance Criteria Catalogue (C5)',
    issuing_body: 'Bundesamt fuer Sicherheit in der Informationstechnik (BSI)',
    version: '2020',
    effective_date: '2020-01-01',
    scope: 'Cloud security standard for cloud service providers operating in Germany',
    scope_sectors: ['cloud', 'digital_infrastructure', 'all'],
    structure_description: '17 control domains covering organizational, technical, and operational security for cloud services. Used as audit standard for cloud providers.',
    source_url: 'https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Informationen-und-Empfehlungen/Empfehlungen-nach-Angriffszielen/Cloud-Computing/Kriterienkatalog-C5/kriterienkatalog-c5_node.html',
    license: 'Public document',
    language: 'de+en',
  },
  controls,
  metadata: {
    ingested_at: new Date().toISOString(),
    total_controls: controls.length,
    notes: [
      '17 control domains: OIS, SP, HR, AM, PS, OPS, IDM, CRY, COS, PI, DEV, SSO, SIM, BCM, COM, INQ, PSS.',
      'C5 is the primary cloud audit standard in Germany, equivalent to SOC 2 for German market.',
    ],
  },
};

mkdirSync(DATA_DIR, { recursive: true });
writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
console.log(`BSI C5: ${controls.length} controls written to ${OUTPUT_FILE}`);
