// scripts/ingest-kritis-extended.ts
// Extended KRITIS requirements from IT-Sicherheitsgesetz 2.0, BSI-KritisV,
// and related regulations including SzA (Systeme zur Angriffserkennung)
// and extended reporting obligations.

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'bsi-kritis-extended.json');

const controls = [
  // SzA — Systeme zur Angriffserkennung (§8a Abs. 1a BSI-Gesetz)
  { control_number: 'KRITIS-SZA-01', title_nl: 'Einsatz von Systemen zur Angriffserkennung (SzA)', title: 'Deployment of attack detection systems', description_nl: 'KRITIS-Betreiber MUESSEN ab dem 01.05.2023 Systeme zur Angriffserkennung (SzA) einsetzen. Die SzA MUESSEN geeignet sein, Bedrohungen und Angriffe auf informationstechnische Systeme kontinuierlich und automatisch zu erkennen.', description: 'KRITIS operators MUST deploy attack detection systems (SzA) from 01.05.2023. The SzA MUST be suitable for continuously and automatically detecting threats and attacks on IT systems.', category: 'Angriffserkennung', subcategory: 'SzA', level: 'Verpflichtend', iso_mapping: 'A.8.16', implementation_guidance: 'SIEM/SOC implementieren. Netzwerk-IDS. Endpunkt-EDR. Protokollierung.', verification_guidance: 'SzA-Einsatz und Abdeckung gemaess BSI-Orientierungshilfe pruefen.', source_url: 'https://www.bsi.bund.de/DE/Themen/KRITIS-und-regulierte-Unternehmen/Kritische-Infrastrukturen/SzA/sza_node.html' },
  { control_number: 'KRITIS-SZA-02', title_nl: 'Protokollierung (SzA-Bereich Logging)', title: 'Logging (SzA area)', description_nl: 'Sicherheitsrelevante Ereignisse MUESSEN protokolliert werden. Protokolldaten MUESSEN zentral gesammelt und fuer mindestens 18 Monate aufbewahrt werden.', description: 'Security-relevant events MUST be logged. Log data MUST be centrally collected and retained for at least 18 months.', category: 'Angriffserkennung', subcategory: 'Protokollierung', level: 'Verpflichtend', iso_mapping: 'A.8.15', implementation_guidance: 'Zentrale Log-Sammlung. 18 Monate Aufbewahrung. Manipulationssicherheit.', verification_guidance: 'Log-Abdeckung und Aufbewahrungsdauer pruefen.', source_url: null },
  { control_number: 'KRITIS-SZA-03', title_nl: 'Detektion (SzA-Bereich Erkennung)', title: 'Detection (SzA area)', description_nl: 'Es MUESSEN Detektionsmechanismen implementiert werden, die bekannte Angriffsmuster (signaturbasiert) und unbekannte Anomalien (verhaltensbasiert) erkennen koennen.', description: 'Detection mechanisms MUST be implemented that can recognize known attack patterns (signature-based) and unknown anomalies (behavior-based).', category: 'Angriffserkennung', subcategory: 'Detektion', level: 'Verpflichtend', iso_mapping: 'A.8.16', implementation_guidance: 'Signaturbasierte und verhaltensbasierte Erkennung. IOC-Feeds. ML-gestuetzte Anomalieerkennung.', verification_guidance: 'Detektionsmechanismen und Use-Case-Abdeckung pruefen.', source_url: null },
  { control_number: 'KRITIS-SZA-04', title_nl: 'Reaktion (SzA-Bereich Reaktionsfaehigkeit)', title: 'Response (SzA area)', description_nl: 'Es MUESSEN Prozesse fuer die Reaktion auf erkannte Angriffe vorhanden sein. Die Reaktionszeit MUSS dem Schutzbedarf angemessen sein. Eskalationswege MUESSEN definiert sein.', description: 'Processes for responding to detected attacks MUST exist. Response time MUST be appropriate to the protection needs. Escalation paths MUST be defined.', category: 'Angriffserkennung', subcategory: 'Reaktion', level: 'Verpflichtend', iso_mapping: 'A.5.26', implementation_guidance: 'Incident-Response-Prozess. Eskalationsmatrix. SLA fuer Reaktionszeiten.', verification_guidance: 'Reaktionsprozess und Reaktionszeiten pruefen.', source_url: null },

  // Erweiterte Meldepflichten
  { control_number: 'KRITIS-MELD-01', title_nl: 'Erstmeldung erheblicher IT-Stoerungen', title: 'Initial report of significant IT disruptions', description_nl: 'KRITIS-Betreiber MUESSEN erhebliche IT-Stoerungen unverzueglich an das BSI melden. Die Erstmeldung MUSS innerhalb von 24 Stunden nach Feststellung erfolgen.', description: 'KRITIS operators MUST immediately report significant IT disruptions to BSI. The initial report MUST be made within 24 hours of detection.', category: 'Meldepflichten', subcategory: 'Erstmeldung', level: 'Verpflichtend', iso_mapping: 'A.5.26', implementation_guidance: 'Meldeprozess an BSI. 24h-Frist. Vorbereitete Meldevorlagen. Erreichbarkeit sicherstellen.', verification_guidance: 'Meldeprozess und Frist-Einhaltung pruefen.', source_url: null },
  { control_number: 'KRITIS-MELD-02', title_nl: 'Folgemeldung mit detaillierten Informationen', title: 'Follow-up report with detailed information', description_nl: 'Innerhalb von 72 Stunden nach der Erstmeldung MUSS eine Folgemeldung an das BSI erfolgen, die detaillierte Informationen ueber Ursache, Auswirkung und ergriffene Massnahmen enthaelt.', description: 'Within 72 hours of the initial report, a follow-up report to BSI MUST be made containing detailed information on cause, impact, and measures taken.', category: 'Meldepflichten', subcategory: 'Folgemeldung', level: 'Verpflichtend', iso_mapping: 'A.5.26', implementation_guidance: 'Folgemeldungs-Template. Ursachenanalyse innerhalb 72h starten. Massnahmen dokumentieren.', verification_guidance: 'Folgemeldungs-Prozess und Qualitaet pruefen.', source_url: null },
  { control_number: 'KRITIS-MELD-03', title_nl: 'Kontaktstelle beim BSI', title: 'Contact point at BSI', description_nl: 'KRITIS-Betreiber MUESSEN eine Kontaktstelle benennen, die vom BSI rund um die Uhr erreichbar ist. Die Kontaktdaten MUESSEN aktuell gehalten und dem BSI mitgeteilt werden.', description: 'KRITIS operators MUST designate a contact point reachable by BSI around the clock. Contact details MUST be kept current and communicated to BSI.', category: 'Meldepflichten', subcategory: 'Kontaktstelle', level: 'Verpflichtend', iso_mapping: 'A.5.5', implementation_guidance: '24/7-erreichbare Kontaktstelle. Kontaktdaten beim BSI aktuell halten.', verification_guidance: 'Erreichbarkeit und Aktualitaet der Kontaktstelle pruefen.', source_url: null },

  // Registrierung und Nachweispflicht
  { control_number: 'KRITIS-REG-01', title_nl: 'Registrierung als KRITIS-Betreiber', title: 'Registration as KRITIS operator', description_nl: 'Betreiber kritischer Infrastrukturen MUESSEN sich beim BSI registrieren und ihre Kontaktdaten aktuell halten. Die Registrierung MUSS innerhalb von 6 Monaten nach Erreichen der Schwellenwerte erfolgen.', description: 'Operators of critical infrastructure MUST register with BSI and keep their contact data current. Registration MUST occur within 6 months of reaching the thresholds.', category: 'Registrierung', subcategory: 'BSI-Registrierung', level: 'Verpflichtend', iso_mapping: 'A.5.31', implementation_guidance: 'Schwellenwert-Pruefung. Registrierung beim BSI. Kontaktdaten pflegen.', verification_guidance: 'Registrierungsstatus und Kontaktdaten-Aktualitaet pruefen.', source_url: null },
  { control_number: 'KRITIS-REG-02', title_nl: 'Nachweis angemessener Sicherheitsvorkehrungen', title: 'Evidence of appropriate security precautions', description_nl: 'KRITIS-Betreiber MUESSEN dem BSI alle zwei Jahre nachweisen, dass angemessene organisatorische und technische Vorkehrungen getroffen wurden. Der Nachweis kann durch Audit, Pruefung oder Zertifizierung erbracht werden.', description: 'KRITIS operators MUST demonstrate to BSI every two years that appropriate organizational and technical precautions have been taken. Evidence can be provided through audit, examination, or certification.', category: 'Registrierung', subcategory: 'Nachweispflicht', level: 'Verpflichtend', iso_mapping: 'A.5.35', implementation_guidance: 'Zweijählicher Nachweis. Audit-Planung. Maengelbehandlung dokumentieren.', verification_guidance: 'Nachweis-Erbringung und Maengelbehandlung pruefen.', source_url: null },

  // IT-SiG 2.0 Erweiterungen
  { control_number: 'KRITIS-UIBI-01', title_nl: 'Unternehmen im besonderen oeffentlichen Interesse (UBI)', title: 'Companies of particular public interest', description_nl: 'Unternehmen im besonderen oeffentlichen Interesse (UBI, §2 Abs. 14 BSI-Gesetz) MUESSEN dem BSI eine Selbsterklaerung vorlegen und Stoerungen melden. UBI umfasst Ruestungsunternehmen, grosse Unternehmen und Gefahrstoffbetreiber.', description: 'Companies of particular public interest (UBI) MUST submit a self-declaration to BSI and report disruptions. UBI includes defense companies, large enterprises, and hazardous substance operators.', category: 'UBI', subcategory: 'Selbsterklaerung', level: 'Verpflichtend', iso_mapping: 'A.5.31', implementation_guidance: 'UBI-Status pruefen. Selbsterklaerung erstellen. Meldepflicht implementieren.', verification_guidance: 'UBI-Status und Selbsterklaerung pruefen.', source_url: null },
  { control_number: 'KRITIS-LIEFERKETTE-01', title_nl: 'Sicherheitsanforderungen an kritische Komponenten', title: 'Security requirements for critical components', description_nl: 'Der Einsatz kritischer Komponenten (§9b BSI-Gesetz) MUSS dem BMI angezeigt werden. Das BMI kann den Einsatz untersagen. Hersteller MUESSEN Vertrauenswuerdigkeitserklaerungen abgeben.', description: 'The use of critical components (section 9b BSI Act) MUST be notified to the BMI. The BMI can prohibit deployment. Manufacturers MUST provide trustworthiness declarations.', category: 'Lieferkette', subcategory: 'Kritische Komponenten', level: 'Verpflichtend', iso_mapping: 'A.5.21', implementation_guidance: 'Kritische Komponenten identifizieren. BMI-Anzeige. Herstellererklaerungen einholen.', verification_guidance: 'Identifizierung kritischer Komponenten und BMI-Anzeige pruefen.', source_url: null },
  { control_number: 'KRITIS-LIEFERKETTE-02', title_nl: 'Zertifizierung von IT-Produkten', title: 'Certification of IT products', description_nl: 'KRITIS-Betreiber SOLLTEN bevorzugt IT-Produkte einsetzen, die nach einem anerkannten Schema (Common Criteria, BSI-Zertifizierung) zertifiziert sind.', description: 'KRITIS operators SHOULD preferably use IT products certified according to a recognized scheme (Common Criteria, BSI certification).', category: 'Lieferkette', subcategory: 'Produktzertifizierung', level: 'Empfohlen', iso_mapping: 'A.5.21', implementation_guidance: 'Zertifizierte Produkte bevorzugen. BSI-Empfehlungen beachten.', verification_guidance: 'Einsatz zertifizierter IT-Produkte pruefen.', source_url: null },
];

const output = {
  framework: {
    id: 'bsi-kritis-extended',
    name: 'KRITIS Extended Requirements (SzA, IT-SiG 2.0, UBI)',
    name_nl: 'KRITIS Erweiterte Anforderungen (SzA, IT-SiG 2.0, UBI)',
    issuing_body: 'Bundesamt fuer Sicherheit in der Informationstechnik (BSI)',
    version: 'IT-SiG 2.0 (2023)',
    effective_date: '2023-05-01',
    scope: 'Extended KRITIS requirements including mandatory attack detection systems (SzA), enhanced reporting obligations, UBI requirements, and critical component supply chain controls',
    scope_sectors: ['energy', 'healthcare', 'transport', 'water', 'finance', 'telecom', 'digital_infrastructure'],
    structure_description: 'Covers SzA requirements (logging, detection, response), extended reporting obligations (initial/follow-up/contact point), registration and evidence requirements, UBI self-declarations, and critical component supply chain controls.',
    source_url: 'https://www.bsi.bund.de/DE/Themen/KRITIS-und-regulierte-Unternehmen/Kritische-Infrastrukturen/kritis_node.html',
    license: 'Federal legislation',
    language: 'de+en',
  },
  controls,
  metadata: { ingested_at: new Date().toISOString(), total_controls: controls.length },
};

mkdirSync(DATA_DIR, { recursive: true });
writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
console.log(`KRITIS Extended: ${controls.length} controls written to ${OUTPUT_FILE}`);
