// scripts/ingest-gematik-extended.ts
// Extended healthcare IT security — deeper gematik TI requirements,
// KBV IT-Sicherheitsrichtlinie, DKG/B3S hospital requirements,
// and DiGA (Digitale Gesundheitsanwendungen) security.

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'gematik-extended.json');

const controls = [
  // TI — Extended Telematikinfrastruktur
  { control_number: 'TI-EXT-01', title_nl: 'ePA-Datensicherheit (Elektronische Patientenakte)', title: 'ePA data security (electronic patient record)', description_nl: 'Die elektronische Patientenakte (ePA) MUSS durch Ende-zu-Ende-Verschluesselung geschuetzt werden. Zugriffsberechtigungen MUESSEN durch den Versicherten steuerbar sein.', description: 'The electronic patient record (ePA) MUST be protected by end-to-end encryption. Access authorizations MUST be controllable by the insured person.', category: 'Telematikinfrastruktur', subcategory: 'ePA', level: 'Verpflichtend', iso_mapping: 'A.8.24', implementation_guidance: 'E2E-Verschluesselung fuer ePA. Patientengesteuerte Zugriffsrechte. Audit-Trail.', verification_guidance: 'ePA-Verschluesselung und Zugriffskontrolle pruefen.', source_url: null },
  { control_number: 'TI-EXT-02', title_nl: 'E-Rezept-Sicherheit', title: 'E-prescription security', description_nl: 'Das E-Rezept-System MUSS die Authentizitaet und Integritaet von Rezepten sicherstellen. Qualifizierte elektronische Signaturen oder Siegel MUESSEN verwendet werden.', description: 'The e-prescription system MUST ensure the authenticity and integrity of prescriptions. Qualified electronic signatures or seals MUST be used.', category: 'Telematikinfrastruktur', subcategory: 'E-Rezept', level: 'Verpflichtend', iso_mapping: 'A.8.24', implementation_guidance: 'QES oder QESiegel fuer E-Rezepte. Integritaetspruefung. Manipulationserkennung.', verification_guidance: 'E-Rezept-Signatur und Integritaet pruefen.', source_url: null },
  { control_number: 'TI-EXT-03', title_nl: 'Konnektormanagement', title: 'Connector management', description_nl: 'TI-Konnektoren MUESSEN zentral verwaltet und ueberwacht werden. Firmware-Updates MUESSEN zeitnah eingespielt werden. End-of-Life-Konnektoren MUESSEN ersetzt werden.', description: 'TI connectors MUST be centrally managed and monitored. Firmware updates MUST be applied promptly. End-of-life connectors MUST be replaced.', category: 'Telematikinfrastruktur', subcategory: 'Konnektoren', level: 'Verpflichtend', iso_mapping: 'A.8.8', implementation_guidance: 'Zentrales Konnektor-Management. Firmware-Monitoring. EOL-Planung.', verification_guidance: 'Konnektor-Management und Firmware-Stand pruefen.', source_url: null },
  { control_number: 'TI-EXT-04', title_nl: 'Authentisierung in der TI (SMC-B, eHBA)', title: 'Authentication in the TI (SMC-B, eHBA)', description_nl: 'Leistungserbringer MUESSEN sich in der TI mit einer SMC-B (Institutionskarte) oder einem eHBA (Heilberufsausweis) authentisieren. Die Karten MUESSEN sicher aufbewahrt werden.', description: 'Service providers MUST authenticate in the TI with an SMC-B (institution card) or eHBA (health professional card). Cards MUST be stored securely.', category: 'Telematikinfrastruktur', subcategory: 'Authentisierung', level: 'Verpflichtend', iso_mapping: 'A.8.5', implementation_guidance: 'SMC-B und eHBA ordnungsgemaess einsetzen. Sichere Aufbewahrung. PIN-Schutz.', verification_guidance: 'Karten-basierte Authentisierung und Kartenaufbewahrung pruefen.', source_url: null },

  // KBV — Extended IT-Sicherheitsrichtlinie
  { control_number: 'KBV-EXT-01', title_nl: 'Praxisnetzwerk-Segmentierung', title: 'Practice network segmentation', description_nl: 'Das Praxisnetzwerk MUSS vom Internet und von Gastnetzen getrennt werden. Medizingeraete SOLLTEN in einem separaten Netzwerksegment betrieben werden.', description: 'The practice network MUST be separated from the internet and guest networks. Medical devices SHOULD be operated in a separate network segment.', category: 'KBV IT-Sicherheitsrichtlinie', subcategory: 'Netzwerksicherheit', level: 'Verpflichtend', iso_mapping: 'A.8.22', implementation_guidance: 'Praxis-Firewall. Separates VLAN fuer Medizingeraete. Gaeste-WLAN isoliert.', verification_guidance: 'Praxis-Netzwerksegmentierung pruefen.', source_url: null },
  { control_number: 'KBV-EXT-02', title_nl: 'Datensicherung in der Arztpraxis', title: 'Data backup in the medical practice', description_nl: 'Praxisdaten MUESSEN taeglich gesichert werden. Backups MUESSEN verschluesselt und extern oder offline aufbewahrt werden. Regelmaessige Restore-Tests MUESSEN durchgefuehrt werden.', description: 'Practice data MUST be backed up daily. Backups MUST be stored encrypted and off-site or offline. Regular restore tests MUST be performed.', category: 'KBV IT-Sicherheitsrichtlinie', subcategory: 'Datensicherung', level: 'Verpflichtend', iso_mapping: 'A.8.13', implementation_guidance: 'Taegliche Backups. Verschluesselung. Externer Standort. Quartalsweiser Restore-Test.', verification_guidance: 'Backup-Prozess und Restore-Tests pruefen.', source_url: null },
  { control_number: 'KBV-EXT-03', title_nl: 'Zugangskontrolle zu Patientendaten in der Praxis', title: 'Access control to patient data in the practice', description_nl: 'Der Zugang zu Patientendaten MUSS durch individuelle Benutzerkonten und Passwortschutz gesichert werden. Gemeinsam genutzte Konten DUERFEN NICHT verwendet werden.', description: 'Access to patient data MUST be secured by individual user accounts and password protection. Shared accounts MUST NOT be used.', category: 'KBV IT-Sicherheitsrichtlinie', subcategory: 'Zugriffskontrolle', level: 'Verpflichtend', iso_mapping: 'A.8.5', implementation_guidance: 'Individuelle Benutzerkonten. Keine Sammelkonten. Bildschirmsperre. Passwortrichtlinie.', verification_guidance: 'Benutzerkontenverwaltung und Passwortrichtlinie pruefen.', source_url: null },
  { control_number: 'KBV-EXT-04', title_nl: 'Verschluesselung mobiler Praxis-Geraete', title: 'Encryption of mobile practice devices', description_nl: 'Mobile Geraete, die Patientendaten verarbeiten (Laptops, Tablets), MUESSEN verschluesselt werden. Bei Verlust MUSS eine Fernloeschung moeglich sein.', description: 'Mobile devices that process patient data (laptops, tablets) MUST be encrypted. In case of loss, remote wiping MUST be possible.', category: 'KBV IT-Sicherheitsrichtlinie', subcategory: 'Mobile Sicherheit', level: 'Verpflichtend', iso_mapping: 'A.8.24', implementation_guidance: 'Festplattenverschluesselung. MDM mit Remote-Wipe. Geraete-Inventar.', verification_guidance: 'Verschluesselung und Remote-Wipe-Faehigkeit pruefen.', source_url: null },

  // DKG — Extended Hospital IT Security (§75c SGB V)
  { control_number: 'DKG-EXT-01', title_nl: 'Schutz der Krankenhaus-IT nach §75c SGB V', title: 'Protection of hospital IT per section 75c SGB V', description_nl: 'Krankenhaeuser MUESSEN ab dem 01.01.2022 angemessene organisatorische und technische Vorkehrungen zur IT-Sicherheit treffen. Der branchenspezifische Sicherheitsstandard (B3S) SOLLTE als Grundlage dienen.', description: 'Hospitals MUST take appropriate organizational and technical IT security precautions from 01.01.2022. The sector-specific security standard (B3S) SHOULD serve as the basis.', category: 'DKG Krankenhaus-IT', subcategory: 'IT-Sicherheit', level: 'Verpflichtend', iso_mapping: 'A.5.1', implementation_guidance: 'IT-Sicherheitskonzept nach B3S Krankenhaus. ISMS etablieren.', verification_guidance: 'IT-Sicherheitskonzept und B3S-Umsetzung pruefen.', source_url: null },
  { control_number: 'DKG-EXT-02', title_nl: 'Absicherung des Krankenhausinformationssystems (KIS)', title: 'Securing the hospital information system (HIS)', description_nl: 'Das KIS MUSS besonders abgesichert werden. Zugriffskontrolle MUSS rollenbasiert sein. Patientendaten MUESSEN verschluesselt gespeichert werden. Das KIS MUSS hochverfuegbar sein.', description: 'The HIS MUST be specially secured. Access control MUST be role-based. Patient data MUST be stored encrypted. The HIS MUST be highly available.', category: 'DKG Krankenhaus-IT', subcategory: 'KIS', level: 'Verpflichtend', iso_mapping: 'A.8.9', implementation_guidance: 'RBAC fuer KIS. Datenbank-Verschluesselung. Hochverfuegbarkeit (Cluster/Failover).', verification_guidance: 'KIS-Sicherheitskonfiguration und Verfuegbarkeit pruefen.', source_url: null },
  { control_number: 'DKG-EXT-03', title_nl: 'Absicherung von PACS und medizinischer Bildgebung', title: 'Securing PACS and medical imaging', description_nl: 'PACS (Picture Archiving and Communication System) MUSS in einem separaten Netzwerksegment betrieben werden. DICOM-Kommunikation SOLLTE verschluesselt werden. Zugriffsprotokollierung MUSS aktiviert sein.', description: 'PACS (Picture Archiving and Communication System) MUST be operated in a separate network segment. DICOM communication SHOULD be encrypted. Access logging MUST be activated.', category: 'DKG Krankenhaus-IT', subcategory: 'PACS', level: 'Verpflichtend', iso_mapping: 'A.8.22', implementation_guidance: 'PACS-VLAN. DICOM-TLS. Zugriffs-Audit-Trail. Integritaetspruefung.', verification_guidance: 'PACS-Netzwerksegmentierung und DICOM-Sicherheit pruefen.', source_url: null },

  // DiGA — Digitale Gesundheitsanwendungen
  { control_number: 'DIGA-01', title_nl: 'Datenschutzanforderungen an DiGA (§4 DiGAV)', title: 'Data protection requirements for DiGA', description_nl: 'Digitale Gesundheitsanwendungen MUESSEN die Datenschutzanforderungen der DiGAV erfuellen. Personenbezogene Daten DUERFEN nur in Deutschland, EU/EWR oder in Laendern mit Angemessenheitsbeschluss verarbeitet werden.', description: 'Digital health applications MUST meet the data protection requirements of DiGAV. Personal data MAY only be processed in Germany, EU/EEA, or countries with an adequacy decision.', category: 'DiGA', subcategory: 'Datenschutz', level: 'Verpflichtend', iso_mapping: 'A.5.34', implementation_guidance: 'Datenschutz-Folgenabschaetzung. Datenverarbeitung nur in EU/EWR. Transparenz.', verification_guidance: 'DiGA-Datenschutz und Datenlokalisierung pruefen.', source_url: null },
  { control_number: 'DIGA-02', title_nl: 'Informationssicherheit von DiGA (BSI TR-03161)', title: 'Information security of DiGA (BSI TR-03161)', description_nl: 'DiGA MUESSEN die Anforderungen der BSI TR-03161 (Mobile Health Applications Security) erfuellen. Dies umfasst sichere Authentisierung, Datenverschluesselung und sichere Kommunikation.', description: 'DiGA MUST meet BSI TR-03161 (Mobile Health Applications Security) requirements. This includes secure authentication, data encryption, and secure communication.', category: 'DiGA', subcategory: 'Informationssicherheit', level: 'Verpflichtend', iso_mapping: 'A.8.26', implementation_guidance: 'BSI TR-03161 umsetzen. Sichere Authentisierung. TLS. Datenverschluesselung.', verification_guidance: 'DiGA gegen BSI TR-03161 pruefen.', source_url: null },
  { control_number: 'DIGA-03', title_nl: 'Penetrationstest fuer DiGA', title: 'Penetration test for DiGA', description_nl: 'DiGA MUESSEN vor der Zulassung und regelmaessig danach einem Penetrationstest unterzogen werden. Die Ergebnisse MUESSEN dem BfArM vorgelegt werden.', description: 'DiGA MUST undergo penetration testing before approval and regularly thereafter. Results MUST be submitted to BfArM.', category: 'DiGA', subcategory: 'Sicherheitstests', level: 'Verpflichtend', iso_mapping: 'A.8.34', implementation_guidance: 'Penetrationstest vor Zulassung. Jaehrliche Wiederholung. BfArM-Berichterstattung.', verification_guidance: 'Penetrationstest-Berichte und BfArM-Einreichung pruefen.', source_url: null },
];

const output = {
  framework: {
    id: 'gematik-extended',
    name: 'Healthcare IT Security Extended (TI, KBV, DKG, DiGA)',
    name_nl: 'Gesundheits-IT-Sicherheit Erweitert (TI, KBV, DKG, DiGA)',
    issuing_body: 'gematik GmbH / KBV / DKG / BfArM',
    version: '2024',
    effective_date: '2024-01-01',
    scope: 'Extended healthcare IT security covering ePA, e-prescriptions, TI connectors, KBV practice security, DKG hospital systems (KIS, PACS), and DiGA (digital health applications) requirements',
    scope_sectors: ['healthcare'],
    structure_description: 'Four areas: Extended TI security (ePA, e-prescriptions, connectors, authentication), KBV practice IT (network, backup, access control, mobile), DKG hospital IT (HIS, PACS, §75c SGB V), and DiGA (data protection, BSI TR-03161, penetration testing).',
    source_url: 'https://www.gematik.de/telematikinfrastruktur',
    license: 'Public document',
    language: 'de+en',
  },
  controls,
  metadata: { ingested_at: new Date().toISOString(), total_controls: controls.length },
};

mkdirSync(DATA_DIR, { recursive: true });
writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
console.log(`gematik Extended: ${controls.length} controls written to ${OUTPUT_FILE}`);
