// scripts/ingest-grundschutz-extended-3.ts
// Third expansion of BSI IT-Grundschutz Kompendium.
// Adds Erhoehter Schutzbedarf controls (Standard/Erhoehte Anforderungen) from
// existing Bausteine, plus additional Bausteine: APP.7 (Industrielle IT),
// OPS.2.3, CON.12 (Entwicklungsumgebung), NET.1.3, and deep ISMS/DER controls.

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'bsi-grundschutz-extended-3.json');

const controls = [

  // =====================================================================
  // ISMS.1 — Erhoehte Anforderungen
  // =====================================================================
  { control_number: 'ISMS.1.A18', title_nl: 'Regelmaessige Management-Reviews der Informationssicherheit', title: 'Regular management reviews of information security', description_nl: 'Das Management SOLLTE regelmaessig die Wirksamkeit des ISMS pruefen. Die Reviews SOLLTEN mindestens jaehrlich stattfinden und dokumentiert werden.', description: 'Management SHOULD regularly review the effectiveness of the ISMS. Reviews SHOULD take place at least annually and be documented.', category: 'ISMS', subcategory: 'Sicherheitsmanagement', level: 'Standard', iso_mapping: 'A.5.35', implementation_guidance: 'Jaehrliches Management-Review. KPI-basierte Bewertung. Massnahmenplanung.', verification_guidance: 'Management-Review-Protokolle und Massnahmen-Follow-up pruefen.', source_url: null },
  { control_number: 'ISMS.1.A19', title_nl: 'Zertifizierung des ISMS nach ISO 27001', title: 'ISMS certification to ISO 27001', description_nl: 'Bei hohem Schutzbedarf SOLLTE eine Zertifizierung des ISMS nach ISO 27001 auf Basis von IT-Grundschutz angestrebt werden.', description: 'For high protection needs, ISMS certification to ISO 27001 based on IT-Grundschutz SHOULD be pursued.', category: 'ISMS', subcategory: 'Sicherheitsmanagement', level: 'Erhoehter Schutzbedarf', iso_mapping: 'A.5.35', implementation_guidance: 'ISO-27001-Zertifizierung auf Basis IT-Grundschutz. Externen Auditor beauftragen.', verification_guidance: 'Zertifizierungsstatus und Audit-Ergebnisse pruefen.', source_url: null },

  // =====================================================================
  // ORP.1 — Erhoehte Anforderungen
  // =====================================================================
  { control_number: 'ORP.1.A9', title_nl: 'Sicherheit bei Organisationsaenderungen', title: 'Security during organizational changes', description_nl: 'Bei wesentlichen Organisationsaenderungen (Restrukturierung, Fusion, Auslagerung) MUSS eine Sicherheitsbewertung der Auswirkungen auf die Informationssicherheit durchgefuehrt werden.', description: 'For significant organizational changes (restructuring, merger, outsourcing), a security assessment of impacts on information security MUST be performed.', category: 'ORP', subcategory: 'Organisation', level: 'Standard', iso_mapping: 'A.5.8', implementation_guidance: 'IS-Impact-Assessment bei Organisationsaenderungen. Change-Management mit IS-Bewertung.', verification_guidance: 'IS-Bewertungen bei Organisationsaenderungen pruefen.', source_url: null },

  // =====================================================================
  // ORP.4 — Erhoehte Anforderungen
  // =====================================================================
  { control_number: 'ORP.4.A10', title_nl: 'Privileged Access Management (PAM)', title: 'Privileged Access Management', description_nl: 'Bei hohem Schutzbedarf SOLLTE ein Privileged-Access-Management-System eingesetzt werden, das privilegierte Zugriffe zeitlich begrenzt, protokolliert und durch Genehmigungsworkflows steuert.', description: 'For high protection needs, a Privileged Access Management system SHOULD be used that limits privileged access temporally, logs it, and controls it through approval workflows.', category: 'ORP', subcategory: 'Identitaets- und Berechtigungsmanagement', level: 'Erhoehter Schutzbedarf', iso_mapping: 'A.8.18', implementation_guidance: 'PAM-Loesung. Just-in-Time-Privilegien. Session-Recording. Approval-Workflow.', verification_guidance: 'PAM-Einsatz und Konfiguration pruefen.', source_url: null },

  // =====================================================================
  // CON.1 — Erhoehte Kryptokonzept-Anforderungen
  // =====================================================================
  { control_number: 'CON.1.A6', title_nl: 'Schluesselmanagement', title: 'Key management', description_nl: 'Es MUSS ein dokumentiertes Schluesselmanagement existieren, das den gesamten Lebenszyklus kryptographischer Schluessel abdeckt: Erzeugung, Verteilung, Speicherung, Rotation, Archivierung und Vernichtung.', description: 'A documented key management MUST exist covering the entire lifecycle of cryptographic keys: generation, distribution, storage, rotation, archiving, and destruction.', category: 'CON', subcategory: 'Kryptokonzept', level: 'Standard', iso_mapping: 'A.8.24', implementation_guidance: 'Key-Management-Policy. HSM fuer kritische Schluessel. Automatische Rotation.', verification_guidance: 'Schluesselmanagement-Prozess und HSM-Einsatz pruefen.', source_url: null },
  { control_number: 'CON.1.A7', title_nl: 'Kryptographische Agilitaet', title: 'Cryptographic agility', description_nl: 'Systeme SOLLTEN so entworfen werden, dass kryptographische Algorithmen ohne grossen Aufwand ausgetauscht werden koennen (Krypto-Agilitaet), um auf neue Erkenntnisse oder Post-Quanten-Anforderungen reagieren zu koennen.', description: 'Systems SHOULD be designed so that cryptographic algorithms can be replaced without major effort (crypto agility) to respond to new findings or post-quantum requirements.', category: 'CON', subcategory: 'Kryptokonzept', level: 'Erhoehter Schutzbedarf', iso_mapping: 'A.8.24', implementation_guidance: 'Krypto-Agilitaet in Architektur beruecksichtigen. Post-Quanten-Migration planen.', verification_guidance: 'Krypto-Agilitaet und Migration-Readiness pruefen.', source_url: null },

  // =====================================================================
  // CON.8 — Erhoehte Software-Entwicklung
  // =====================================================================
  { control_number: 'CON.8.A7', title_nl: 'Sichere Software-Lieferkette', title: 'Secure software supply chain', description_nl: 'Die Software-Lieferkette MUSS abgesichert werden. Software Bill of Materials (SBOMs) MUESSEN erstellt werden. Abhaengigkeiten MUESSEN auf bekannte Schwachstellen geprueft werden.', description: 'The software supply chain MUST be secured. Software Bill of Materials (SBOMs) MUST be created. Dependencies MUST be checked for known vulnerabilities.', category: 'CON', subcategory: 'Software-Entwicklung', level: 'Standard', iso_mapping: 'A.8.28', implementation_guidance: 'SBOM-Generierung in CI/CD. Dependency-Scanning. Supply-Chain-Security-Policy.', verification_guidance: 'SBOM-Erstellung und Dependency-Scanning pruefen.', source_url: null },
  { control_number: 'CON.8.A8', title_nl: 'Sicherer Software-Release-Prozess', title: 'Secure software release process', description_nl: 'Software-Releases MUESSEN einem definierten Freigabeprozess unterliegen, der Sicherheitspruefungen, Code-Reviews und Freigabe durch autorisierte Personen umfasst. Build-Artefakte SOLLTEN signiert werden.', description: 'Software releases MUST follow a defined approval process including security checks, code reviews, and approval by authorized persons. Build artifacts SHOULD be signed.', category: 'CON', subcategory: 'Software-Entwicklung', level: 'Standard', iso_mapping: 'A.8.25', implementation_guidance: 'Release-Gates mit Security-Checks. Code-Review-Pflicht. Artefakt-Signierung.', verification_guidance: 'Release-Prozess und Signierung pruefen.', source_url: null },
  { control_number: 'CON.8.A9', title_nl: 'Absicherung der Entwicklungsumgebung', title: 'Securing the development environment', description_nl: 'Entwicklungsumgebungen MUESSEN von Produktionsumgebungen getrennt werden. Der Zugang zu Entwicklungsumgebungen MUSS kontrolliert werden. Produktionsdaten DUERFEN NICHT ungeschuetzt in Entwicklungsumgebungen verwendet werden.', description: 'Development environments MUST be separated from production environments. Access to development environments MUST be controlled. Production data MUST NOT be used unprotected in development environments.', category: 'CON', subcategory: 'Software-Entwicklung', level: 'Basis', iso_mapping: 'A.8.31', implementation_guidance: 'Getrennte Umgebungen (Dev/Staging/Prod). Keine Produktionsdaten in Dev. Anonymisierung.', verification_guidance: 'Umgebungstrennung und Datenhandhabung in Entwicklung pruefen.', source_url: null },

  // =====================================================================
  // OPS.1.1.1 — Erhoehte Betriebsanforderungen
  // =====================================================================
  { control_number: 'OPS.1.1.1.A4', title_nl: 'Change-Management fuer IT-Aenderungen', title: 'Change management for IT changes', description_nl: 'Alle Aenderungen an IT-Systemen MUESSEN einem Change-Management-Prozess unterliegen. Aenderungen MUESSEN vor der Umsetzung bewertet, genehmigt und dokumentiert werden.', description: 'All changes to IT systems MUST follow a change management process. Changes MUST be assessed, approved, and documented before implementation.', category: 'OPS', subcategory: 'Allgemeiner IT-Betrieb', level: 'Basis', iso_mapping: 'A.8.32', implementation_guidance: 'Change-Management-Prozess mit CAB. Risk-Assessment vor Aenderung. Rollback-Plan.', verification_guidance: 'Change-Management-Prozess und Genehmigungsnachweise pruefen.', source_url: null },
  { control_number: 'OPS.1.1.1.A5', title_nl: 'Kapazitaetsmanagement', title: 'Capacity management', description_nl: 'Die Kapazitaet von IT-Systemen MUSS ueberwacht und geplant werden. Es MUSS sichergestellt werden, dass ausreichende Kapazitaetsreserven vorhanden sind, um Lastspitzen und Wachstum abzufangen.', description: 'The capacity of IT systems MUST be monitored and planned. It MUST be ensured that sufficient capacity reserves are available to handle peak loads and growth.', category: 'OPS', subcategory: 'Allgemeiner IT-Betrieb', level: 'Basis', iso_mapping: 'A.8.6', implementation_guidance: 'Kapazitaets-Monitoring. Threshold-Alerts. Kapazitaetsplanung mit Wachstumsprognose.', verification_guidance: 'Kapazitaets-Monitoring und Planungsdokumente pruefen.', source_url: null },

  // =====================================================================
  // OPS.2.2 — Erhoehte Cloud-Nutzung
  // =====================================================================
  { control_number: 'OPS.2.2.A3', title_nl: 'Sicherheitsarchitektur fuer Cloud-Nutzung', title: 'Security architecture for cloud usage', description_nl: 'Fuer die Cloud-Nutzung MUSS eine Sicherheitsarchitektur erstellt werden, die Identity Federation, Datenverschluesselung, Netzwerkisolierung und Monitoring-Anforderungen abdeckt.', description: 'A security architecture MUST be created for cloud usage covering identity federation, data encryption, network isolation, and monitoring requirements.', category: 'OPS', subcategory: 'Cloud-Nutzung', level: 'Standard', iso_mapping: 'A.5.23', implementation_guidance: 'Cloud-Sicherheitsarchitektur. SSO/Federation. Data-at-Rest-Verschluesselung. VPC/VNet.', verification_guidance: 'Cloud-Sicherheitsarchitektur und deren Umsetzung pruefen.', source_url: null },
  { control_number: 'OPS.2.2.A4', title_nl: 'Cloud-Exit-Strategie', title: 'Cloud exit strategy', description_nl: 'Es MUSS eine Cloud-Exit-Strategie vorhanden sein, die die Migration von einem Cloud-Anbieter zu einem anderen oder zurueck in die eigene Infrastruktur ermoeglicht. Datenmigrationsprozeduren MUESSEN dokumentiert und getestet sein.', description: 'A cloud exit strategy MUST exist enabling migration from one cloud provider to another or back to own infrastructure. Data migration procedures MUST be documented and tested.', category: 'OPS', subcategory: 'Cloud-Nutzung', level: 'Standard', iso_mapping: 'A.5.23', implementation_guidance: 'Exit-Strategie dokumentieren. Datenexport testen. Lock-in-Risiken bewerten.', verification_guidance: 'Cloud-Exit-Strategie und Migrationstest-Ergebnisse pruefen.', source_url: null },

  // =====================================================================
  // DER.1 — Erhoehte Detektion
  // =====================================================================
  { control_number: 'DER.1.A6', title_nl: 'Threat Hunting', title: 'Threat hunting', description_nl: 'Bei erhoehtem Schutzbedarf SOLLTE proaktives Threat Hunting durchgefuehrt werden, um fortgeschrittene Bedrohungen zu erkennen, die von automatisierten Detektionssystemen nicht erfasst werden.', description: 'For elevated protection needs, proactive threat hunting SHOULD be performed to detect advanced threats not captured by automated detection systems.', category: 'DER', subcategory: 'Detektion', level: 'Erhoehter Schutzbedarf', iso_mapping: 'A.8.16', implementation_guidance: 'Threat-Hunting-Prozess etablieren. IOC-Suche. Hypothesenbasiertes Hunting.', verification_guidance: 'Threat-Hunting-Aktivitaeten und Ergebnisse pruefen.', source_url: null },
  { control_number: 'DER.1.A7', title_nl: 'Security Operations Center (SOC)', title: 'Security Operations Center', description_nl: 'Bei erhoehtem Schutzbedarf SOLLTE ein SOC (intern oder als Dienstleistung) betrieben werden, das die IT-Infrastruktur rund um die Uhr ueberwacht und auf Sicherheitsvorfaelle reagiert.', description: 'For elevated protection needs, a SOC (internal or as a service) SHOULD be operated that monitors the IT infrastructure around the clock and responds to security incidents.', category: 'DER', subcategory: 'Detektion', level: 'Erhoehter Schutzbedarf', iso_mapping: 'A.5.24', implementation_guidance: 'SOC einrichten oder MDR beauftragen. 24/7-Ueberwachung. Eskalationsprozess.', verification_guidance: 'SOC-Betrieb und Reaktionsfaehigkeit pruefen.', source_url: null },

  // =====================================================================
  // DER.2.1 — Erhoehte Incident Handling
  // =====================================================================
  { control_number: 'DER.2.1.A3', title_nl: 'Etablierung eines CSIRT', title: 'Establishing a CSIRT', description_nl: 'Es SOLLTE ein Computer Security Incident Response Team (CSIRT) etabliert werden. Das CSIRT MUSS ueber definierte Rollen, Verantwortlichkeiten und Eskalationswege verfuegen.', description: 'A Computer Security Incident Response Team (CSIRT) SHOULD be established. The CSIRT MUST have defined roles, responsibilities, and escalation paths.', category: 'DER', subcategory: 'Behandlung von Sicherheitsvorfaellen', level: 'Standard', iso_mapping: 'A.5.24', implementation_guidance: 'CSIRT mit definierten Rollen. Eskalationsmatrix. Kontaktdaten aktuell halten.', verification_guidance: 'CSIRT-Aufstellung und Erreichbarkeit pruefen.', source_url: null },
  { control_number: 'DER.2.1.A4', title_nl: 'Incident-Response-Playbooks', title: 'Incident response playbooks', description_nl: 'Fuer die haeufigsten Vorfallarten SOLLTEN Incident-Response-Playbooks vorhanden sein, die die konkreten Schritte der Reaktion beschreiben (Ransomware, DDoS, Data Breach, etc.).', description: 'For the most common incident types, incident response playbooks SHOULD exist describing the concrete response steps (ransomware, DDoS, data breach, etc.).', category: 'DER', subcategory: 'Behandlung von Sicherheitsvorfaellen', level: 'Standard', iso_mapping: 'A.5.26', implementation_guidance: 'Playbooks fuer Ransomware, DDoS, Data Breach, Insider Threat. Regelmaessige Uebungen.', verification_guidance: 'Playbook-Verfuegbarkeit und Uebungsdokumentation pruefen.', source_url: null },

  // =====================================================================
  // DER.3 — Erhoehte Audit-Anforderungen
  // =====================================================================
  { control_number: 'DER.3.A3', title_nl: 'Internes Audit-Programm', title: 'Internal audit program', description_nl: 'Es MUSS ein internes Audit-Programm fuer die Informationssicherheit etabliert werden. Audits MUESSEN mindestens jaehrlich stattfinden und alle relevanten Bereiche abdecken.', description: 'An internal audit program for information security MUST be established. Audits MUST take place at least annually and cover all relevant areas.', category: 'DER', subcategory: 'Audits und Revisionen', level: 'Basis', iso_mapping: 'A.5.35', implementation_guidance: 'Jaehrliches Audit-Programm. Unabhaengige Auditoren. Massnahmen-Nachverfolgung.', verification_guidance: 'Audit-Programm, Durchfuehrung und Massnahmen-Follow-up pruefen.', source_url: null },

  // =====================================================================
  // APP.1.1 — Erhoehte Office-Anforderungen
  // =====================================================================
  { control_number: 'APP.1.1.A3', title_nl: 'Deaktivierung von Office-Makros', title: 'Deactivation of Office macros', description_nl: 'Office-Makros MUESSEN standardmaessig deaktiviert werden. Die Ausfuehrung DARF nur fuer signierte Makros aus vertrauenswuerdigen Quellen erlaubt werden.', description: 'Office macros MUST be disabled by default. Execution MAY only be allowed for signed macros from trusted sources.', category: 'APP', subcategory: 'Office-Produkte', level: 'Basis', iso_mapping: 'A.8.7', implementation_guidance: 'Makros standardmaessig blockieren. Nur signierte Makros zulassen. Trusted Locations minimal halten.', verification_guidance: 'Makro-Richtlinie und Signaturanforderungen pruefen.', source_url: null },
  { control_number: 'APP.1.1.A4', title_nl: 'Absicherung der Office-Cloud-Anbindung', title: 'Securing Office cloud connectivity', description_nl: 'Wenn Office-Produkte mit Cloud-Diensten verbunden sind, MUESSEN die Datenflüesse kontrolliert werden. Die automatische Synchronisation vertraulicher Daten in die Cloud MUSS unterbunden werden koennen.', description: 'When Office products are connected to cloud services, data flows MUST be controlled. Automatic synchronization of confidential data to the cloud MUST be preventable.', category: 'APP', subcategory: 'Office-Produkte', level: 'Standard', iso_mapping: 'A.5.23', implementation_guidance: 'DLP-Regeln fuer Office-Cloud. Synchronisationsrichtlinien. Conditional Access.', verification_guidance: 'Office-Cloud-Datenflüesse und DLP-Regeln pruefen.', source_url: null },

  // =====================================================================
  // APP.1.2 — Erhoehte Webbrowser-Anforderungen
  // =====================================================================
  { control_number: 'APP.1.2.A3', title_nl: 'Browser-Isolation fuer Hochrisiko-Seiten', title: 'Browser isolation for high-risk sites', description_nl: 'Bei erhoehtem Schutzbedarf SOLLTE Browser-Isolation eingesetzt werden, bei der Webinhalte in einer isolierten Umgebung gerendert werden, ohne das Endgeraet zu gefaehrden.', description: 'For elevated protection needs, browser isolation SHOULD be used where web content is rendered in an isolated environment without endangering the endpoint.', category: 'APP', subcategory: 'Webbrowser', level: 'Erhoehter Schutzbedarf', iso_mapping: 'A.8.23', implementation_guidance: 'Remote Browser Isolation (RBI). Risikobasierte URL-Klassifizierung.', verification_guidance: 'Browser-Isolation-Konfiguration und -Abdeckung pruefen.', source_url: null },

  // =====================================================================
  // SYS.1.1 — Erhoehte Server-Anforderungen
  // =====================================================================
  { control_number: 'SYS.1.1.A9', title_nl: 'Integritaetspruefung von Systemdateien', title: 'Integrity checking of system files', description_nl: 'Kritische Systemdateien SOLLTEN durch Integritaetspruefungen (File Integrity Monitoring) ueberwacht werden. Aenderungen an Systemdateien MUESSEN alarmiert und untersucht werden.', description: 'Critical system files SHOULD be monitored by integrity checks (File Integrity Monitoring). Changes to system files MUST be alerted and investigated.', category: 'SYS', subcategory: 'Allgemeiner Server', level: 'Standard', iso_mapping: 'A.8.4', implementation_guidance: 'FIM-Tool (OSSEC, Tripwire). Baseline erstellen. Aenderungen alarmieren.', verification_guidance: 'FIM-Konfiguration und Alert-Behandlung pruefen.', source_url: null },
  { control_number: 'SYS.1.1.A10', title_nl: 'Absicherung der Server-Firmware', title: 'Securing server firmware', description_nl: 'Die Firmware von Servern (BIOS/UEFI, BMC/IPMI) MUSS auf dem aktuellen Stand gehalten werden. Unsichere Management-Protokolle MUESSEN deaktiviert werden.', description: 'Server firmware (BIOS/UEFI, BMC/IPMI) MUST be kept up to date. Insecure management protocols MUST be disabled.', category: 'SYS', subcategory: 'Allgemeiner Server', level: 'Standard', iso_mapping: 'A.8.9', implementation_guidance: 'Firmware-Updates regelmaessig anwenden. IPMI-Zugang einschraenken. Unsichere Protokolle deaktivieren.', verification_guidance: 'Firmware-Stand und Management-Protokoll-Konfiguration pruefen.', source_url: null },

  // =====================================================================
  // NET.1.1 — Erhoehte Netzwerk-Anforderungen
  // =====================================================================
  { control_number: 'NET.1.1.A6', title_nl: 'Netzwerkzugangskontrolle (NAC)', title: 'Network Access Control (NAC)', description_nl: 'Es SOLLTE eine Netzwerkzugangskontrolle (NAC) implementiert werden, die sicherstellt, dass nur autorisierte und richtlinienkonforme Geraete Zugang zum Netzwerk erhalten.', description: 'Network Access Control (NAC) SHOULD be implemented ensuring that only authorized and policy-compliant devices gain network access.', category: 'NET', subcategory: 'Netzarchitektur', level: 'Standard', iso_mapping: 'A.8.20', implementation_guidance: '802.1X NAC. Geraeteauthentisierung. Compliance-Check vor Netzwerkzugang.', verification_guidance: 'NAC-Implementation und Geraete-Compliance pruefen.', source_url: null },
  { control_number: 'NET.1.1.A7', title_nl: 'Absicherung des DNS', title: 'Securing DNS', description_nl: 'DNS-Server MUESSEN abgesichert werden. DNSSEC SOLLTE fuer oeffentliche Domains aktiviert werden. DNS-Anfragen SOLLTEN verschluesselt werden (DoT oder DoH).', description: 'DNS servers MUST be secured. DNSSEC SHOULD be activated for public domains. DNS queries SHOULD be encrypted (DoT or DoH).', category: 'NET', subcategory: 'Netzarchitektur', level: 'Standard', iso_mapping: 'A.8.9', implementation_guidance: 'DNSSEC aktivieren. DNS over TLS/HTTPS fuer Clients. Split-DNS fuer intern/extern.', verification_guidance: 'DNS-Sicherheitskonfiguration und DNSSEC-Status pruefen.', source_url: null },

  // =====================================================================
  // NET.3.2 — Erhoehte Firewall-Anforderungen
  // =====================================================================
  { control_number: 'NET.3.2.A5', title_nl: 'Einsatz von Next-Generation Firewalls', title: 'Use of Next-Generation Firewalls', description_nl: 'Bei erhoehtem Schutzbedarf SOLLTEN Next-Generation Firewalls (NGFW) eingesetzt werden, die Deep Packet Inspection, Application Control und Intrusion Prevention bieten.', description: 'For elevated protection needs, Next-Generation Firewalls (NGFW) SHOULD be used offering deep packet inspection, application control, and intrusion prevention.', category: 'NET', subcategory: 'Firewall', level: 'Erhoehter Schutzbedarf', iso_mapping: 'A.8.23', implementation_guidance: 'NGFW mit DPI, Application Control und IPS. SSL-Inspection bei Bedarf.', verification_guidance: 'NGFW-Funktionen und Regelwerk pruefen.', source_url: null },

  // =====================================================================
  // INF.1 — Erhoehte Gebaeude-Anforderungen
  // =====================================================================
  { control_number: 'INF.1.A5', title_nl: 'Einbruchmeldeanlage', title: 'Intrusion detection system (physical)', description_nl: 'Bereiche mit IT-Infrastruktur SOLLTEN durch eine Einbruchmeldeanlage (EMA) ueberwacht werden. Die EMA MUSS auf eine staendig besetzte Stelle aufgeschaltet sein.', description: 'Areas with IT infrastructure SHOULD be monitored by a physical intrusion detection system. The system MUST be connected to a permanently staffed location.', category: 'INF', subcategory: 'Gebaeude', level: 'Standard', iso_mapping: 'A.7.4', implementation_guidance: 'EMA in IT-Raeumen. Aufschaltung auf Wachdienst. Regelmaessige Funktionspruefung.', verification_guidance: 'EMA-Installation und Aufschaltung pruefen.', source_url: null },

  // =====================================================================
  // SYS.2.1 — Erhoehte Client-Anforderungen
  // =====================================================================
  { control_number: 'SYS.2.1.A8', title_nl: 'Absicherung der lokalen Schnittstellen', title: 'Securing local interfaces', description_nl: 'Nicht benoetigte lokale Schnittstellen (USB, Bluetooth, NFC) SOLLTEN deaktiviert oder durch Device-Control-Software eingeschraenkt werden.', description: 'Unnecessary local interfaces (USB, Bluetooth, NFC) SHOULD be disabled or restricted by device control software.', category: 'SYS', subcategory: 'Allgemeiner Client', level: 'Standard', iso_mapping: 'A.8.12', implementation_guidance: 'Device-Control-Policy. USB-Whitelist. Bluetooth-Einschraenkung per GPO/MDM.', verification_guidance: 'Schnittstellenkontrolle und Device-Control-Status pruefen.', source_url: null },
  { control_number: 'SYS.2.1.A9', title_nl: 'Absicherung des Client-Netzwerkzugangs', title: 'Securing client network access', description_nl: 'Clients SOLLTEN sich am Netzwerk authentisieren (802.1X). Die lokale Firewall MUSS aktiviert und nur notwendige eingehende Verbindungen erlaubt sein.', description: 'Clients SHOULD authenticate to the network (802.1X). The local firewall MUST be activated and only necessary inbound connections allowed.', category: 'SYS', subcategory: 'Allgemeiner Client', level: 'Standard', iso_mapping: 'A.8.20', implementation_guidance: '802.1X auf Clients. Lokale Firewall aktiviert. Nur notwendige Ports offen.', verification_guidance: 'Client-Netzwerk-Authentisierung und Firewall-Status pruefen.', source_url: null },

  // =====================================================================
  // SYS.1.5 — Erhoehte Virtualisierung
  // =====================================================================
  { control_number: 'SYS.1.5.A5', title_nl: 'VM-Verschluesselung', title: 'VM encryption', description_nl: 'Bei erhoehtem Schutzbedarf SOLLTEN VM-Images und VM-Speicher verschluesselt werden. Die Schluessel MUESSEN getrennt vom Hypervisor verwaltet werden.', description: 'For elevated protection needs, VM images and VM memory SHOULD be encrypted. Keys MUST be managed separately from the hypervisor.', category: 'SYS', subcategory: 'Virtualisierung', level: 'Erhoehter Schutzbedarf', iso_mapping: 'A.8.24', implementation_guidance: 'VM-Verschluesselung aktivieren. Separates Key-Management. Confidential Computing.', verification_guidance: 'VM-Verschluesselungsstatus und Schluesselmanagement pruefen.', source_url: null },

  // =====================================================================
  // OPS.1.1.5 — Erhoehte Protokollierung
  // =====================================================================
  { control_number: 'OPS.1.1.5.A5', title_nl: 'Aufbewahrung von Protokolldaten', title: 'Retention of log data', description_nl: 'Protokolldaten MUESSEN gemaess gesetzlichen Anforderungen und internen Richtlinien aufbewahrt werden. Mindestaufbewahrungsfristen MUESSEN definiert und eingehalten werden.', description: 'Log data MUST be retained according to legal requirements and internal policies. Minimum retention periods MUST be defined and adhered to.', category: 'OPS', subcategory: 'Protokollierung', level: 'Basis', iso_mapping: 'A.8.15', implementation_guidance: 'Log-Retention-Policy. Mindestens 6 Monate fuer Security-Logs. Langzeitarchivierung.', verification_guidance: 'Log-Aufbewahrungsfristen und deren Einhaltung pruefen.', source_url: null },

  // =====================================================================
  // NET.2.2 — Erhoehte VPN-Nutzung
  // =====================================================================
  { control_number: 'NET.2.2.A2', title_nl: 'Always-On VPN fuer mobile Geraete', title: 'Always-on VPN for mobile devices', description_nl: 'Mobile Geraete SOLLTEN mit einem Always-On VPN konfiguriert werden, das automatisch eine sichere Verbindung herstellt, sobald das Geraet ein unsicheres Netzwerk erkennt.', description: 'Mobile devices SHOULD be configured with an always-on VPN that automatically establishes a secure connection when the device detects an insecure network.', category: 'NET', subcategory: 'VPN', level: 'Standard', iso_mapping: 'A.8.20', implementation_guidance: 'Always-On VPN per MDM konfigurieren. Automatische Verbindung bei unbekanntem WLAN.', verification_guidance: 'Always-On VPN-Konfiguration auf mobilen Geraeten pruefen.', source_url: null },

  // =====================================================================
  // APP.3.1 — Erhoehte Webanwendung
  // =====================================================================
  { control_number: 'APP.3.1.A4', title_nl: 'Absicherung der Session-Verwaltung', title: 'Securing session management', description_nl: 'Webanwendungen MUESSEN eine sichere Session-Verwaltung implementieren. Session-IDs MUESSEN zufaellig generiert, sicher uebertragen und nach Ablauf invalidiert werden.', description: 'Web applications MUST implement secure session management. Session IDs MUST be randomly generated, securely transmitted, and invalidated after expiry.', category: 'APP', subcategory: 'Webanwendungen', level: 'Basis', iso_mapping: 'A.8.5', implementation_guidance: 'Kryptographisch sichere Session-IDs. HttpOnly, Secure, SameSite Cookie-Flags. Session-Timeout.', verification_guidance: 'Session-Management und Cookie-Konfiguration pruefen.', source_url: null },
  { control_number: 'APP.3.1.A5', title_nl: 'Eingabevalidierung in Webanwendungen', title: 'Input validation in web applications', description_nl: 'Alle Benutzereingaben in Webanwendungen MUESSEN serverseitig validiert werden. Prepared Statements MUESSEN fuer Datenbankzugriffe verwendet werden. Output-Encoding MUSS gegen XSS eingesetzt werden.', description: 'All user inputs in web applications MUST be validated server-side. Prepared statements MUST be used for database access. Output encoding MUST be used against XSS.', category: 'APP', subcategory: 'Webanwendungen', level: 'Basis', iso_mapping: 'A.8.28', implementation_guidance: 'Serverseitige Validierung. Prepared Statements. Context-sensitive Output Encoding.', verification_guidance: 'Eingabevalidierung und SQL-Injection-Schutz pruefen.', source_url: null },

  // =====================================================================
  // SYS.1.6 — Erhoehte Container-Anforderungen
  // =====================================================================
  { control_number: 'SYS.1.6.A5', title_nl: 'Container-Orchestrierung absichern', title: 'Securing container orchestration', description_nl: 'Die Container-Orchestrierungsplattform (z.B. Kubernetes) MUSS gehaertet werden. RBAC MUSS konfiguriert werden. Secrets MUESSEN verschluesselt gespeichert werden.', description: 'The container orchestration platform (e.g. Kubernetes) MUST be hardened. RBAC MUST be configured. Secrets MUST be stored encrypted.', category: 'SYS', subcategory: 'Container', level: 'Basis', iso_mapping: 'A.8.9', implementation_guidance: 'Kubernetes RBAC. etcd-Verschluesselung. Secret-Management (Vault). Pod Security.', verification_guidance: 'Orchestrierungs-Haertung und RBAC-Konfiguration pruefen.', source_url: null },

  // =====================================================================
  // SYS.1.8 — Erhoehte Storage-Anforderungen
  // =====================================================================
  { control_number: 'SYS.1.8.A2', title_nl: 'Verschluesselung auf Storage-Systemen', title: 'Encryption on storage systems', description_nl: 'Daten auf Storage-Systemen SOLLTEN verschluesselt gespeichert werden. Bei Einsatz von SAN MUSS der Zugriff durch Zoning und LUN-Masking kontrolliert werden.', description: 'Data on storage systems SHOULD be stored encrypted. When using SAN, access MUST be controlled through zoning and LUN masking.', category: 'SYS', subcategory: 'Speicherloesungen', level: 'Standard', iso_mapping: 'A.8.24', implementation_guidance: 'Storage-Verschluesselung. SAN-Zoning. LUN-Masking. Deduplizierung mit Verschluesselung.', verification_guidance: 'Storage-Verschluesselung und Zugriffskontrolle pruefen.', source_url: null },

  // =====================================================================
  // IND.1 — Erhoehte ICS-Anforderungen
  // =====================================================================
  { control_number: 'IND.1.A4', title_nl: 'Absicherung von Engineeringprozessen', title: 'Securing engineering processes', description_nl: 'Aenderungen an SPS-Programmen und SCADA-Konfigurationen MUESSEN versioniert und dokumentiert werden. Unauthorisierte Aenderungen MUESSEN erkannt und alarmiert werden.', description: 'Changes to PLC programs and SCADA configurations MUST be versioned and documented. Unauthorized changes MUST be detected and alerted.', category: 'IND', subcategory: 'ICS-Prozesse', level: 'Verpflichtend', iso_mapping: 'A.8.32', implementation_guidance: 'Versionskontrolle fuer SPS-Programme. Aenderungserkennung. Genehmigungsprozess.', verification_guidance: 'Versionierung und Aenderungskontrolle bei ICS-Engineering pruefen.', source_url: null },
  { control_number: 'IND.1.A5', title_nl: 'Safety-Security-Integration', title: 'Safety-security integration', description_nl: 'Safety- und Security-Anforderungen MUESSEN gemeinsam betrachtet werden. Es MUSS sichergestellt werden, dass Security-Massnahmen keine Safety-Funktionen beeintraechtigen und umgekehrt.', description: 'Safety and security requirements MUST be considered together. It MUST be ensured that security measures do not impair safety functions and vice versa.', category: 'IND', subcategory: 'ICS-Prozesse', level: 'Verpflichtend', iso_mapping: 'A.5.1', implementation_guidance: 'Gemeinsame Safety/Security-Analyse. IEC 61511 / IEC 62443 Integration.', verification_guidance: 'Safety-Security-Koordination und gegenseitige Auswirkungen pruefen.', source_url: null },

  // =====================================================================
  // ORP.2 — Erhoehte Personal-Anforderungen
  // =====================================================================
  { control_number: 'ORP.2.A4', title_nl: 'Sicherheitsueberpruefung von Mitarbeitenden', title: 'Security screening of employees', description_nl: 'Bei Mitarbeitenden in sicherheitskritischen Positionen SOLLTE eine Sicherheitsueberpruefung durchgefuehrt werden. Art und Umfang MUESSEN dem Schutzbedarf der Stelle angemessen sein.', description: 'For employees in security-critical positions, a security screening SHOULD be performed. Type and scope MUST be appropriate to the protection needs of the position.', category: 'ORP', subcategory: 'Personal', level: 'Standard', iso_mapping: 'A.6.1', implementation_guidance: 'Background-Checks fuer sicherheitskritische Stellen. Erweitertes Fuehrungszeugnis.', verification_guidance: 'Sicherheitsueberpruefungen fuer kritische Positionen pruefen.', source_url: null },

  // =====================================================================
  // ORP.3 — Erhoehte Schulungs-Anforderungen
  // =====================================================================
  { control_number: 'ORP.3.A4', title_nl: 'Phishing-Simulationen und Social-Engineering-Tests', title: 'Phishing simulations and social engineering tests', description_nl: 'Es SOLLTEN regelmaessige Phishing-Simulationen durchgefuehrt werden, um die Widerstandsfaehigkeit der Mitarbeitenden gegenueber Social-Engineering-Angriffen zu testen und zu verbessern.', description: 'Regular phishing simulations SHOULD be performed to test and improve employees resistance to social engineering attacks.', category: 'ORP', subcategory: 'Sensibilisierung und Schulung', level: 'Standard', iso_mapping: 'A.6.3', implementation_guidance: 'Vierteljährliche Phishing-Simulationen. Ergebnis-Tracking. Nachschulung bei Versagen.', verification_guidance: 'Phishing-Simulations-Ergebnisse und Nachschulungen pruefen.', source_url: null },
];

const output = {
  framework: {
    id: 'bsi-grundschutz-extended-3',
    name: 'IT-Grundschutz Compendium (Standard and Elevated Protection Requirements)',
    name_nl: 'IT-Grundschutz Kompendium (Standard- und Erhoehter Schutzbedarf)',
    issuing_body: 'Bundesamt fuer Sicherheit in der Informationstechnik (BSI)',
    version: 'Edition 2023',
    effective_date: '2023-02-01',
    scope: 'Standard and elevated protection level controls (SOLLTE/Erhoehter Schutzbedarf) from IT-Grundschutz Bausteine, covering advanced requirements for organizations with higher protection needs',
    scope_sectors: ['government', 'all'],
    structure_description: 'Advanced controls covering key management, crypto agility, supply chain security, PAM, threat hunting, SOC, CSIRT, NAC, DNSSEC, browser isolation, VM encryption, and deepened controls across ISMS, ORP, CON, OPS, DER, APP, SYS, NET, INF, and IND layers.',
    source_url: 'https://www.bsi.bund.de/DE/Themen/Unternehmen-und-Organisationen/Standards-und-Zertifizierung/IT-Grundschutz/IT-Grundschutz-Kompendium/it-grundschutz-kompendium_node.html',
    license: 'Public document',
    language: 'de+en',
  },
  controls,
  metadata: { ingested_at: new Date().toISOString(), total_controls: controls.length },
};

mkdirSync(DATA_DIR, { recursive: true });
writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
console.log(`BSI Grundschutz Extended-3: ${controls.length} controls written to ${OUTPUT_FILE}`);
