// scripts/ingest-bafin-extended.ts
// Extended BaFin IT requirements — deeper BAIT controls, VAIT specifics,
// KAIT (capital management), ZAIT (payment services), and MaRisk IT requirements.

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', 'data', 'extracted');
const OUTPUT_FILE = join(DATA_DIR, 'bafin-extended.json');

const controls = [
  // BAIT — Extended Bankaufsichtliche Anforderungen an die IT
  { control_number: 'BAIT-EXT-01', title_nl: 'IT-Notfallmanagement (Tz. 9)', title: 'IT emergency management', description_nl: 'Das Institut MUSS ein IT-Notfallmanagement etablieren, das die Wiederherstellung des IT-Betriebs bei Stoerungen sicherstellt. Die Notfallplaene MUESSEN regelmaessig getestet werden.', description: 'The institution MUST establish IT emergency management ensuring restoration of IT operations during disruptions. Emergency plans MUST be regularly tested.', category: 'BAIT', subcategory: 'IT-Notfallmanagement', level: 'Verpflichtend', iso_mapping: 'A.5.29', implementation_guidance: 'IT-Notfallplaene mit BIA. RTO/RPO pro System. Jaehrliche DR-Tests.', verification_guidance: 'IT-Notfallplaene und DR-Testergebnisse pruefen.', source_url: 'https://www.bafin.de/SharedDocs/Veroeffentlichungen/DE/Rundschreiben/2022/rs_2022_10_ba_BAIT.html' },
  { control_number: 'BAIT-EXT-02', title_nl: 'Benutzerberechtigungsmanagement (Tz. 6)', title: 'User authorization management', description_nl: 'Das Benutzerberechtigungsmanagement MUSS sicherstellen, dass Zugriffsrechte nach dem Minimalprinzip vergeben und regelmaessig rezertifiziert werden. Privilegierte Berechtigungen MUESSEN besonders kontrolliert werden.', description: 'User authorization management MUST ensure access rights are granted according to the least privilege principle and regularly recertified. Privileged authorizations MUST be specially controlled.', category: 'BAIT', subcategory: 'Benutzerberechtigungsmanagement', level: 'Verpflichtend', iso_mapping: 'A.8.2', implementation_guidance: 'RBAC mit Minimalprinzip. Rezertifizierung halbjaehrlich. PAM fuer privilegierte Konten.', verification_guidance: 'Berechtigungsvergabe und Rezertifizierungsnachweise pruefen.', source_url: null },
  { control_number: 'BAIT-EXT-03', title_nl: 'IT-Betrieb und Aenderungsmanagement (Tz. 8)', title: 'IT operations and change management', description_nl: 'Der IT-Betrieb MUSS durch ein formalisiertes Change-Management gesteuert werden. Aenderungen MUESSEN bewertet, genehmigt, getestet und dokumentiert werden. Notfallaenderungen MUESSEN nachtraeglich genehmigt werden.', description: 'IT operations MUST be managed through formalized change management. Changes MUST be assessed, approved, tested, and documented. Emergency changes MUST be approved retroactively.', category: 'BAIT', subcategory: 'IT-Betrieb', level: 'Verpflichtend', iso_mapping: 'A.8.32', implementation_guidance: 'Change-Management mit CAB. Testing vor Deployment. Nachtraegliche Genehmigung bei Notfall.', verification_guidance: 'Change-Management-Prozess und Genehmigungsnachweise pruefen.', source_url: null },
  { control_number: 'BAIT-EXT-04', title_nl: 'Auslagerungsmanagement fuer IT-Dienstleistungen (Tz. 7)', title: 'Outsourcing management for IT services', description_nl: 'Bei der Auslagerung von IT-Dienstleistungen MUESSEN Sicherheitsanforderungen vertraglich festgelegt werden. Die Einhaltung MUSS ueberwacht werden. Wesentliche Auslagerungen beduerften der BaFin-Anzeige.', description: 'When outsourcing IT services, security requirements MUST be contractually defined. Compliance MUST be monitored. Material outsourcings require BaFin notification.', category: 'BAIT', subcategory: 'Auslagerungsmanagement', level: 'Verpflichtend', iso_mapping: 'A.5.20', implementation_guidance: 'Sicherheitsanforderungen in Auslagerungsvertraegen. Regelmaessige Audits. BaFin-Anzeige.', verification_guidance: 'Auslagerungsvertraege und Auditberichte pruefen.', source_url: null },
  { control_number: 'BAIT-EXT-05', title_nl: 'IT-Architektur und Systemlandschaft (Tz. 3)', title: 'IT architecture and system landscape', description_nl: 'Das Institut MUSS eine aktuelle und vollstaendige Dokumentation der IT-Architektur und Systemlandschaft vorhalten. Abhaengigkeiten zwischen Systemen MUESSEN dokumentiert sein.', description: 'The institution MUST maintain current and complete documentation of the IT architecture and system landscape. Dependencies between systems MUST be documented.', category: 'BAIT', subcategory: 'IT-Architektur', level: 'Verpflichtend', iso_mapping: 'A.5.9', implementation_guidance: 'IT-Architektur-Dokumentation. Systemlandkarte. Abhaengigkeitsanalyse.', verification_guidance: 'IT-Architektur-Dokumentation und Aktualitaet pruefen.', source_url: null },

  // VAIT — Versicherungsaufsichtliche Anforderungen an die IT
  { control_number: 'VAIT-01', title_nl: 'IT-Governance im Versicherungsunternehmen', title: 'IT governance in insurance companies', description_nl: 'Versicherungsunternehmen MUESSEN eine IT-Governance etablieren, die die IT-Strategie an die Geschaeftsstrategie koppelt. Die IT-Governance MUSS vom Vorstand verantwortet werden.', description: 'Insurance companies MUST establish IT governance linking IT strategy to business strategy. IT governance MUST be the responsibility of the board.', category: 'VAIT', subcategory: 'IT-Governance', level: 'Verpflichtend', iso_mapping: 'A.5.1', implementation_guidance: 'IT-Governance-Framework. IT-Strategie vom Vorstand genehmigt. Regelmaessige Reviews.', verification_guidance: 'IT-Governance und Vorstands-Verantwortung pruefen.', source_url: null },
  { control_number: 'VAIT-02', title_nl: 'Aktuarielle IT-Systeme absichern', title: 'Securing actuarial IT systems', description_nl: 'IT-Systeme fuer aktuarielle Berechnungen (Reservierung, Pricing) MUESSEN besonders geschuetzt werden. Die Integritaet der Berechnungsergebnisse MUSS sichergestellt werden.', description: 'IT systems for actuarial calculations (reserving, pricing) MUST be specially protected. The integrity of calculation results MUST be ensured.', category: 'VAIT', subcategory: 'Aktuarielle Systeme', level: 'Verpflichtend', iso_mapping: 'A.8.4', implementation_guidance: 'Zugriffskontrolle fuer aktuarielle Systeme. Integritaetspruefung. Audit-Trail.', verification_guidance: 'Schutz aktuarieller Systeme und Datenintegritaet pruefen.', source_url: null },
  { control_number: 'VAIT-03', title_nl: 'Schutz von Versicherungsnehmerdaten', title: 'Protection of policyholder data', description_nl: 'Daten der Versicherungsnehmer MUESSEN nach dem Need-to-Know-Prinzip geschuetzt werden. Gesundheitsdaten MUESSEN besonders geschuetzt werden (Artikel 9 DSGVO).', description: 'Policyholder data MUST be protected according to the need-to-know principle. Health data MUST be specially protected (Article 9 GDPR).', category: 'VAIT', subcategory: 'Datenschutz', level: 'Verpflichtend', iso_mapping: 'A.5.34', implementation_guidance: 'Need-to-Know fuer VN-Daten. Besonderer Schutz fuer Gesundheitsdaten. Verschluesselung.', verification_guidance: 'Schutz der Versicherungsnehmerdaten pruefen.', source_url: null },

  // KAIT — Kapitalverwaltungsaufsichtliche Anforderungen an die IT
  { control_number: 'KAIT-01', title_nl: 'IT-Risikomanagement bei Kapitalverwaltungsgesellschaften', title: 'IT risk management at capital management companies', description_nl: 'Kapitalverwaltungsgesellschaften MUESSEN ein IT-Risikomanagement implementieren, das die spezifischen Risiken der Fondsverwaltung und des Wertpapierhandels beruecksichtigt.', description: 'Capital management companies MUST implement IT risk management considering the specific risks of fund management and securities trading.', category: 'KAIT', subcategory: 'IT-Risikomanagement', level: 'Verpflichtend', iso_mapping: 'A.5.7', implementation_guidance: 'IT-Risikomanagement mit Fokus auf Handelssysteme. Marktrisiko-IT. Settlement-IT.', verification_guidance: 'IT-Risikomanagement fuer Fondsverwaltung pruefen.', source_url: null },
  { control_number: 'KAIT-02', title_nl: 'Absicherung von Handelssystemen', title: 'Securing trading systems', description_nl: 'Handelssysteme MUESSEN besonders abgesichert werden. Zugriff MUSS strikt kontrolliert werden. Transaktionsintegritaet MUSS durch kryptographische Verfahren sichergestellt werden.', description: 'Trading systems MUST be specially secured. Access MUST be strictly controlled. Transaction integrity MUST be ensured through cryptographic methods.', category: 'KAIT', subcategory: 'Handelssysteme', level: 'Verpflichtend', iso_mapping: 'A.8.24', implementation_guidance: 'Zugriffskontrolle fuer Handelssysteme. Transaktionssignierung. Audit-Trail.', verification_guidance: 'Sicherheit der Handelssysteme und Transaktionsintegritaet pruefen.', source_url: null },

  // ZAIT — Zahlungsdiensteaufsichtliche Anforderungen an die IT
  { control_number: 'ZAIT-01', title_nl: 'IT-Sicherheit bei Zahlungsdienstleistern', title: 'IT security at payment service providers', description_nl: 'Zahlungsdienstleister MUESSEN ein IT-Sicherheitsmanagement implementieren, das die PSD2-Anforderungen an starke Kundenauthentifizierung (SCA) und sichere Kommunikation erfuellt.', description: 'Payment service providers MUST implement IT security management meeting PSD2 requirements for strong customer authentication (SCA) and secure communication.', category: 'ZAIT', subcategory: 'IT-Sicherheit', level: 'Verpflichtend', iso_mapping: 'A.8.5', implementation_guidance: 'SCA-Implementation (PSD2). Transaktionsueberwachung. Sichere API-Kommunikation.', verification_guidance: 'SCA-Implementation und PSD2-Konformitaet pruefen.', source_url: null },
  { control_number: 'ZAIT-02', title_nl: 'Transaktionsueberwachung und Betrugspreävention', title: 'Transaction monitoring and fraud prevention', description_nl: 'Zahlungsdienstleister MUESSEN Transaktionsueberwachungssysteme betreiben, die verdaechtige Transaktionen in Echtzeit erkennen. Dynamische Risikoanalyse MUSS implementiert werden.', description: 'Payment service providers MUST operate transaction monitoring systems that detect suspicious transactions in real time. Dynamic risk analysis MUST be implemented.', category: 'ZAIT', subcategory: 'Transaktionsueberwachung', level: 'Verpflichtend', iso_mapping: 'A.8.16', implementation_guidance: 'Echtzeit-Transaktionsueberwachung. Risikobasierte Analyse. Machine-Learning-Modelle.', verification_guidance: 'Transaktionsueberwachung und Fraud-Detection pruefen.', source_url: null },

  // MaRisk — Extended IT-related requirements
  { control_number: 'MARISK-IT-01', title_nl: 'IT-Risikosteuerung nach MaRisk (AT 7.2)', title: 'IT risk control per MaRisk', description_nl: 'Die IT-Risikosteuerung MUSS in das institutsweite Risikomanagement integriert sein. IT-Risiken MUESSEN quantifiziert und im Risikoappetit des Instituts beruecksichtigt werden.', description: 'IT risk control MUST be integrated into the institution-wide risk management. IT risks MUST be quantified and considered in the institution risk appetite.', category: 'MaRisk', subcategory: 'IT-Risiko', level: 'Verpflichtend', iso_mapping: 'A.5.7', implementation_guidance: 'IT-Risiken in Risikotragfaehigkeit. Quantifizierung von IT-Risiken. Limitsystem.', verification_guidance: 'Integration von IT-Risiken in Gesamtrisikomanagement pruefen.', source_url: null },
  { control_number: 'MARISK-IT-02', title_nl: 'Kontrollsystem fuer IT-Prozesse (AT 4.3)', title: 'Control system for IT processes', description_nl: 'Es MUSS ein wirksames internes Kontrollsystem (IKS) fuer IT-Prozesse bestehen. Kontrollen MUESSEN dokumentiert, getestet und deren Wirksamkeit regelmaessig ueberprueft werden.', description: 'An effective internal control system (ICS) for IT processes MUST exist. Controls MUST be documented, tested, and their effectiveness regularly verified.', category: 'MaRisk', subcategory: 'Internes Kontrollsystem', level: 'Verpflichtend', iso_mapping: 'A.5.35', implementation_guidance: 'IKS fuer IT-Prozesse. Kontrollmatrix. Wirksamkeitstests. Meldung an Vorstand.', verification_guidance: 'IT-IKS und Wirksamkeitsnachweise pruefen.', source_url: null },
];

const output = {
  framework: {
    id: 'bafin-extended',
    name: 'BaFin IT Requirements Extended (BAIT/VAIT/KAIT/ZAIT/MaRisk)',
    name_nl: 'BaFin IT-Anforderungen Erweitert (BAIT/VAIT/KAIT/ZAIT/MaRisk)',
    issuing_body: 'Bundesanstalt fuer Finanzdienstleistungsaufsicht (BaFin)',
    version: '2024',
    effective_date: '2024-01-01',
    scope: 'Extended financial sector IT requirements: deeper BAIT controls, VAIT for insurers, KAIT for capital managers, ZAIT for payment providers, and MaRisk IT risk management integration',
    scope_sectors: ['finance'],
    structure_description: 'Covers extended BAIT (emergency management, authorization, operations, outsourcing, architecture), VAIT (insurance governance, actuarial systems, policyholder data), KAIT (trading systems, fund management), ZAIT (SCA, transaction monitoring), and MaRisk (IT risk integration, internal controls).',
    source_url: 'https://www.bafin.de/SharedDocs/Veroeffentlichungen/DE/Rundschreiben/2022/rs_2022_10_ba_BAIT.html',
    license: 'Public sector publication',
    language: 'de+en',
  },
  controls,
  metadata: { ingested_at: new Date().toISOString(), total_controls: controls.length },
};

mkdirSync(DATA_DIR, { recursive: true });
writeFileSync(OUTPUT_FILE, JSON.stringify(output, null, 2), 'utf-8');
console.log(`BaFin Extended: ${controls.length} controls written to ${OUTPUT_FILE}`);
